// Le conditionnel présent.
export const CONDITIONNEL_PRESENT = {
  id: "conditionnel-present",
  t: "Le conditionnel présent",
  d: "« Je voudrais » : la politesse, l'hypothèse, le souhait.",
  level: "B1",
  use: "Une demande polie, un souhait, une hypothèse, une information non confirmée.",
  lesson: [
    "Formation : le RADICAL DU FUTUR + les TERMINAISONS DE L'IMPARFAIT (-ais, -ais, -ait, -ions, -iez, -aient). « Je parlerai » (futur) → « je parlerais » (conditionnel).",
    "Comme il partage son radical avec le futur, tous les irréguliers du futur se retrouvent ici : être → serais, avoir → aurais, aller → irais, faire → ferais, pouvoir → pourrais, vouloir → voudrais, devoir → devrais, savoir → saurais, voir → verrais, venir → viendrais.",
    "Emploi 1 — la politesse : « Je voudrais un café » est infiniment plus poli que « Je veux un café ». « Pourriez-vous m'aider ? » « Auriez-vous l'heure ? »",
    "Emploi 2 — l'hypothèse avec SI : si + IMPARFAIT dans la subordonnée, CONDITIONNEL dans la principale. « Si j'avais le temps, je viendrais. » Jamais « si j'aurais » — c'est la faute la plus sanctionnée en français.",
    "Emploi 3 — le conseil : « Tu devrais te reposer. » « Vous feriez mieux de partir tôt. »",
    "Emploi 4 — l'information non vérifiée, courante dans la presse : « L'accident aurait fait trois blessés. »",
    "Futur ou conditionnel ? À la 1re personne du singulier tout se joue sur un -s : « je partirai » (futur, certain) contre « je partirais » (conditionnel, hypothétique). Aux autres personnes, comparez -a / -ait et -ont / -aient.",
  ],
  tables: [
    { verb: "parler", note: "radical du futur + -ais", forms: ["je parlerais", "tu parlerais", "il/elle parlerait", "nous parlerions", "vous parleriez", "ils/elles parleraient"] },
    { verb: "avoir", note: "radical aur-", forms: ["j'aurais", "tu aurais", "il/elle aurait", "nous aurions", "vous auriez", "ils/elles auraient"] },
    { verb: "être", note: "radical ser-", forms: ["je serais", "tu serais", "il/elle serait", "nous serions", "vous seriez", "ils/elles seraient"] },
  ],
  irregulars: [
    { v: "être → serais", f: "je serais · nous serions" },
    { v: "avoir → aurais", f: "j'aurais · ils auraient" },
    { v: "aller → irais", f: "j'irais · vous iriez" },
    { v: "faire → ferais", f: "je ferais · nous ferions" },
    { v: "pouvoir → pourrais", f: "je pourrais (deux r)" },
    { v: "vouloir → voudrais", f: "je voudrais · nous voudrions" },
    { v: "devoir → devrais", f: "tu devrais (le conseil)" },
    { v: "savoir → saurais", f: "je saurais · ils sauraient" },
    { v: "voir → verrais", f: "je verrais (deux r)" },
    { v: "venir → viendrais", f: "je viendrais · ils viendraient" },
    { v: "falloir → faudrait", f: "il faudrait (impersonnel)" },
  ],
  qs: [
    { s: "Je ___ un café, s'il vous plaît.", inf: "vouloir", p: "je", a: "voudrais", opts: ["voudrais", "voudrai", "veux", "voulais"], exp: "La formule de politesse par excellence : « je voudrais » et non « je veux »." },
    { s: "Si j'avais le temps, je ___ vous voir.", inf: "venir", p: "je", a: "viendrais", opts: ["viendrais", "viendrai", "venais", "viens"], exp: "Si + imparfait → conditionnel dans la principale. Radical « viendr- » + -ais." },
    { s: "___-vous m'indiquer la sortie ?", inf: "pouvoir", p: "vous", a: "Pourriez", opts: ["Pourriez", "Pourrez", "Pouviez", "Pouvez"], exp: "Demande polie au conditionnel : « Pourriez-vous… ». Le futur « pourrez » serait bien plus sec." },
    { s: "Tu ___ te reposer un peu, tu as l'air fatigué.", inf: "devoir", p: "tu", a: "devrais", opts: ["devrais", "devras", "devais", "dois"], exp: "Le conditionnel de « devoir » sert à conseiller sans imposer." },
    { s: "Si nous partions maintenant, nous ___ à l'heure.", inf: "arriver", p: "nous", a: "arriverions", opts: ["arriverions", "arriverons", "arrivions", "arriveraient"], exp: "Si + imparfait (« partions ») → conditionnel « arriverions »." },
    { s: "Elle ___ ravie de vous rencontrer.", inf: "être", p: "elle", a: "serait", opts: ["serait", "sera", "était", "soit"], exp: "Radical « ser- » + -ait. Suggestion polie plutôt qu'affirmation." },
    { s: "À votre place, je ___ un avocat.", inf: "consulter", p: "je", a: "consulterais", opts: ["consulterais", "consulterai", "consultais", "consulte"], exp: "Conseil hypothétique → conditionnel, terminaison -ais." },
    { s: "Il ___ vérifier les dates avant de réserver.", inf: "falloir", p: "il", a: "faudrait", opts: ["faudrait", "faudra", "fallait", "faille"], exp: "« Il faudrait » adoucit « il faut » : c'est une suggestion, pas un ordre." },
    { s: "Si tu étudiais davantage, tu ___ de meilleurs résultats.", inf: "avoir", p: "tu", a: "aurais", opts: ["aurais", "auras", "avais", "aies"], exp: "Si + imparfait → conditionnel. Attention : jamais « si tu aurais »." },
    { s: "Ils ___ volontiers, mais ils travaillent ce soir.", inf: "venir", p: "ils", a: "viendraient", opts: ["viendraient", "viendront", "venaient", "viennent"], exp: "Radical « viendr- » + -aient à la 3e personne du pluriel." },
    { s: "Vous ___ mieux de partir tôt à cause du trafic.", inf: "faire", p: "vous", a: "feriez", opts: ["feriez", "ferez", "faisiez", "faites"], exp: "« Vous feriez mieux de » est la tournure figée du conseil." },
    { s: "Selon la police, il y ___ trois blessés.", inf: "avoir", p: "il", a: "aurait", opts: ["aurait", "aura", "avait", "ait"], exp: "Information non confirmée → conditionnel, usage courant dans la presse." },
    { s: "Nous ___ savoir si le dossier est complet.", inf: "aimer", p: "nous", a: "aimerions", opts: ["aimerions", "aimerons", "aimions", "aimeraient"], exp: "« Nous aimerions savoir » : demande polie, terminaison -ions." },
    { s: "Si vous aviez un doute, que ___-vous ?", inf: "faire", p: "vous", a: "feriez", opts: ["feriez", "ferez", "faisiez", "fassiez"], exp: "Si + imparfait dans la subordonnée, conditionnel dans la question." },
    { s: "Je ___ ne pas insister, si j'étais toi.", inf: "préférer", p: "je", a: "préférerais", opts: ["préférerais", "préférerai", "préférais", "préfère"], exp: "Radical du futur « préférer- » + -ais." },
    { s: "Elle ___ en réunion en ce moment, d'après ses collègues.", inf: "être", p: "elle", a: "serait", opts: ["serait", "sera", "était", "soit"], exp: "Information rapportée non vérifiée → conditionnel présent." },
    { s: "Si on lui demandait, il ___ sûrement oui.", inf: "dire", p: "il", a: "dirait", opts: ["dirait", "dira", "disait", "dise"], exp: "Radical du futur « dir- » + -ait." },
    { s: "___-vous l'heure, s'il vous plaît ?", inf: "avoir", p: "vous", a: "Auriez", opts: ["Auriez", "Aurez", "Aviez", "Avez"], exp: "« Auriez-vous » est la version courtoise de « avez-vous »." },
    { s: "Nous ___ ce problème s'il y avait plus de temps.", inf: "résoudre", p: "nous", a: "résoudrions", opts: ["résoudrions", "résoudrons", "résolvions", "résoudraient"], exp: "Radical du futur « résoudr- » + -ions." },
    { s: "Tu ___ où, si tu pouvais choisir ?", inf: "aller", p: "tu", a: "irais", opts: ["irais", "iras", "allais", "ailles"], exp: "Radical irrégulier « ir- » + -ais." },
    { s: "Ils ___ intérêt à se dépêcher.", inf: "avoir", p: "ils", a: "auraient", opts: ["auraient", "auront", "avaient", "aient"], exp: "Radical « aur- » + -aient. À l'oral, « auraient » et « auront » se distinguent nettement." },
    { s: "Je ___ vous poser une question, si vous permettez.", inf: "souhaiter", p: "je", a: "souhaiterais", opts: ["souhaiterais", "souhaiterai", "souhaitais", "souhaite"], exp: "Formule d'ouverture polie au conditionnel." },
    { s: "Ce ___ dommage de rater cette occasion.", inf: "être", p: "il", a: "serait", opts: ["serait", "sera", "était", "soit"], exp: "« Ce serait dommage » : jugement hypothétique." },
    { s: "Si elle savait la vérité, elle ne ___ pas ainsi.", inf: "réagir", p: "elle", a: "réagirait", opts: ["réagirait", "réagira", "réagissait", "réagisse"], exp: "Si + imparfait → conditionnel. Pas d'infixe -iss- au conditionnel." },
    { s: "Vous ___ me rappeler demain matin ?", inf: "pouvoir", p: "vous", a: "pourriez", opts: ["pourriez", "pourrez", "pouviez", "puissiez"], exp: "Demande polie : « vous pourriez », avec deux r et la terminaison -iez." },
    { inf: "être", p: "nous", a: "serions", opts: ["serions", "serons", "étions", "soyons"], exp: "Radical « ser- » + -ions." },
    { inf: "savoir", p: "je", a: "saurais", opts: ["saurais", "saurai", "savais", "sache"], exp: "Radical « saur- » + -ais." },
    { inf: "voir", p: "ils", a: "verraient", opts: ["verraient", "verront", "voyaient", "voient"], exp: "Radical « verr- » (deux r) + -aient." },
    { inf: "faire", p: "tu", a: "ferais", opts: ["ferais", "feras", "faisais", "fasses"], exp: "Radical « fer- » + -ais." },
    { inf: "devoir", p: "nous", a: "devrions", opts: ["devrions", "devrons", "devions", "devraient"], exp: "Radical « devr- » + -ions. « Devions » (sans r) serait l'imparfait." },
  ],
};
