// Le futur simple de l'indicatif.
export const FUTUR_SIMPLE = {
  id: "futur-simple",
  t: "Le futur simple",
  d: "« Je partirai » : le futur de l'écrit, des projets et des promesses.",
  level: "B1",
  use: "Un projet, une prévision, une promesse — surtout à l'écrit.",
  lesson: [
    "Formation : INFINITIF + -ai, -as, -a, -ons, -ez, -ont. « Parler → je parlerai », « finir → je finirai ».",
    "Les verbes en -re perdent leur -e final : « prendre → je prendrai », « écrire → j'écrirai », « boire → je boirai ».",
    "Le -r- avant la terminaison est la signature du futur : on l'entend et on doit l'écrire. Il est présent à TOUTES les personnes, sans exception.",
    "Radicaux irréguliers (à mémoriser) : être → ser-, avoir → aur-, aller → ir-, faire → fer-, venir → viendr-, pouvoir → pourr-, vouloir → voudr-, devoir → devr-, savoir → saur-, voir → verr-, envoyer → enverr-, falloir → faudr-, tenir → tiendr-, courir → courr-, mourir → mourr-, recevoir → recevr-.",
    "Les terminaisons du futur sont exactement le verbe AVOIR au présent (ai, as, a, ons, ez, ont) — un moyen sûr de ne pas les oublier.",
    "Futur ou conditionnel ? Le futur fait -rai / -ras / -ra ; le conditionnel fait -rais / -rait / -raient. À la 1re personne, « je parlerai » (futur) et « je parlerais » (conditionnel) ne diffèrent que d'un -s.",
    "Après « quand », « dès que », « lorsque », le français met le FUTUR, là où l'anglais met un présent : « Quand j'aurai le temps, je vous appellerai. »",
  ],
  tables: [
    { verb: "parler", note: "infinitif + terminaisons", forms: ["je parlerai", "tu parleras", "il/elle parlera", "nous parlerons", "vous parlerez", "ils/elles parleront"] },
    { verb: "prendre", note: "-re perd son e", forms: ["je prendrai", "tu prendras", "il/elle prendra", "nous prendrons", "vous prendrez", "ils/elles prendront"] },
    { verb: "être", note: "radical irrégulier ser-", forms: ["je serai", "tu seras", "il/elle sera", "nous serons", "vous serez", "ils/elles seront"] },
  ],
  irregulars: [
    { v: "être → ser-", f: "je serai · nous serons" },
    { v: "avoir → aur-", f: "j'aurai · ils auront" },
    { v: "aller → ir-", f: "j'irai · nous irons" },
    { v: "faire → fer-", f: "je ferai · vous ferez" },
    { v: "venir → viendr-", f: "je viendrai · ils viendront" },
    { v: "pouvoir → pourr-", f: "je pourrai (deux r)" },
    { v: "vouloir → voudr-", f: "je voudrai · nous voudrons" },
    { v: "devoir → devr-", f: "je devrai · vous devrez" },
    { v: "savoir → saur-", f: "je saurai · ils sauront" },
    { v: "voir → verr-", f: "je verrai (deux r)" },
    { v: "envoyer → enverr-", f: "j'enverrai · nous enverrons" },
    { v: "falloir → faudr-", f: "il faudra (impersonnel)" },
  ],
  qs: [
    { s: "Demain, je ___ mon dossier au bureau d'immigration.", inf: "déposer", p: "je", a: "déposerai", opts: ["déposerai", "déposerais", "déposera", "déposeré"], exp: "Infinitif « déposer » + -ai. Avec un -s, ce serait le conditionnel." },
    { s: "Quand j'___ le temps, je vous appellerai.", inf: "avoir", p: "je", a: "aurai", opts: ["aurai", "aurais", "avrai", "ai"], exp: "Radical irrégulier « aur- ». Après « quand », le français exige le futur, jamais le présent." },
    { s: "Nous ___ à Montréal en septembre.", inf: "être", p: "nous", a: "serons", opts: ["serons", "serions", "seront", "sommes"], exp: "Radical « ser- » + -ons. « Serions » est le conditionnel, « seront » la 3e personne." },
    { s: "Tu ___ la réponse avant vendredi.", inf: "savoir", p: "tu", a: "sauras", opts: ["sauras", "saurais", "savras", "saches"], exp: "Radical irrégulier « saur- » + -as." },
    { s: "Ils ___ nous voir dès leur arrivée.", inf: "venir", p: "ils", a: "viendront", opts: ["viendront", "viendraient", "viendrons", "viennent"], exp: "Radical « viendr- » + -ont. Le -d- est propre au futur et au conditionnel." },
    { s: "Vous ___ ce document en trois exemplaires.", inf: "envoyer", p: "vous", a: "enverrez", opts: ["enverrez", "envoyerez", "enverriez", "envoierez"], exp: "Radical irrégulier « enverr- », avec deux r : vous enverrez." },
    { s: "Elle ___ ses études l'année prochaine.", inf: "finir", p: "elle", a: "finira", opts: ["finira", "finirait", "finiras", "finissera"], exp: "Infinitif « finir » + -a. Pas d'infixe -iss- au futur." },
    { s: "Je ___ ce que je peux pour vous aider.", inf: "faire", p: "je", a: "ferai", opts: ["ferai", "ferais", "faire ai", "fairai"], exp: "Radical irrégulier « fer- » : je ferai, tu feras, il fera." },
    { s: "Nous ___ le train de 7 h pour être à l'heure.", inf: "prendre", p: "nous", a: "prendrons", opts: ["prendrons", "prendrions", "prenderons", "prendront"], exp: "Verbe en -re : on retire le -e final → prendr- + -ons." },
    { s: "Il ___ patienter encore un peu.", inf: "falloir", p: "il", a: "faudra", opts: ["faudra", "faudrait", "faudras", "fallera"], exp: "Verbe impersonnel, radical « faudr- » : il faudra." },
    { s: "Tu ___ bientôt si tu continues comme ça.", inf: "pouvoir", p: "tu", a: "pourras", opts: ["pourras", "pourrais", "pouras", "peuxras"], exp: "Radical « pourr- », avec deux r qui s'entendent nettement." },
    { s: "Je vous ___ demain matin sans faute.", inf: "rappeler", p: "je", a: "rappellerai", opts: ["rappellerai", "rappelerai", "rappellerais", "rappelerais"], exp: "« Rappeler » double le -l- devant un e muet, et cette forme se conserve à tout le futur : je rappellerai." },
    { s: "Nous ___ à Québec pour les vacances.", inf: "aller", p: "nous", a: "irons", opts: ["irons", "irions", "allerons", "iront"], exp: "Radical irrégulier « ir- » : j'irai, tu iras, nous irons." },
    { s: "Vous ___ un courriel de confirmation.", inf: "recevoir", p: "vous", a: "recevrez", opts: ["recevrez", "recevriez", "recevoirez", "receverez"], exp: "Radical « recevr- » + -ez." },
    { s: "Elle ___ ce qu'elle a promis, j'en suis sûr.", inf: "tenir", p: "elle", a: "tiendra", opts: ["tiendra", "tiendrait", "tiendras", "tienra"], exp: "Radical « tiendr- », comme « venir → viendr- »." },
    { s: "Ils ___ leurs résultats la semaine prochaine.", inf: "connaître", p: "ils", a: "connaîtront", opts: ["connaîtront", "connaîtraient", "connaissront", "connaitrons"], exp: "Le circonflexe du radical se maintient au futur : ils connaîtront." },
    { s: "On ___ bien ce qui se passera.", inf: "voir", p: "on", a: "verra", opts: ["verra", "verrait", "voira", "verras"], exp: "Radical irrégulier « verr- » avec deux r. « On » se conjugue comme « il »." },
    { s: "Je ___ te dire la vérité un jour.", inf: "devoir", p: "je", a: "devrai", opts: ["devrai", "devrais", "doivrai", "deverai"], exp: "Radical « devr- » + -ai." },
    { s: "Vous ___ vos papiers à l'entrée.", inf: "présenter", p: "vous", a: "présenterez", opts: ["présenterez", "présenteriez", "présentez", "présenterrez"], exp: "Infinitif complet + -ez. Un seul r." },
    { s: "Nous ___ ce problème ensemble.", inf: "résoudre", p: "nous", a: "résoudrons", opts: ["résoudrons", "résoudrions", "résolverons", "résoudront"], exp: "Verbe en -dre : on retire le -e → résoudr- + -ons." },
    { s: "Dès que tu ___, préviens-moi.", inf: "arriver", p: "tu", a: "arriveras", opts: ["arriveras", "arriverais", "arrives", "arrivera"], exp: "Après « dès que », le futur est obligatoire en français." },
    { s: "Ils ___ certainement plus de temps que prévu.", inf: "mettre", p: "ils", a: "mettront", opts: ["mettront", "mettraient", "metteront", "mettrons"], exp: "Verbe en -re : mettr- + -ont. Deux t, deux r différents à ne pas confondre." },
    { s: "Elle ___ vingt-cinq ans en juin prochain.", inf: "avoir", p: "elle", a: "aura", opts: ["aura", "aurait", "auras", "avra"], exp: "Radical « aur- » + -a." },
    { s: "Je ___ le premier chapitre ce soir.", inf: "écrire", p: "je", a: "écrirai", opts: ["écrirai", "écrirais", "écrivrai", "écrierai"], exp: "Verbe en -re : écrir- (on retire le -e) + -ai." },
    { s: "Nous ___ vous répondre dans les meilleurs délais.", inf: "essayer", p: "nous", a: "essaierons", alt: ["essayerons"], opts: ["essaierons", "essayerions", "essaierions", "essayeront"], exp: "« Essayer » admet deux futurs : essaierons (le plus courant) et essayerons. Les deux sont corrects." },
    { inf: "être", p: "ils", a: "seront", opts: ["seront", "seraient", "sont", "serons"], exp: "Radical « ser- » + -ont. Sans -ai-, à la différence du conditionnel." },
    { inf: "aller", p: "je", a: "irai", opts: ["irai", "irais", "allerai", "vais"], exp: "Le futur d'« aller » se construit sur « ir- » : j'irai." },
    { inf: "pouvoir", p: "nous", a: "pourrons", opts: ["pourrons", "pourrions", "pouvrons", "pouront"], exp: "Deux r : nous pourrons. « Pourrions » est le conditionnel." },
    { inf: "vouloir", p: "vous", a: "voudrez", opts: ["voudrez", "voudriez", "voulerez", "voudrai"], exp: "Radical « voudr- » + -ez." },
    { inf: "courir", p: "elle", a: "courra", opts: ["courra", "courrait", "courira", "coura"], exp: "« Courir » double le r au futur : elle courra — à distinguer de l'imparfait « elle courait »." },
  ],
};
