// Le futur proche : aller (présent) + infinitif.
export const FUTUR_PROCHE = {
  id: "futur-proche",
  t: "Le futur proche",
  d: "« Je vais partir » : le futur immédiat, celui de l'oral.",
  level: "A2",
  use: "Une action sur le point d'arriver, ou un futur présenté comme certain.",
  lesson: [
    "Formation : le verbe ALLER au présent + l'infinitif du verbe. « Je vais manger. » « Nous allons partir. » L'infinitif ne se conjugue jamais.",
    "Aller au présent : je vais, tu vas, il/elle va, nous allons, vous allez, ils/elles vont.",
    "À la forme négative, ne… pas encadre l'auxiliaire ALLER, pas l'infinitif : « Je ne vais pas partir. » Jamais « je vais ne pas partir ».",
    "Avec un pronom complément, le pronom se place devant l'INFINITIF : « Je vais le faire. » « Nous allons vous appeler. »",
    "Avec un verbe pronominal, le pronom réfléchi s'accorde avec le sujet : « Je vais me lever. » « Ils vont se préparer. »",
    "Futur proche ou futur simple ? Le futur proche est plus courant à l'oral et suggère la proximité ou la certitude ; le futur simple appartient à l'écrit et aux projets plus lointains. Au TCF, les deux sont acceptés dans la plupart des contextes.",
    "Ne confondez pas « je vais à Paris » (aller = se déplacer) et « je vais partir » (aller = auxiliaire du futur proche).",
  ],
  tables: [
    { verb: "partir", note: "aller + infinitif", forms: ["je vais partir", "tu vas partir", "il/elle va partir", "nous allons partir", "vous allez partir", "ils/elles vont partir"] },
    { verb: "se lever", note: "pronominal", forms: ["je vais me lever", "tu vas te lever", "il/elle va se lever", "nous allons nous lever", "vous allez vous lever", "ils/elles vont se lever"] },
    { verb: "partir", note: "forme négative", forms: ["je ne vais pas partir", "tu ne vas pas partir", "il ne va pas partir", "nous n'allons pas partir", "vous n'allez pas partir", "ils ne vont pas partir"] },
  ],
  irregulars: [
    { v: "aller (auxiliaire)", f: "je vais · tu vas · il va · nous allons · vous allez · ils vont" },
    { v: "aller + aller", f: "je vais aller à Montréal (la répétition est correcte)" },
    { v: "négation", f: "ne + vais + pas + infinitif" },
    { v: "pronom COD", f: "je vais LE faire (devant l'infinitif)" },
    { v: "pronominal", f: "nous allons NOUS préparer" },
  ],
  qs: [
    { s: "Attention, il ___ pleuvoir cet après-midi.", inf: "pleuvoir", p: "il", a: "va pleuvoir", opts: ["va pleuvoir", "vas pleuvoir", "va pleuvra", "vais pleuvoir"], exp: "Aller à la 3e personne (va) + infinitif inchangé." },
    { s: "Nous ___ notre dossier la semaine prochaine.", inf: "envoyer", p: "nous", a: "allons envoyer", opts: ["allons envoyer", "allons envoyons", "vont envoyer", "allez envoyer"], exp: "« Nous allons » + infinitif « envoyer ». Le second verbe reste à l'infinitif." },
    { s: "Je ___ mes résultats demain matin.", inf: "recevoir", p: "je", a: "vais recevoir", opts: ["vais recevoir", "vas recevoir", "vais recevrai", "vais reçu"], exp: "1re personne : je vais + infinitif." },
    { s: "Tu ___ à quelle heure ce soir ?", inf: "rentrer", p: "tu", a: "vas rentrer", opts: ["vas rentrer", "va rentrer", "vais rentrer", "vas rentrerai"], exp: "2e personne du singulier : tu vas + infinitif." },
    { s: "Ils ___ leur maison le mois prochain.", inf: "vendre", p: "ils", a: "vont vendre", opts: ["vont vendre", "vont vendent", "va vendre", "allons vendre"], exp: "3e personne du pluriel : ils vont + infinitif." },
    { s: "Vous ___ le formulaire avant de signer ?", inf: "lire", p: "vous", a: "allez lire", opts: ["allez lire", "allez lisez", "vont lire", "allons lire"], exp: "2e personne du pluriel : vous allez + infinitif." },
    { s: "Elle ___ tôt demain pour prendre l'avion.", inf: "se lever", p: "elle", a: "va se lever", opts: ["va se lever", "se va lever", "va me lever", "va lever"], exp: "Le pronom réfléchi accompagne l'infinitif et s'accorde avec le sujet : va SE lever." },
    { s: "Je ne ___ pas ce soir, je suis fatigué.", inf: "sortir", p: "je", a: "vais sortir", opts: ["vais sortir", "vais sorti", "vais pas sortir", "sortirai"], exp: "La négation encadre « vais » : je NE vais PAS sortir. Le gap ne contient que « vais sortir »." },
    { s: "Nous ___ demain à huit heures.", inf: "se retrouver", p: "nous", a: "allons nous retrouver", opts: ["allons nous retrouver", "allons se retrouver", "nous allons retrouver", "allons nous retrouvons"], exp: "Pronominal à la 1re personne du pluriel : allons NOUS retrouver." },
    { s: "Le magasin ___ dans dix minutes.", inf: "fermer", p: "il", a: "va fermer", opts: ["va fermer", "vas fermer", "va fermera", "va fermé"], exp: "Futur immédiat par excellence : va + infinitif." },
    { s: "Mes parents ___ nous rendre visite cet été.", inf: "venir", p: "ils", a: "vont venir", opts: ["vont venir", "vont viennent", "va venir", "vont venus"], exp: "« Ils vont venir » : la répétition d'« aller » puis « venir » est parfaitement correcte." },
    { s: "Qu'est-ce que tu ___ après le cours ?", inf: "faire", p: "tu", a: "vas faire", opts: ["vas faire", "va faire", "vas fais", "vas ferai"], exp: "Question courante à l'oral : tu vas + infinitif." },
    { s: "Je ___ demain matin sans faute.", inf: "l'appeler", p: "je", a: "vais l'appeler", opts: ["vais l'appeler", "l'vais appeler", "vais appeler le", "vais l'appelle"], exp: "Le pronom COD se place devant l'infinitif : je vais L'appeler." },
    { s: "Vous ___ ce projet à quelle date ?", inf: "commencer", p: "vous", a: "allez commencer", opts: ["allez commencer", "allez commencez", "vont commencer", "allons commencer"], exp: "Vous allez + infinitif, sans conjuguer le second verbe." },
    { s: "Elles ___ à Toronto pour le travail.", inf: "déménager", p: "elles", a: "vont déménager", opts: ["vont déménager", "va déménager", "vont déménagent", "allez déménager"], exp: "Sujet féminin pluriel : « vont » comme au masculin." },
    { s: "On ___ un peu avant de reprendre.", inf: "se reposer", p: "on", a: "va se reposer", opts: ["va se reposer", "vont se reposer", "va nous reposer", "va reposer"], exp: "« On » se conjugue comme « il » : on va SE reposer." },
    { s: "Je ___ à ta question dans un instant.", inf: "répondre", p: "je", a: "vais répondre", opts: ["vais répondre", "vais réponds", "vais répondrai", "vas répondre"], exp: "Je vais + infinitif « répondre »." },
    { s: "Nous ___ le train de 14 h 30.", inf: "prendre", p: "nous", a: "allons prendre", opts: ["allons prendre", "allons prenons", "allons pris", "vont prendre"], exp: "L'infinitif « prendre » reste inchangé après l'auxiliaire." },
    { s: "Il ___ la vérité tôt ou tard.", inf: "savoir", p: "il", a: "va savoir", opts: ["va savoir", "va saura", "va sait", "vas savoir"], exp: "Va + infinitif, même pour un verbe irrégulier comme « savoir »." },
    { s: "Tu ___ ton passeport avant de partir ?", inf: "vérifier", p: "tu", a: "vas vérifier", opts: ["vas vérifier", "va vérifier", "vas vérifies", "vas vérifierai"], exp: "2e personne du singulier : tu vas + infinitif." },
    { s: "Ce soir, nous ___ au restaurant pour fêter ça.", inf: "aller", p: "nous", a: "allons aller", opts: ["allons aller", "allons", "allons allons", "vont aller"], exp: "« Aller » au futur proche donne « allons aller » : correct, même si l'on préfère souvent « nous allons au restaurant »." },
    { s: "Vous ___ ces documents au bureau d'immigration ?", inf: "apporter", p: "vous", a: "allez apporter", opts: ["allez apporter", "allez apportez", "allons apporter", "vont apporter"], exp: "Vous allez + infinitif." },
    { s: "Je ___ maintenant, il est déjà tard.", inf: "y aller", p: "je", a: "vais y aller", opts: ["vais y aller", "y vais aller", "vais aller y", "vais y vais"], exp: "Le pronom « y » se place devant l'infinitif : je vais Y aller." },
    { s: "Les cours ___ la semaine prochaine.", inf: "reprendre", p: "ils", a: "vont reprendre", opts: ["vont reprendre", "va reprendre", "vont reprennent", "vont repris"], exp: "Sujet pluriel « les cours » → vont + infinitif." },
    { s: "Elle ___ un nouveau travail dès septembre.", inf: "chercher", p: "elle", a: "va chercher", opts: ["va chercher", "vas chercher", "va cherche", "va cherchera"], exp: "Va + infinitif, sans accord ni conjugaison du second verbe." },
    { inf: "manger", p: "nous", a: "allons manger", opts: ["allons manger", "allons mangeons", "vont manger", "allez manger"], exp: "Nous allons + infinitif." },
    { inf: "partir", p: "ils", a: "vont partir", opts: ["vont partir", "va partir", "vont partent", "vont partis"], exp: "Ils vont + infinitif." },
    { inf: "se coucher", p: "tu", a: "vas te coucher", opts: ["vas te coucher", "vas se coucher", "te vas coucher", "vas coucher"], exp: "Le pronom réfléchi suit le sujet : tu vas TE coucher." },
    { inf: "finir", p: "vous", a: "allez finir", opts: ["allez finir", "allez finissez", "allons finir", "vont finir"], exp: "Vous allez + infinitif." },
    { inf: "écrire", p: "je", a: "vais écrire", opts: ["vais écrire", "vas écrire", "vais écris", "vais écrirai"], exp: "Je vais + infinitif." },
  ],
};
