// L'imparfait de l'indicatif.
export const IMPARFAIT = {
  id: "imparfait",
  t: "L'imparfait",
  d: "Le décor du passé : habitudes, descriptions, actions en cours.",
  level: "A2",
  use: "Une habitude passée, une description, une action non achevée.",
  lesson: [
    "Formation : on part du radical de la 1re personne du PLURIEL au présent (nous parlons → parl-) et on ajoute -ais, -ais, -ait, -ions, -iez, -aient.",
    "La règle est presque sans exception : nous finissons → je finissais ; nous prenons → je prenais ; nous buvions ← nous buvons → je buvais.",
    "Seul « être » est irrégulier : j'étais, tu étais, il était, nous étions, vous étiez, ils étaient.",
    "Emplois : l'habitude (« Chaque été, nous allions à la mer »), la description (« Il faisait froid, la rue était vide »), l'action en cours interrompue par un passé composé (« Je dormais quand le téléphone a sonné »).",
    "Imparfait ou passé composé ? L'imparfait plante le décor et dure ; le passé composé fait avancer l'histoire et se termine. C'est le contraste le plus testé au TCF.",
    "Verbes en -ger et -cer : le -e / la cédille ne restent que devant a et o. « Nous mangions » (sans e), mais « je mangeais » ; « nous commencions », mais « je commençais ».",
    "Attention aux verbes dont le radical finit par -i : nous étudions → nous étudiions, vous riiez, nous oubliions. Le double -ii- est correct.",
  ],
  tables: [
    { verb: "parler", note: "radical : nous parl-ons", forms: ["je parlais", "tu parlais", "il/elle parlait", "nous parlions", "vous parliez", "ils/elles parlaient"] },
    { verb: "finir", note: "radical : nous finiss-ons", forms: ["je finissais", "tu finissais", "il/elle finissait", "nous finissions", "vous finissiez", "ils/elles finissaient"] },
    { verb: "être", note: "le seul irrégulier", forms: ["j'étais", "tu étais", "il/elle était", "nous étions", "vous étiez", "ils/elles étaient"] },
  ],
  irregulars: [
    { v: "être", f: "j'étais · nous étions · ils étaient" },
    { v: "avoir", f: "j'avais · nous avions · ils avaient" },
    { v: "faire", f: "je faisais · nous faisions (prononcé « fe- »)" },
    { v: "manger", f: "je mangeais · nous mangions (sans e)" },
    { v: "commencer", f: "je commençais · nous commencions (sans cédille)" },
    { v: "étudier", f: "j'étudiais · nous étudiions (double i)" },
    { v: "boire", f: "je buvais · nous buvions" },
    { v: "prendre", f: "je prenais · nous prenions" },
    { v: "voir", f: "je voyais · nous voyions" },
    { v: "falloir", f: "il fallait (impersonnel)" },
  ],
  qs: [
    { s: "Quand j'___ petit, je jouais au foot tous les samedis.", inf: "être", p: "je", a: "étais", opts: ["étais", "était", "étai", "suis"], exp: "« Être » est le seul verbe vraiment irrégulier à l'imparfait : j'étais, tu étais, il était." },
    { s: "Chaque été, nous ___ chez nos grands-parents.", inf: "aller", p: "nous", a: "allions", opts: ["allions", "allons", "irions", "allaient"], exp: "Radical « all- » (nous allons) + -ions. C'est une habitude passée → imparfait." },
    { s: "Il ___ froid et la rue était déserte.", inf: "faire", p: "il", a: "faisait", opts: ["faisait", "faisais", "fesait", "ferait"], exp: "« Faire » garde le radical « fais- » (nous faisons) : il faisait. On écrit -ai-, même si l'on prononce « fe- »." },
    { s: "Je ___ quand le téléphone a sonné.", inf: "dormir", p: "je", a: "dormais", opts: ["dormais", "dormis", "dormait", "ai dormi"], exp: "Action en cours interrompue par un passé composé → imparfait pour le décor." },
    { s: "Vous ___ souvent au cinéma à cette époque ?", inf: "aller", p: "vous", a: "alliez", opts: ["alliez", "allez", "iriez", "alliiez"], exp: "Radical « all- » + -iez. Un seul i : le radical ne se termine pas par -i." },
    { s: "Nous ___ le français deux fois par semaine.", inf: "étudier", p: "nous", a: "étudiions", opts: ["étudiions", "étudions", "étudiaient", "étudierions"], exp: "Le radical « étudi- » finit déjà par -i, et l'imparfait ajoute -ions → double i : nous étudiions." },
    { s: "Elle ___ toujours ses devoirs avant de sortir.", inf: "finir", p: "elle", a: "finissait", opts: ["finissait", "finait", "finissais", "finirait"], exp: "Radical du pluriel « finiss- » + -ait. L'infixe -iss- se conserve à l'imparfait." },
    { s: "Ils ___ dans un petit appartement au centre-ville.", inf: "habiter", p: "ils", a: "habitaient", opts: ["habitaient", "habitait", "habitaits", "habiteraient"], exp: "3e personne du pluriel : -aient, qui se prononce comme -ait." },
    { s: "Tu ___ beaucoup de café quand tu travaillais la nuit.", inf: "boire", p: "tu", a: "buvais", opts: ["buvais", "boivais", "buvait", "boirais"], exp: "Radical du pluriel : nous buvons → buv- + -ais." },
    { s: "Nous ___ souvent au restaurant le dimanche.", inf: "manger", p: "nous", a: "mangions", opts: ["mangions", "mangeions", "mangeons", "mangerions"], exp: "Le -e de « mangeons » ne sert que devant a et o. Devant -ions, il disparaît : nous mangions." },
    { s: "Je ___ mes cours à huit heures du matin.", inf: "commencer", p: "je", a: "commençais", opts: ["commençais", "commencais", "commencions", "commencerais"], exp: "La cédille est obligatoire devant a : je commençais, tu commençais, ils commençaient." },
    { s: "Il ___ qu'on parte plus tôt que prévu.", inf: "falloir", p: "il", a: "fallait", opts: ["fallait", "faillait", "faudrait", "fallais"], exp: "Verbe impersonnel : il fallait, uniquement à la 3e personne du singulier." },
    { s: "Vous ___ la télévision quand je suis entré.", inf: "regarder", p: "vous", a: "regardiez", opts: ["regardiez", "regardez", "regarderiez", "regardaient"], exp: "Décor en cours (imparfait) interrompu par une action ponctuelle (passé composé)." },
    { s: "Elle ___ trois langues avant même d'entrer à l'université.", inf: "parler", p: "elle", a: "parlait", opts: ["parlait", "parlais", "parlerait", "a parlé"], exp: "État durable dans le passé → imparfait. « Parlerait » serait le conditionnel." },
    { s: "Nous ___ nos voisins tous les matins.", inf: "voir", p: "nous", a: "voyions", opts: ["voyions", "voyons", "voirions", "voyaient"], exp: "Radical « voy- » (nous voyons) + -ions → nous voyions, avec y ET i." },
    { s: "Les enfants ___ dans la cour pendant la récréation.", inf: "courir", p: "ils", a: "couraient", opts: ["couraient", "courraient", "courait", "couriraient"], exp: "Un seul -r- : « courraient » avec deux r serait le conditionnel." },
    { s: "J'___ vingt ans quand je suis arrivé au Canada.", inf: "avoir", p: "je", a: "avais", opts: ["avais", "avait", "aurais", "ai eu"], exp: "L'âge dans le passé s'exprime à l'imparfait : j'avais vingt ans." },
    { s: "Tu ___ que c'était une bonne idée, à l'époque.", inf: "penser", p: "tu", a: "pensais", opts: ["pensais", "pensait", "penserais", "as pensé"], exp: "Opinion durable dans le passé → imparfait, terminaison -ais à la 2e personne." },
    { s: "Le magasin ___ à dix-neuf heures tous les jours.", inf: "fermer", p: "il", a: "fermait", opts: ["fermait", "fermais", "fermerait", "a fermé"], exp: "Habitude répétée → imparfait, et non passé composé." },
    { s: "Nous ___ de partir quand il a commencé à pleuvoir.", inf: "essayer", p: "nous", a: "essayions", opts: ["essayions", "essayons", "essaierions", "essayaient"], exp: "Radical « essay- » + -ions. Le y du radical se conserve devant -ions." },
    { s: "Vous ___ toujours en retard aux réunions !", inf: "arriver", p: "vous", a: "arriviez", opts: ["arriviez", "arrivez", "arriveriez", "arrivaient"], exp: "2e personne du pluriel de l'imparfait : -iez." },
    { s: "Ils ne ___ pas ce qu'il fallait faire.", inf: "savoir", p: "ils", a: "savaient", opts: ["savaient", "savait", "sauraient", "sachaient"], exp: "Radical « sav- » (nous savons) + -aient. « Sachaient » n'existe pas." },
    { s: "Je ___ mon vélo pour aller à l'école.", inf: "prendre", p: "je", a: "prenais", opts: ["prenais", "prendais", "prendrais", "prennais"], exp: "Radical du pluriel : nous prenons → pren- (un seul n) + -ais." },
    { s: "Elle ___ à écrire dès qu'elle avait un moment.", inf: "se mettre", p: "elle", a: "se mettait", opts: ["se mettait", "s'est mise", "se mettrait", "se metait"], exp: "Radical « mett- » (nous mettons), avec deux t : elle se mettait." },
    { s: "Nous ___ que vous viendriez plus tôt.", inf: "croire", p: "nous", a: "croyions", opts: ["croyions", "croyons", "croirions", "croyaient"], exp: "Radical « croy- » (nous croyons) + -ions → croyions." },
    { inf: "être", p: "vous", a: "étiez", opts: ["étiez", "êtiez", "étez", "étaient"], exp: "« Vous étiez » — l'accent aigu remplace le circonflexe du présent (« vous êtes »)." },
    { inf: "avoir", p: "nous", a: "avions", opts: ["avions", "avons", "aurions", "avaient"], exp: "Radical « av- » + -ions. À ne pas confondre avec le conditionnel « aurions »." },
    { inf: "faire", p: "ils", a: "faisaient", opts: ["faisaient", "fesaient", "feraient", "faisait"], exp: "On écrit « fais- », même si la prononciation est « fe- »." },
    { inf: "vouloir", p: "je", a: "voulais", opts: ["voulais", "voudrais", "veulais", "voulait"], exp: "Radical « voul- » (nous voulons). « Voudrais » est le conditionnel." },
    { inf: "venir", p: "tu", a: "venais", opts: ["venais", "viendrais", "viennais", "venait"], exp: "Radical « ven- » (nous venons), sans le doublement du présent « ils viennent »." },
  ],
};
