// L'impératif présent.
export const IMPERATIF = {
  id: "imperatif",
  t: "L'impératif",
  d: "« Écoutez ! » : l'ordre, le conseil, la consigne — trois personnes seulement.",
  level: "A2",
  use: "Donner un ordre, un conseil, une instruction ou une invitation.",
  lesson: [
    "L'impératif n'a que TROIS personnes, et le sujet ne s'écrit jamais : (tu) → Parle ! · (nous) → Parlons ! · (vous) → Parlez !",
    "Les formes sont celles du présent de l'indicatif, sans le pronom sujet. Une seule exception d'orthographe : les verbes en -er perdent le -s de la 2e personne. « Tu parles » → « Parle ! », « tu vas » → « Va ! ».",
    "Ce -s revient devant les pronoms « y » et « en », pour la liaison : « Vas-y ! », « Manges-en ! », « Penses-y ! ».",
    "Les verbes des autres groupes gardent leur -s : « Finis ! », « Prends ! », « Viens ! », « Attends ! ».",
    "Quatre irréguliers : être → Sois, Soyons, Soyez · avoir → Aie, Ayons, Ayez · savoir → Sache, Sachons, Sachez · vouloir → Veuille, Veuillons, Veuillez (« Veuillez agréer… »).",
    "À la forme AFFIRMATIVE, les pronoms se placent APRÈS le verbe, reliés par un trait d'union, et me / te deviennent moi / toi : « Donne-le-moi ! », « Lève-toi ! », « Dépêchons-nous ! ».",
    "À la forme NÉGATIVE, on revient à l'ordre normal, devant le verbe, et moi redevient me : « Ne me le donne pas », « Ne te lève pas », « Ne nous dépêchons pas ».",
    "L'ordre des pronoms à l'affirmative : verbe + COD + COI. « Donne-le-moi » (et non « donne-moi-le »).",
  ],
  tables: [
    // Three persons only, so these tables carry their own row labels.
    { verb: "parler", note: "-er : pas de -s à « tu »", labels: ["(tu)", "(nous)", "(vous)"], forms: ["Parle !", "Parlons !", "Parlez !"] },
    { verb: "finir", note: "autres groupes : -s conservé", labels: ["(tu)", "(nous)", "(vous)"], forms: ["Finis !", "Finissons !", "Finissez !"] },
    { verb: "se lever", note: "pronominal · affirmatif / négatif", labels: ["(tu)", "(nous)", "(vous)"], forms: ["Lève-toi ! / Ne te lève pas !", "Levons-nous ! / Ne nous levons pas !", "Levez-vous ! / Ne vous levez pas !"] },
  ],
  irregulars: [
    { v: "être", f: "Sois · Soyons · Soyez" },
    { v: "avoir", f: "Aie · Ayons · Ayez" },
    { v: "savoir", f: "Sache · Sachons · Sachez" },
    { v: "vouloir", f: "Veuille · Veuillons · Veuillez" },
    { v: "aller", f: "Va (mais Vas-y) · Allons · Allez" },
    { v: "faire", f: "Fais · Faisons · Faites" },
    { v: "venir", f: "Viens · Venons · Venez" },
    { v: "prendre", f: "Prends · Prenons · Prenez" },
  ],
  qs: [
    { s: "___ la porte, s'il te plaît !", inf: "fermer", p: "tu", a: "Ferme", opts: ["Ferme", "Fermes", "Ferme-toi", "Fermez"], exp: "Verbe en -er : à la 2e personne du singulier, l'impératif perd le -s. « Ferme ! »" },
    { s: "___ vos documents avant de partir.", inf: "vérifier", p: "vous", a: "Vérifiez", opts: ["Vérifiez", "Vérifier", "Vérifiez-vous", "Vérifions"], exp: "2e personne du pluriel : forme identique au présent, sans le pronom sujet." },
    { s: "___ patient, le résultat arrive bientôt.", inf: "être", p: "tu", a: "Sois", opts: ["Sois", "Es", "Soit", "Soyez"], exp: "« Être » est irrégulier : Sois, Soyons, Soyez." },
    { s: "___-y tout de suite, il t'attend !", inf: "aller", p: "tu", a: "Vas", opts: ["Vas", "Va", "Vais", "Allez"], exp: "« Va » reprend son -s devant « y », pour la liaison : « Vas-y ! »" },
    { s: "___ vite, le train part dans cinq minutes !", inf: "se dépêcher", p: "nous", a: "Dépêchons-nous", opts: ["Dépêchons-nous", "Nous dépêchons", "Dépêchons", "Se dépêchons"], exp: "À l'affirmative, le pronom réfléchi passe après le verbe avec un trait d'union." },
    { s: "___ vos noms sur la première ligne.", inf: "écrire", p: "vous", a: "Écrivez", opts: ["Écrivez", "Écrivé", "Écrire", "Écrivons"], exp: "Forme du présent (« vous écrivez ») sans le pronom sujet." },
    { s: "Ne ___ pas, tout va bien se passer.", inf: "s'inquiéter", p: "tu", a: "t'inquiète", opts: ["t'inquiète", "t'inquiètes", "inquiète-toi", "vous inquiétez"], exp: "À la négative, le pronom revient devant le verbe et « toi » redevient « te »." },
    { s: "___ le formulaire, puis signez-le.", inf: "remplir", p: "vous", a: "Remplissez", opts: ["Remplissez", "Remplisez", "Remplir", "Remplissons"], exp: "2e groupe : l'infixe -iss- se conserve à l'impératif pluriel." },
    { s: "___-moi la vérité, je t'écoute.", inf: "dire", p: "tu", a: "Dis", opts: ["Dis", "Dit", "Dites", "Dise"], exp: "« Dire » garde son -s à la 2e personne du singulier : Dis !" },
    { s: "___ un peu de patience, s'il vous plaît.", inf: "avoir", p: "vous", a: "Ayez", opts: ["Ayez", "Avez", "Ayiez", "Ayons"], exp: "« Avoir » est irrégulier : Aie, Ayons, Ayez." },
    { s: "___ ensemble, ce sera plus rapide.", inf: "travailler", p: "nous", a: "Travaillons", opts: ["Travaillons", "Travaillez", "Travailler", "Nous travaillons"], exp: "La 1re personne du pluriel sert à proposer : « Travaillons ! »" },
    { s: "___-toi, tu es en retard !", inf: "se lever", p: "tu", a: "Lève", opts: ["Lève", "Lèves", "Léve", "Levez"], exp: "Verbe en -er : pas de -s. Le pronom « toi » se place après le trait d'union." },
    { s: "N'___ pas votre passeport à la maison !", inf: "oublier", p: "vous", a: "oubliez", opts: ["oubliez", "oublier", "oubliez-vous", "oublions"], exp: "À la négative, la forme du verbe ne change pas : « N'oubliez pas ». " },
    { s: "___ que je ne pourrai pas venir demain.", inf: "savoir", p: "vous", a: "Sachez", opts: ["Sachez", "Savez", "Sachiez", "Sachons"], exp: "« Savoir » est irrégulier à l'impératif : Sache, Sachons, Sachez." },
    { s: "___ agréer, Madame, mes salutations distinguées.", inf: "vouloir", p: "vous", a: "Veuillez", opts: ["Veuillez", "Voulez", "Vouliez", "Veuilliez"], exp: "Formule de politesse figée à la fin des lettres officielles : « Veuillez agréer… »" },
    { s: "___-le-moi, je m'en occupe.", inf: "donner", p: "tu", a: "Donne", opts: ["Donne", "Donnes", "Donnez", "Donné"], exp: "Verbe en -er sans -s, puis COD + COI : « Donne-le-moi ». " },
    { s: "___ attention en traversant la rue.", inf: "faire", p: "tu", a: "Fais", opts: ["Fais", "Fait", "Faites", "Fasse"], exp: "« Faire » garde son -s au singulier : Fais, Faisons, Faites." },
    { s: "___ à l'heure, la réunion commence à 9 h précises.", inf: "venir", p: "vous", a: "Venez", opts: ["Venez", "Veniez", "Venir", "Venons"], exp: "Forme du présent sans pronom sujet." },
    { s: "Ne ___ pas si vite, je ne comprends rien !", inf: "parler", p: "tu", a: "parle", opts: ["parle", "parles", "parlez", "parler"], exp: "Même à la négative, le verbe en -er perd son -s : « Ne parle pas »." },
    { s: "___ un instant, je reviens.", inf: "attendre", p: "vous", a: "Attendez", opts: ["Attendez", "Attendiez", "Attendre", "Attendons"], exp: "Verbe en -dre : forme du présent, sans pronom." },
    { s: "___ là-bas dans une heure, d'accord ?", inf: "se retrouver", p: "nous", a: "Retrouvons-nous", opts: ["Retrouvons-nous", "Nous retrouvons", "Retrouvons", "Se retrouvons"], exp: "Pronominal à l'affirmative : le pronom réfléchi passe après le verbe, avec un trait d'union." },
    { s: "___ ce médicament après le repas.", inf: "prendre", p: "vous", a: "Prenez", opts: ["Prenez", "Preniez", "Prendez", "Prenons"], exp: "Radical « pren- » (vous prenez), sans doublement du n." },
    { s: "___ tranquille, je m'occupe de tout.", inf: "rester", p: "tu", a: "Reste", opts: ["Reste", "Restes", "Restez", "Restons"], exp: "Verbe en -er : Reste, sans -s." },
    { s: "___-en si tu as faim, il y en a assez.", inf: "manger", p: "tu", a: "Manges", opts: ["Manges", "Mange", "Mangez", "Mangeons"], exp: "Le -s revient devant « en » pour permettre la liaison : « Manges-en ! »" },
    { s: "___ gentils avec votre petit frère.", inf: "être", p: "vous", a: "Soyez", opts: ["Soyez", "Êtes", "Soyiez", "Soyons"], exp: "Être à la 2e personne du pluriel : Soyez." },
    { inf: "finir", p: "tu", a: "Finis", opts: ["Finis", "Fini", "Finit", "Finissez"], exp: "2e groupe : le -s est conservé au singulier." },
    { inf: "aller", p: "nous", a: "Allons", opts: ["Allons", "Allez", "Allions", "Aller"], exp: "« Allons ! » sert aussi d'encouragement." },
    { inf: "avoir", p: "tu", a: "Aie", opts: ["Aie", "Aies", "As", "Ayes"], exp: "Impératif irrégulier d'avoir, sans -s : Aie confiance." },
    { inf: "s'asseoir", p: "vous", a: "Asseyez-vous", alt: ["Assoyez-vous"], opts: ["Asseyez-vous", "Vous asseyez", "Asseyez", "S'asseyez-vous"], exp: "Pronominal à l'affirmative : le pronom passe après le verbe. « Assoyez-vous » est également correct." },
    { inf: "ouvrir", p: "tu", a: "Ouvre", opts: ["Ouvre", "Ouvres", "Ouvrez", "Ouvri"], exp: "« Ouvrir » se conjugue comme un verbe en -er : pas de -s à l'impératif singulier." },
  ],
};
