// Le passé composé. The gap always covers the WHOLE verb group (auxiliary +
// participle), because choosing the auxiliary is most of what this tense tests.
export const PASSE_COMPOSE = {
  id: "passe-compose",
  t: "Le passé composé",
  d: "L'action passée, terminée, datée : « hier, j'ai fini ».",
  level: "A2",
  use: "Une action passée et achevée, souvent ponctuelle.",
  lesson: [
    "Formation : auxiliaire ÊTRE ou AVOIR au présent + participe passé. « J'ai mangé. » « Je suis parti. »",
    "La grande majorité des verbes prennent AVOIR. ÊTRE est réservé à deux familles : les verbes pronominaux (se lever, se souvenir…) et une quinzaine de verbes de mouvement / changement d'état.",
    "Les verbes avec ÊTRE : aller, venir, arriver, partir, entrer, sortir, monter, descendre, naître, mourir, rester, tomber, passer, retourner, devenir, revenir — et leurs composés.",
    "Accord avec ÊTRE : le participe s'accorde avec le SUJET. « Elle est arrivée. » « Ils sont partis. » « Elles sont venues. »",
    "Accord avec AVOIR : pas d'accord avec le sujet. Le participe s'accorde seulement avec le COD s'il est placé AVANT le verbe : « Les lettres que j'ai écrites. »",
    "Participes irréguliers à connaître : avoir → eu, être → été, faire → fait, prendre → pris, mettre → mis, voir → vu, vouloir → voulu, pouvoir → pu, devoir → dû, savoir → su, venir → venu, écrire → écrit, dire → dit, lire → lu, boire → bu, naître → né, mourir → mort.",
    "Monter, descendre, sortir, passer, retourner prennent AVOIR quand ils ont un complément d'objet direct : « J'ai sorti la poubelle », mais « Je suis sorti à 8 h ».",
  ],
  tables: [
    { verb: "parler", note: "avec AVOIR", forms: ["j'ai parlé", "tu as parlé", "il/elle a parlé", "nous avons parlé", "vous avez parlé", "ils/elles ont parlé"] },
    { verb: "aller", note: "avec ÊTRE · accord", forms: ["je suis allé(e)", "tu es allé(e)", "il est allé / elle est allée", "nous sommes allé(e)s", "vous êtes allé(e)(s)", "ils sont allés / elles sont allées"] },
    { verb: "se lever", note: "pronominal · ÊTRE", forms: ["je me suis levé(e)", "tu t'es levé(e)", "il s'est levé / elle s'est levée", "nous nous sommes levé(e)s", "vous vous êtes levé(e)(s)", "ils se sont levés / elles se sont levées"] },
  ],
  irregulars: [
    { v: "avoir → eu", f: "j'ai eu · nous avons eu" },
    { v: "être → été", f: "j'ai été · nous avons été" },
    { v: "faire → fait", f: "j'ai fait · ils ont fait" },
    { v: "prendre → pris", f: "j'ai pris · nous avons pris" },
    { v: "mettre → mis", f: "j'ai mis · vous avez mis" },
    { v: "voir → vu", f: "j'ai vu · elles ont vu" },
    { v: "pouvoir → pu / devoir → dû", f: "j'ai pu · j'ai dû" },
    { v: "venir → venu", f: "je suis venu(e) · ils sont venus" },
    { v: "naître → né / mourir → mort", f: "elle est née · il est mort" },
    { v: "écrire → écrit / dire → dit", f: "j'ai écrit · tu as dit" },
  ],
  qs: [
    { s: "Hier, nous ___ au marché avant la pluie.", inf: "aller", p: "nous", a: "sommes allés", opts: ["sommes allés", "avons allé", "sommes allé", "avons été"], exp: "« Aller » est un verbe de mouvement → auxiliaire ÊTRE, et le participe s'accorde avec le sujet « nous » → allés." },
    { s: "J'___ mon dossier d'immigration la semaine dernière.", inf: "envoyer", p: "je", a: "ai envoyé", opts: ["ai envoyé", "suis envoyé", "ai envoyer", "ai envoyée"], exp: "« Envoyer » prend AVOIR, et le participe ne s'accorde pas avec le sujet." },
    { s: "Elle ___ à Québec en 1998.", inf: "naître", p: "elle", a: "est née", opts: ["est née", "a né", "est né", "a naît"], exp: "« Naître » se conjugue avec ÊTRE. Accord avec le sujet féminin → née." },
    { s: "Les documents que vous ___ sont incomplets.", inf: "envoyer", p: "vous", a: "avez envoyés", opts: ["avez envoyés", "avez envoyé", "êtes envoyés", "avez envoyée"], exp: "Avec AVOIR, le participe s'accorde avec le COD (« que » = les documents) parce qu'il est placé AVANT le verbe." },
    { s: "Ils ___ tard hier soir, vers minuit.", inf: "rentrer", p: "ils", a: "sont rentrés", opts: ["sont rentrés", "ont rentré", "sont rentré", "ont rentrés"], exp: "« Rentrer » sans COD → ÊTRE, avec accord au masculin pluriel." },
    { s: "Tu ___ la poubelle ce matin ?", inf: "sortir", p: "tu", a: "as sorti", opts: ["as sorti", "es sorti", "as sortie", "es sortie"], exp: "« Sortir » avec un COD (« la poubelle ») prend AVOIR. Sans COD, ce serait « tu es sorti »." },
    { s: "Nous ___ ce film trois fois.", inf: "voir", p: "nous", a: "avons vu", opts: ["avons vu", "sommes vus", "avons voyé", "avons vus"], exp: "Participe irrégulier : voir → vu. AVOIR, sans accord (le COD est placé après)." },
    { s: "Elles ___ à six heures pour prendre l'avion.", inf: "se lever", p: "elles", a: "se sont levées", opts: ["se sont levées", "se ont levées", "se sont levé", "s'ont levées"], exp: "Verbe pronominal → toujours ÊTRE, et ici accord avec le sujet féminin pluriel." },
    { s: "Il ___ beaucoup de difficultés au début.", inf: "avoir", p: "il", a: "a eu", opts: ["a eu", "est eu", "a eut", "a avu"], exp: "Participe irrégulier : avoir → eu (et non « eut », qui est le passé simple)." },
    { s: "Vous ___ la bonne décision.", inf: "prendre", p: "vous", a: "avez pris", opts: ["avez pris", "êtes pris", "avez prendu", "avez prise"], exp: "Participe irrégulier : prendre → pris. Pas d'accord, le COD suit le verbe." },
    { s: "Ma sœur ___ ses études l'année dernière.", inf: "finir", p: "elle", a: "a fini", opts: ["a fini", "est finie", "a finie", "a finit"], exp: "AVOIR + participe « fini », sans accord avec le sujet. « A finit » n'existe pas." },
    { s: "Je ___ malade toute la semaine.", inf: "être", p: "je", a: "ai été", opts: ["ai été", "suis été", "ai étai", "ai eu été"], exp: "Le verbe « être » se conjugue au passé composé avec AVOIR : j'ai été." },
    { s: "Les enfants ___ dans l'escalier.", inf: "tomber", p: "ils", a: "sont tombés", opts: ["sont tombés", "ont tombé", "sont tombé", "ont tombés"], exp: "« Tomber » est un verbe de changement d'état → ÊTRE, avec accord." },
    { s: "Tu ___ ton portefeuille dans le taxi ?", inf: "oublier", p: "tu", a: "as oublié", opts: ["as oublié", "es oublié", "as oublier", "as oubliée"], exp: "AVOIR + participe en -é. « Oublier » n'est pas un verbe de mouvement." },
    { s: "Nous ___ trois ans à Toronto avant de déménager.", inf: "rester", p: "nous", a: "sommes restés", opts: ["sommes restés", "avons resté", "sommes resté", "avons restés"], exp: "« Rester » figure dans la liste des verbes avec ÊTRE, malgré l'absence de mouvement." },
    { s: "Elle ___ qu'elle ne viendrait pas.", inf: "dire", p: "elle", a: "a dit", opts: ["a dit", "est dite", "a disé", "a dite"], exp: "Participe irrégulier : dire → dit. AVOIR, sans accord." },
    { s: "Vous ___ à quelle heure ce matin ?", inf: "partir", p: "vous", a: "êtes partis", opts: ["êtes partis", "avez parti", "êtes parti", "avez partis"], exp: "« Partir » → ÊTRE. Le vouvoiement pluriel entraîne l'accord « partis »." },
    { s: "J'___ écrire la lettre avant vendredi.", inf: "devoir", p: "je", a: "ai dû", opts: ["ai dû", "ai du", "suis dû", "ai devu"], exp: "Participe irrégulier : devoir → dû, avec un accent circonflexe qui le distingue de l'article « du »." },
    { s: "Ils ___ la maison de leurs parents en 2020.", inf: "vendre", p: "ils", a: "ont vendu", opts: ["ont vendu", "sont vendus", "ont vendus", "ont vendue"], exp: "Verbe en -dre → participe en -u. AVOIR, sans accord." },
    { s: "Cette chanson, je l'___ mille fois !", inf: "entendre", p: "je", a: "ai entendue", opts: ["ai entendue", "ai entendu", "suis entendue", "ai entendus"], exp: "Le COD « l' » (= cette chanson, féminin) précède le verbe → accord : entendue." },
    { s: "Nous ___ nous rencontrer au café.", inf: "pouvoir", p: "nous", a: "avons pu", opts: ["avons pu", "sommes pus", "avons pouvu", "avons pus"], exp: "Participe irrégulier : pouvoir → pu." },
    { s: "Le colis ___ hier après-midi.", inf: "arriver", p: "il", a: "est arrivé", opts: ["est arrivé", "a arrivé", "est arrivée", "a arrivée"], exp: "« Arriver » → ÊTRE. Sujet masculin singulier → arrivé." },
    { s: "Vous ___ vos clés ? Regardez dans votre sac.", inf: "perdre", p: "vous", a: "avez perdu", opts: ["avez perdu", "êtes perdus", "avez perdus", "avez perdues"], exp: "AVOIR + « perdu ». Le COD « vos clés » suit le verbe → pas d'accord." },
    { s: "Elle ___ un café en attendant le train.", inf: "boire", p: "elle", a: "a bu", opts: ["a bu", "est bue", "a bou", "a buvé"], exp: "Participe irrégulier : boire → bu." },
    { s: "Mes parents ___ au Canada il y a vingt ans.", inf: "venir", p: "ils", a: "sont venus", opts: ["sont venus", "ont venu", "sont venu", "ont venus"], exp: "« Venir » → ÊTRE, participe « venu », accordé au masculin pluriel." },
    { inf: "faire", p: "nous", a: "avons fait", opts: ["avons fait", "sommes faits", "avons faisé", "avons faits"], exp: "Participe irrégulier : faire → fait, invariable ici (COD après le verbe)." },
    { inf: "mettre", p: "tu", a: "as mis", opts: ["as mis", "es mis", "as mit", "as mettu"], exp: "Participe irrégulier : mettre → mis, avec un -s même au masculin singulier." },
    { inf: "descendre", p: "elle", a: "est descendue", opts: ["est descendue", "a descendu", "est descendu", "a descendue"], exp: "Sans COD, « descendre » prend ÊTRE, avec accord au féminin : descendue." },
    { inf: "se souvenir", p: "je", a: "me suis souvenu", alt: ["me suis souvenue"], opts: ["me suis souvenu", "m'ai souvenu", "me suis souvenus", "ai souvenu"], exp: "Pronominal → ÊTRE, jamais avoir. Le féminin « me suis souvenue » est également accepté." },
    { inf: "lire", p: "ils", a: "ont lu", opts: ["ont lu", "sont lus", "ont lus", "ont lit"], exp: "Participe irrégulier : lire → lu." },
  ],
};
