// Le présent de l'indicatif. Shape documented once in @/constants/conjugation.
export const PRESENT = {
  id: "present",
  t: "Le présent de l'indicatif",
  d: "Le temps de base : ce qui est vrai maintenant, ce qui se répète, ce qui dure.",
  level: "A1",
  use: "Une action en cours, une habitude, une vérité générale.",
  lesson: [
    "Le présent situe l'action au moment où l'on parle : « Je travaille en ce moment. » Il sert aussi aux habitudes (« Je travaille tous les jours ») et aux vérités générales (« L'eau bout à 100 °C »).",
    "1er groupe (-er) : on retire -er et on ajoute -e, -es, -e, -ons, -ez, -ent. C'est le groupe le plus nombreux et le plus régulier.",
    "2e groupe (-ir type finir) : -is, -is, -it, -issons, -issez, -issent. L'infixe -iss- au pluriel est la signature du groupe.",
    "3e groupe : irréguliers. Beaucoup suivent -s, -s, -t, -ons, -ez, -ent (je pars, tu pars, il part), mais les plus fréquents (être, avoir, aller, faire) s'apprennent par cœur.",
    "Avec « depuis », le français emploie le PRÉSENT là où l'anglais met un passé : « J'habite ici depuis cinq ans. » C'est une faute classique au TCF.",
    "« On » se conjugue toujours comme « il / elle », même quand il signifie « nous » : « On part demain. »",
  ],
  tables: [
    { verb: "parler", note: "1er groupe · -er", forms: ["je parle", "tu parles", "il/elle parle", "nous parlons", "vous parlez", "ils/elles parlent"] },
    { verb: "finir", note: "2e groupe · -ir", forms: ["je finis", "tu finis", "il/elle finit", "nous finissons", "vous finissez", "ils/elles finissent"] },
    { verb: "prendre", note: "3e groupe · irrégulier", forms: ["je prends", "tu prends", "il/elle prend", "nous prenons", "vous prenez", "ils/elles prennent"] },
  ],
  irregulars: [
    { v: "être", f: "je suis · tu es · il est · nous sommes · vous êtes · ils sont" },
    { v: "avoir", f: "j'ai · tu as · il a · nous avons · vous avez · ils ont" },
    { v: "aller", f: "je vais · tu vas · il va · nous allons · vous allez · ils vont" },
    { v: "faire", f: "je fais · tu fais · il fait · nous faisons · vous faites · ils font" },
    { v: "pouvoir", f: "je peux · tu peux · il peut · nous pouvons · vous pouvez · ils peuvent" },
    { v: "vouloir", f: "je veux · tu veux · il veut · nous voulons · vous voulez · ils veulent" },
    { v: "devoir", f: "je dois · tu dois · il doit · nous devons · vous devez · ils doivent" },
    { v: "savoir", f: "je sais · tu sais · il sait · nous savons · vous savez · ils savent" },
    { v: "venir", f: "je viens · tu viens · il vient · nous venons · vous venez · ils viennent" },
    { v: "dire", f: "je dis · tu dis · il dit · nous disons · vous dites · ils disent" },
  ],
  qs: [
    { s: "Chaque matin, je ___ le métro pour aller au travail.", inf: "prendre", p: "je", a: "prends", opts: ["prends", "prend", "prens", "prennes"], exp: "« Prendre » à la 1re personne : je prends. Le -d appartient au radical, le -s est la terminaison." },
    { s: "Nous ___ le français depuis trois ans.", inf: "étudier", p: "nous", a: "étudions", opts: ["étudions", "étudiions", "étudiez", "étudient"], exp: "Verbe en -er : radical « étudi- » + -ons. « Étudiions » est l'imparfait." },
    { s: "Vous ___ souvent au Canada ?", inf: "voyager", p: "vous", a: "voyagez", opts: ["voyagez", "voyagiez", "voyagons", "voyages"], exp: "2e personne du pluriel du 1er groupe : -ez." },
    { s: "Elle ___ toujours à l'heure au bureau.", inf: "arriver", p: "elle", a: "arrive", opts: ["arrive", "arrives", "arrivent", "arrivé"], exp: "3e personne du singulier du 1er groupe : -e, sans -s." },
    { s: "Ils ___ leurs devoirs avant le dîner.", inf: "finir", p: "ils", a: "finissent", opts: ["finissent", "finient", "finent", "finissant"], exp: "2e groupe : l'infixe -iss- apparaît à toutes les personnes du pluriel." },
    { s: "Tu ___ que c'est une bonne idée ?", inf: "croire", p: "tu", a: "crois", opts: ["crois", "croit", "croies", "croix"], exp: "« Croire » suit -s, -s, -t : tu crois." },
    { s: "J'___ une lettre à mon frère chaque mois.", inf: "écrire", p: "je", a: "écris", opts: ["écris", "écrit", "écrive", "écrits"], exp: "« Écrire » : j'écris, tu écris, il écrit. Le -t est réservé à la 3e personne." },
    { s: "Nous ___ en ville tous les samedis.", inf: "aller", p: "nous", a: "allons", opts: ["allons", "vons", "allez", "irons"], exp: "« Aller » est irrégulier mais régulier au pluriel : nous allons, vous allez." },
    { s: "Le train ___ à huit heures précises.", inf: "partir", p: "il", a: "part", opts: ["part", "parte", "pars", "partit"], exp: "« Partir » perd le -t- du radical au singulier : je pars, tu pars, il part." },
    { s: "Vous ___ un café ou un thé ?", inf: "vouloir", p: "vous", a: "voulez", opts: ["voulez", "voudrez", "veulez", "voulliez"], exp: "« Vouloir » change de radical au pluriel : nous voulons, vous voulez, ils veulent." },
    { s: "Ils ___ à Montréal depuis 2019.", inf: "vivre", p: "ils", a: "vivent", opts: ["vivent", "vive", "vivrent", "vivons"], exp: "« Vivre » retrouve le -v- au pluriel : nous vivons, ils vivent. Notez « depuis » + présent." },
    { s: "Je ne ___ pas pourquoi il est en retard.", inf: "savoir", p: "je", a: "sais", opts: ["sais", "sait", "sache", "saix"], exp: "« Savoir » : je sais, tu sais, il sait. « Sache » est le subjonctif." },
    { s: "Elle ___ ses clés au moins une fois par semaine.", inf: "perdre", p: "elle", a: "perd", opts: ["perd", "perds", "perde", "pert"], exp: "Verbe en -dre : le -d du radical suffit à la 3e personne, sans -t ajouté." },
    { s: "Nous ___ la fenêtre parce qu'il fait chaud.", inf: "ouvrir", p: "nous", a: "ouvrons", opts: ["ouvrons", "ouvrissons", "ouvrirons", "ouvrez"], exp: "« Ouvrir » se conjugue comme un verbe en -er : j'ouvre, nous ouvrons. Pas d'infixe -iss-." },
    { s: "Tu ___ du sport le week-end ?", inf: "faire", p: "tu", a: "fais", opts: ["fais", "fait", "fasses", "faits"], exp: "« Faire » : je fais, tu fais, il fait, nous faisons, vous faites, ils font." },
    { s: "On ___ souvent au restaurant le vendredi soir.", inf: "manger", p: "on", a: "mange", opts: ["mange", "mangent", "manges", "mangeons"], exp: "« On » se conjugue comme « il », même s'il désigne « nous »." },
    { s: "Les enfants ___ dans le jardin.", inf: "jouer", p: "ils", a: "jouent", opts: ["jouent", "joue", "jouens", "jouont"], exp: "1er groupe au pluriel : -ent, qui ne se prononce pas." },
    { s: "Je ___ mes amis ce soir après le travail.", inf: "voir", p: "je", a: "vois", opts: ["vois", "voit", "voie", "voix"], exp: "« Voir » : je vois, tu vois, il voit, nous voyons, ils voient." },
    { s: "Vous ___ de Tunisie, si je comprends bien ?", inf: "venir", p: "vous", a: "venez", opts: ["venez", "viennez", "venniez", "viendrez"], exp: "« Venir » garde le radical « ven- » à nous et vous : nous venons, vous venez." },
    { s: "Elle ___ trois langues couramment.", inf: "parler", p: "elle", a: "parle", opts: ["parle", "parles", "parlent", "parlé"], exp: "1er groupe, 3e personne du singulier : -e." },
    { s: "Ils ___ toujours la vérité, même quand c'est difficile.", inf: "dire", p: "ils", a: "disent", opts: ["disent", "dient", "disons", "dites"], exp: "« Dire » : nous disons, vous DITES (irrégulier), ils disent." },
    { s: "Tu ___ ton passeport avec toi ?", inf: "avoir", p: "tu", a: "as", opts: ["as", "a", "ai", "aies"], exp: "« Avoir » : j'ai, tu as, il a. Sans accent et sans -s à la 3e personne." },
    { s: "Nous ___ un appartement plus grand depuis janvier.", inf: "chercher", p: "nous", a: "cherchons", opts: ["cherchons", "cherchions", "cherchez", "chercherons"], exp: "1er groupe : radical « cherch- » + -ons. « Cherchions » est l'imparfait." },
    { s: "Le professeur ___ l'exercice au tableau.", inf: "expliquer", p: "il", a: "explique", opts: ["explique", "expliques", "expliquent", "expliqué"], exp: "1er groupe, 3e personne du singulier : -e." },
    { s: "Est-ce que vous ___ m'aider, s'il vous plaît ?", inf: "pouvoir", p: "vous", a: "pouvez", opts: ["pouvez", "puvez", "pouviez", "pourrez"], exp: "« Pouvoir » : je peux, tu peux, il peut, nous pouvons, vous pouvez, ils peuvent." },
    { inf: "être", p: "vous", a: "êtes", opts: ["êtes", "estes", "êtez", "sommes"], exp: "« Vous êtes » — avec l'accent circonflexe, l'une des formes les plus mal orthographiées." },
    { inf: "avoir", p: "ils", a: "ont", opts: ["ont", "sont", "ils ont", "ans"], exp: "« Ils ont » (avoir), à ne pas confondre avec « ils sont » (être)." },
    { inf: "aller", p: "je", a: "vais", opts: ["vais", "vas", "va", "aille"], exp: "« Aller » emprunte son présent à un autre radical : je vais, tu vas, il va, ils vont." },
    { inf: "devoir", p: "tu", a: "dois", opts: ["dois", "doit", "doives", "devs"], exp: "« Devoir » : je dois, tu dois, il doit, nous devons, ils doivent." },
    { inf: "connaître", p: "nous", a: "connaissons", opts: ["connaissons", "connaisons", "connaîtrons", "connaissez"], exp: "Verbes en -aître : double -ss- au pluriel, et l'accent circonflexe disparaît (il connaît, mais nous connaissons)." },
  ],
};
