// Le subjonctif présent.
export const SUBJONCTIF_PRESENT = {
  id: "subjonctif-present",
  t: "Le subjonctif présent",
  d: "« Il faut que je parte » : le mode du souhait, du doute et de l'obligation.",
  level: "B2",
  use: "Après une expression de volonté, d'émotion, de doute ou d'obligation.",
  lesson: [
    "Formation : radical de la 3e personne du PLURIEL au présent (ils parlent → parl-) + -e, -es, -e, -ions, -iez, -ent.",
    "Nous et vous se construisent sur le radical de l'IMPARFAIT : que nous parlions, que vous parliez. C'est pourquoi ces deux formes ressemblent à l'imparfait.",
    "Le subjonctif est presque toujours introduit par QUE. On le rencontre donc rarement seul : « Il faut que… », « Je veux que… », « Bien que… ».",
    "Déclencheurs — obligation : il faut que, il est nécessaire que. Volonté : vouloir que, souhaiter que, exiger que. Émotion : être content / triste / surpris que, avoir peur que. Doute : douter que, ne pas penser que, ne pas croire que.",
    "Conjonctions qui l'imposent : bien que, quoique, pour que, afin que, avant que, jusqu'à ce que, à condition que, à moins que, sans que, pourvu que.",
    "Pièges : « après que » demande l'INDICATIF (« après qu'il est parti »), et « espérer que » aussi (« j'espère qu'il viendra »). « Bien que » et « avant que », en revanche, exigent le subjonctif.",
    "Irréguliers à mémoriser : être → que je sois, avoir → que j'aie, aller → que j'aille, faire → que je fasse, pouvoir → que je puisse, savoir → que je sache, vouloir → que je veuille, falloir → qu'il faille, valoir → qu'il vaille.",
    "Si les deux verbes ont le MÊME sujet, on emploie l'infinitif, pas le subjonctif : « Je veux partir » (et non « je veux que je parte »).",
  ],
  tables: [
    { verb: "parler", note: "radical : ils parl-ent", forms: ["que je parle", "que tu parles", "qu'il/elle parle", "que nous parlions", "que vous parliez", "qu'ils/elles parlent"] },
    { verb: "être", note: "irrégulier", forms: ["que je sois", "que tu sois", "qu'il/elle soit", "que nous soyons", "que vous soyez", "qu'ils/elles soient"] },
    { verb: "avoir", note: "irrégulier", forms: ["que j'aie", "que tu aies", "qu'il/elle ait", "que nous ayons", "que vous ayez", "qu'ils/elles aient"] },
  ],
  irregulars: [
    { v: "être", f: "que je sois · que nous soyons · qu'ils soient" },
    { v: "avoir", f: "que j'aie · que nous ayons · qu'ils aient" },
    { v: "aller", f: "que j'aille · que nous allions · qu'ils aillent" },
    { v: "faire", f: "que je fasse · que nous fassions" },
    { v: "pouvoir", f: "que je puisse · que nous puissions" },
    { v: "savoir", f: "que je sache · que nous sachions" },
    { v: "vouloir", f: "que je veuille · que nous voulions" },
    { v: "venir", f: "que je vienne · que nous venions" },
    { v: "prendre", f: "que je prenne · que nous prenions" },
    { v: "falloir", f: "qu'il faille (impersonnel)" },
  ],
  qs: [
    { s: "Il faut que tu ___ à l'heure demain.", inf: "être", p: "tu", a: "sois", opts: ["sois", "es", "soit", "seras"], exp: "« Il faut que » impose le subjonctif. Être : que je sois, que tu sois, qu'il soit." },
    { s: "Je veux que vous ___ ce dossier avant vendredi.", inf: "finir", p: "vous", a: "finissiez", opts: ["finissiez", "finissez", "finiriez", "finirez"], exp: "Radical « finiss- » + -iez. « Vouloir que » déclenche le subjonctif." },
    { s: "Bien qu'il ___ fatigué, il continue à travailler.", inf: "être", p: "il", a: "soit", opts: ["soit", "est", "sera", "était"], exp: "« Bien que » exige toujours le subjonctif, même quand le fait est certain." },
    { s: "Il faudrait que nous ___ plus tôt.", inf: "partir", p: "nous", a: "partions", opts: ["partions", "partons", "partirions", "partirons"], exp: "À nous et vous, le subjonctif se construit sur le radical de l'imparfait : que nous partions." },
    { s: "Je doute qu'elle ___ venir ce soir.", inf: "pouvoir", p: "elle", a: "puisse", opts: ["puisse", "peut", "pourra", "pouvait"], exp: "« Douter que » → subjonctif. Pouvoir est irrégulier : que je puisse." },
    { s: "Il est important que vous ___ vos documents.", inf: "apporter", p: "vous", a: "apportiez", opts: ["apportiez", "apportez", "apporterez", "apporteriez"], exp: "Expression d'obligation impersonnelle + que → subjonctif, forme en -iez." },
    { s: "Je suis content que tu ___ réussi ton examen.", inf: "avoir", p: "tu", a: "aies", opts: ["aies", "as", "aurais", "auras"], exp: "Émotion + que → subjonctif. Avoir : que j'aie, que tu aies, qu'il ait." },
    { s: "Pour qu'il ___ comprendre, expliquez-lui lentement.", inf: "pouvoir", p: "il", a: "puisse", opts: ["puisse", "peut", "pourrait", "pourra"], exp: "« Pour que » (le but) impose le subjonctif." },
    { s: "Il faut que j'___ à la banque cet après-midi.", inf: "aller", p: "je", a: "aille", opts: ["aille", "vais", "irai", "allais"], exp: "Aller est fortement irrégulier au subjonctif : que j'aille, que nous allions, qu'ils aillent." },
    { s: "Nous attendrons jusqu'à ce qu'ils ___.", inf: "arriver", p: "ils", a: "arrivent", opts: ["arrivent", "arriveront", "arrivaient", "arriveraient"], exp: "« Jusqu'à ce que » → subjonctif. La forme se confond ici avec l'indicatif présent." },
    { s: "Je ne pense pas qu'elle ___ la vérité.", inf: "savoir", p: "elle", a: "sache", opts: ["sache", "sait", "saura", "saurait"], exp: "« Ne pas penser que » exprime le doute → subjonctif. Savoir : que je sache." },
    { s: "Il vaut mieux que vous ___ un spécialiste.", inf: "consulter", p: "vous", a: "consultiez", opts: ["consultiez", "consultez", "consulterez", "consulteriez"], exp: "« Il vaut mieux que » → subjonctif, terminaison -iez." },
    { s: "Avant que tu ___, laisse-moi te dire une chose.", inf: "partir", p: "tu", a: "partes", opts: ["partes", "pars", "partiras", "partirais"], exp: "« Avant que » impose le subjonctif ; « après que », lui, demande l'indicatif." },
    { s: "Ses parents souhaitent qu'il ___ ses études au Canada.", inf: "faire", p: "il", a: "fasse", opts: ["fasse", "fait", "fera", "ferait"], exp: "« Souhaiter que » → subjonctif. Faire : que je fasse, que nous fassions." },
    { s: "Il est possible que nous ___ en retard.", inf: "être", p: "nous", a: "soyons", opts: ["soyons", "sommes", "serons", "serions"], exp: "Être au subjonctif, 1re personne du pluriel : que nous soyons." },
    { s: "Je regrette que vous ne ___ pas rester plus longtemps.", inf: "pouvoir", p: "vous", a: "puissiez", opts: ["puissiez", "pouvez", "pourrez", "pourriez"], exp: "Émotion (« regretter que ») → subjonctif : que vous puissiez." },
    { s: "À condition qu'elle ___ d'accord, on signera lundi.", inf: "être", p: "elle", a: "soit", opts: ["soit", "est", "sera", "serait"], exp: "« À condition que » → subjonctif." },
    { s: "Il faut que tu ___ ce médicament trois fois par jour.", inf: "prendre", p: "tu", a: "prennes", opts: ["prennes", "prends", "prendras", "prendrais"], exp: "Radical « prenn- » (ils prennent) + -es." },
    { s: "Nous aimerions que vous ___ à la réunion.", inf: "venir", p: "vous", a: "veniez", opts: ["veniez", "venez", "viendrez", "viendriez"], exp: "À vous, le subjonctif reprend le radical de l'imparfait : que vous veniez." },
    { s: "Quoi qu'il ___, je resterai à vos côtés.", inf: "arriver", p: "il", a: "arrive", opts: ["arrive", "arrivera", "arriverait", "arrivait"], exp: "« Quoi que » → subjonctif. La forme est identique à l'indicatif présent." },
    { s: "Il est dommage que tu ___ si peu de temps.", inf: "avoir", p: "tu", a: "aies", opts: ["aies", "as", "auras", "aurais"], exp: "Jugement + que → subjonctif : que tu aies, sans -s de l'indicatif." },
    { s: "J'ai peur qu'il ne ___ pas assez d'argent.", inf: "rester", p: "il", a: "reste", opts: ["reste", "restera", "restait", "resterait"], exp: "« Avoir peur que » → subjonctif. Le « ne » est explétif, il ne nie rien." },
    { s: "Nous partirons sans qu'ils ___ notre départ.", inf: "remarquer", p: "ils", a: "remarquent", opts: ["remarquent", "remarqueront", "remarquaient", "remarqueraient"], exp: "« Sans que » → subjonctif. Radical « remarqu- » (ils remarquent) + -ent." },
    { s: "Il faut que ce ___ clair pour tout le monde.", inf: "être", p: "il", a: "soit", opts: ["soit", "est", "sera", "serait"], exp: "Être à la 3e personne du singulier : qu'il soit." },
    { s: "Pourvu qu'il ___ beau dimanche !", inf: "faire", p: "il", a: "fasse", opts: ["fasse", "fait", "fera", "ferait"], exp: "« Pourvu que » exprime le souhait → subjonctif : qu'il fasse beau." },
    { inf: "être", p: "ils", a: "soient", opts: ["soient", "sont", "seront", "seraient"], exp: "Qu'ils soient — à ne pas confondre avec l'indicatif « ils sont »." },
    { inf: "avoir", p: "nous", a: "ayons", opts: ["ayons", "avons", "aurons", "aurions"], exp: "Que nous ayons, forme irrégulière sans -i-." },
    { inf: "vouloir", p: "il", a: "veuille", opts: ["veuille", "veut", "voudra", "voudrait"], exp: "Qu'il veuille — radical irrégulier « veuill- »." },
    { inf: "savoir", p: "nous", a: "sachions", opts: ["sachions", "savons", "saurons", "savions"], exp: "Que nous sachions : le radical irrégulier « sach- » vaut aussi pour nous et vous." },
    { inf: "aller", p: "ils", a: "aillent", opts: ["aillent", "vont", "iront", "allaient"], exp: "Qu'ils aillent — radical « aill- », comme « que j'aille »." },
  ],
};
