// Études — 200 entries. { fr, def, ex, level } — level is CEFR (A1 → C2).
export const ETUDES = [
  // ── Établissements ───────────────────────────────────────────────────
  { fr: "une école", def: "Établissement où l'on enseigne.", ex: "Les enfants marchent jusqu'à l'école.", level: "A1" },
  { fr: "une université", def: "Établissement d'enseignement supérieur.", ex: "Elle étudie à l'université de Montréal.", level: "A2" },
  { fr: "un collège", def: "Établissement d'enseignement après le secondaire.", ex: "Le collège offre des programmes techniques.", level: "A2" },
  { fr: "un cégep", def: "Collège d'enseignement général et professionnel (Québec).", ex: "Au cégep, il a choisi les sciences.", level: "B1" },
  { fr: "une commission scolaire", def: "Organisme qui gère les écoles d'une région.", ex: "La commission scolaire est devenue un centre de services.", level: "B2" },
  { fr: "un campus", def: "Ensemble des terrains et bâtiments d'une université.", ex: "Le campus compte trois bibliothèques.", level: "B1" },
  { fr: "une garderie éducative", def: "Service de garde qui prépare les tout-petits à l'école.", ex: "La garderie éducative suit un programme officiel.", level: "B2" },
  { fr: "la maternelle", def: "Première année scolaire des jeunes enfants.", ex: "Sa fille entre à la maternelle en septembre.", level: "A2" },
  { fr: "le primaire", def: "Niveau scolaire des premières années.", ex: "Le primaire dure six ans au Québec.", level: "A2" },
  { fr: "le secondaire", def: "Niveau scolaire après le primaire.", ex: "Le secondaire mène au cégep.", level: "A2" },
  { fr: "une école privée", def: "École payante gérée hors du réseau public.", ex: "L'école privée exige un examen d'entrée.", level: "B1" },
  { fr: "une école publique", def: "École gratuite financée par l'État.", ex: "L'école publique du quartier est excellente.", level: "B1" },
  { fr: "un établissement scolaire", def: "Lieu officiel d'enseignement.", ex: "Chaque établissement scolaire a son projet éducatif.", level: "B2" },
  { fr: "une faculté", def: "Grande division d'une université par domaine.", ex: "La faculté de droit accueille mille étudiants.", level: "B2" },
  { fr: "un département", def: "Unité d'enseignement dans une discipline.", ex: "Le département de biologie recrute un professeur.", level: "B2" },
  { fr: "un centre de formation professionnelle", def: "Établissement enseignant des métiers.", ex: "Le centre de formation professionnelle forme des cuisiniers.", level: "B2" },
  { fr: "une école de langues", def: "Établissement qui enseigne les langues.", ex: "L'école de langues offre des cours du soir.", level: "B1" },
  { fr: "un internat", def: "Établissement où les élèves logent sur place.", ex: "Il a étudié en internat pendant deux ans.", level: "B2" },
  { fr: "une résidence étudiante", def: "Logement réservé aux étudiants.", ex: "La résidence étudiante est près du campus.", level: "B1" },
  { fr: "un secrétariat", def: "Bureau administratif d'un établissement.", ex: "Le secrétariat traite les demandes d'attestation.", level: "B1" },

  // ── Personnes ────────────────────────────────────────────────────────
  { fr: "un étudiant", def: "Personne qui suit des études supérieures.", ex: "L'étudiant révise à la bibliothèque.", level: "A1" },
  { fr: "un élève", def: "Personne qui fréquente l'école.", ex: "Chaque élève reçoit un horaire.", level: "A1" },
  { fr: "un professeur", def: "Personne qui enseigne, surtout au supérieur.", ex: "Le professeur donne beaucoup de lectures.", level: "A2" },
  { fr: "un enseignant", def: "Personne dont le métier est d'enseigner.", ex: "Les enseignants sont en formation cette semaine.", level: "B1" },
  { fr: "un chargé de cours", def: "Enseignant engagé pour donner un cours précis.", ex: "Le chargé de cours travaille aussi en entreprise.", level: "C1" },
  { fr: "un directeur d'école", def: "Personne qui dirige une école.", ex: "Le directeur d'école a rencontré les parents.", level: "B1" },
  { fr: "un conseiller pédagogique", def: "Personne qui aide à choisir son parcours d'études.", ex: "Le conseiller pédagogique l'a orientée vers le génie.", level: "B2" },
  { fr: "un tuteur", def: "Personne qui aide un étudiant à réussir.", ex: "Son tuteur l'aide en mathématiques.", level: "B1" },
  { fr: "un camarade de classe", def: "Personne qui étudie dans la même classe.", ex: "Ses camarades de classe l'ont bien accueilli.", level: "B1" },
  { fr: "un doyen", def: "Personne à la tête d'une faculté.", ex: "Le doyen a ouvert la cérémonie.", level: "C1" },
  { fr: "un recteur", def: "Plus haut responsable d'une université.", ex: "Le recteur a annoncé un nouveau pavillon.", level: "C1" },
  { fr: "un directeur de recherche", def: "Professeur qui encadre un projet de recherche.", ex: "Son directeur de recherche relit sa thèse.", level: "C1" },
  { fr: "un assistant", def: "Personne qui aide un professeur.", ex: "L'assistant corrige les travaux pratiques.", level: "B2" },
  { fr: "un stagiaire", def: "Personne en formation pratique.", ex: "La stagiaire observe une classe de sixième.", level: "B1" },
  { fr: "un diplômé", def: "Personne qui a obtenu un diplôme.", ex: "Les diplômés trouvent vite un emploi.", level: "B1" },
  { fr: "un ancien élève", def: "Personne qui a fréquenté l'établissement.", ex: "Les anciens élèves financent des bourses.", level: "B2" },
  { fr: "un surveillant", def: "Personne qui veille sur les élèves.", ex: "Le surveillant est présent à la récréation.", level: "B1" },
  { fr: "un orienteur", def: "Personne qui guide dans les choix de carrière.", ex: "L'orienteur l'a aidé à choisir un programme.", level: "B2" },
  { fr: "un cohorte", def: "Groupe d'étudiants qui commence en même temps.", ex: "Sa cohorte compte quarante étudiants.", level: "C1" },
  { fr: "un pair", def: "Étudiant du même niveau que soi.", ex: "L'entraide entre pairs est encouragée.", level: "B2" },

  // ── Diplômes & programmes ────────────────────────────────────────────
  { fr: "un diplôme", def: "Document attestant la réussite d'études.", ex: "Son diplôme est reconnu au Canada.", level: "A2" },
  { fr: "un baccalauréat", def: "Premier diplôme universitaire (usage canadien).", ex: "Elle termine son baccalauréat en génie.", level: "B1" },
  { fr: "une maîtrise", def: "Diplôme universitaire de deuxième cycle.", ex: "Il fait une maîtrise en informatique.", level: "B1" },
  { fr: "un doctorat", def: "Diplôme universitaire le plus élevé.", ex: "Son doctorat porte sur le climat.", level: "B2" },
  { fr: "un certificat", def: "Diplôme court sur un sujet précis.", ex: "Un certificat en gestion complète son profil.", level: "B1" },
  { fr: "un diplôme d'études collégiales", def: "Diplôme obtenu au cégep (Québec).", ex: "Le diplôme d'études collégiales mène à l'université.", level: "B2" },
  { fr: "un diplôme d'études secondaires", def: "Diplôme marquant la fin du secondaire.", ex: "Le diplôme d'études secondaires est exigé pour ce poste.", level: "B2" },
  { fr: "un programme", def: "Ensemble de cours menant à un diplôme.", ex: "Le programme dure trois ans.", level: "A2" },
  { fr: "une majeure", def: "Discipline principale d'un programme.", ex: "Sa majeure est en sociologie.", level: "B2" },
  { fr: "une mineure", def: "Discipline secondaire d'un programme.", ex: "Il ajoute une mineure en langues.", level: "B2" },
  { fr: "un cycle", def: "Niveau d'études universitaires.", ex: "La maîtrise est un deuxième cycle.", level: "B2" },
  { fr: "un cursus", def: "Parcours d'études suivi par une personne.", ex: "Son cursus mêle art et technologie.", level: "C1" },
  { fr: "une discipline", def: "Domaine du savoir enseigné.", ex: "La chimie est sa discipline préférée.", level: "B1" },
  { fr: "une spécialisation", def: "Concentration des études sur un domaine précis.", ex: "Sa spécialisation est la cybersécurité.", level: "B2" },
  { fr: "une attestation d'études", def: "Document confirmant des études suivies.", ex: "L'attestation d'études a suffi à l'employeur.", level: "B2" },
  { fr: "un préalable", def: "Cours à réussir avant d'en suivre un autre.", ex: "Le calcul est un préalable à ce cours.", level: "B2" },
  { fr: "un crédit", def: "Unité mesurant la charge d'un cours.", ex: "Le programme compte quatre-vingt-dix crédits.", level: "B2" },
  { fr: "un cours obligatoire", def: "Cours que tout étudiant du programme doit suivre.", ex: "La statistique est un cours obligatoire.", level: "B1" },
  { fr: "un cours optionnel", def: "Cours choisi librement par l'étudiant.", ex: "Il a pris un cours optionnel de photographie.", level: "B1" },
  { fr: "une formation continue", def: "Cours suivis en cours de carrière.", ex: "La formation continue met à jour ses compétences.", level: "B2" },

  // ── Admission & inscription ──────────────────────────────────────────
  { fr: "une inscription", def: "Fait de s'enregistrer dans un programme.", ex: "L'inscription se fait en ligne avant août.", level: "A2" },
  { fr: "une admission", def: "Acceptation dans un établissement.", ex: "Elle a reçu son admission en médecine.", level: "B1" },
  { fr: "une demande d'admission", def: "Dossier soumis pour être accepté.", ex: "Sa demande d'admission est complète.", level: "B1" },
  { fr: "un dossier scolaire", def: "Ensemble des résultats et documents d'un élève.", ex: "Son dossier scolaire est impeccable.", level: "B2" },
  { fr: "un relevé de notes", def: "Document officiel listant les cours et les résultats.", ex: "L'université exige un relevé de notes traduit.", level: "B1" },
  { fr: "une lettre de recommandation", def: "Lettre appuyant une candidature.", ex: "Son professeur a écrit une lettre de recommandation.", level: "B2" },
  { fr: "une lettre de motivation", def: "Lettre expliquant pourquoi on postule.", ex: "La lettre de motivation doit être personnelle.", level: "B1" },
  { fr: "la cote R", def: "Note globale servant à comparer les candidats (Québec).", ex: "Sa cote R lui ouvre plusieurs programmes.", level: "C1" },
  { fr: "une moyenne", def: "Résultat moyen d'un ensemble de notes.", ex: "Sa moyenne dépasse 85 %.", level: "B1" },
  { fr: "un examen d'entrée", def: "Test à réussir pour être admis.", ex: "L'examen d'entrée porte sur les maths.", level: "B1" },
  { fr: "un contingentement", def: "Limite du nombre de places dans un programme.", ex: "Le contingentement rend l'admission difficile.", level: "C1" },
  { fr: "une liste d'attente", def: "File de candidats en attente d'une place.", ex: "Il est sur la liste d'attente en droit.", level: "B2" },
  { fr: "une date limite", def: "Dernier jour pour faire une démarche.", ex: "La date limite d'inscription est le 1er mars.", level: "A2" },
  { fr: "un frais d'inscription", def: "Somme à payer pour s'inscrire.", ex: "Le frais d'inscription n'est pas remboursable.", level: "B1" },
  { fr: "un choix de cours", def: "Sélection des cours pour la session.", ex: "Fais ton choix de cours avant la rentrée.", level: "B1" },
  { fr: "un abandon de cours", def: "Fait de quitter un cours en cours de session.", ex: "L'abandon de cours avant la date limite évite un échec.", level: "B2" },
  { fr: "une équivalence de cours", def: "Reconnaissance d'un cours déjà réussi ailleurs.", ex: "Il a obtenu une équivalence de cours pour son diplôme étranger.", level: "C1" },
  { fr: "un transfert", def: "Passage d'un programme ou établissement à un autre.", ex: "Son transfert vers l'université a été accepté.", level: "B2" },
  { fr: "une convocation", def: "Invitation officielle à un examen ou un rendez-vous.", ex: "La convocation à l'examen indique la salle.", level: "B2" },
  { fr: "un test de classement", def: "Examen déterminant le niveau à intégrer.", ex: "Le test de classement l'a placée en niveau intermédiaire.", level: "B2" },

  // ── Vie étudiante & cours ────────────────────────────────────────────
  { fr: "un cours", def: "Enseignement sur un sujet donné.", ex: "Le cours commence à 8 h.", level: "A1" },
  { fr: "une session", def: "Période d'études de quelques mois (usage canadien).", ex: "La session d'automne se termine en décembre.", level: "B1" },
  { fr: "un trimestre", def: "Période d'études de trois mois.", ex: "Le trimestre d'hiver est chargé.", level: "B1" },
  { fr: "un semestre", def: "Période d'études de six mois.", ex: "Il part à l'étranger un semestre.", level: "B1" },
  { fr: "la rentrée", def: "Reprise des cours après les vacances.", ex: "La rentrée a lieu fin août.", level: "A2" },
  { fr: "un horaire de cours", def: "Répartition des cours dans la semaine.", ex: "Son horaire de cours laisse les vendredis libres.", level: "B1" },
  { fr: "un plan de cours", def: "Document décrivant le contenu et les règles d'un cours.", ex: "Le plan de cours précise les dates d'examen.", level: "B2" },
  { fr: "un magistral", def: "Cours donné devant un grand groupe.", ex: "Le cours magistral réunit deux cents étudiants.", level: "C1" },
  { fr: "un travail pratique", def: "Séance d'application des connaissances.", ex: "Le travail pratique se fait en laboratoire.", level: "B2" },
  { fr: "un laboratoire", def: "Salle équipée pour les expériences.", ex: "Le laboratoire de chimie est au sous-sol.", level: "B1" },
  { fr: "un devoir", def: "Travail à faire à la maison.", ex: "Le devoir est à remettre lundi.", level: "A2" },
  { fr: "un travail d'équipe", def: "Travail réalisé à plusieurs.", ex: "Le travail d'équipe compte pour 30 %.", level: "B1" },
  { fr: "un exposé", def: "Présentation orale devant la classe.", ex: "Son exposé porte sur les changements climatiques.", level: "B1" },
  { fr: "une dissertation", def: "Texte argumenté sur un sujet.", ex: "La dissertation doit faire mille mots.", level: "B2" },
  { fr: "un mémoire", def: "Long travail de recherche de fin d'études.", ex: "Elle rédige son mémoire de maîtrise.", level: "B2" },
  { fr: "une thèse", def: "Travail de recherche du doctorat.", ex: "Sa thèse a demandé quatre ans.", level: "B2" },
  { fr: "une lecture", def: "Texte à lire pour un cours.", ex: "Les lectures de la semaine sont en ligne.", level: "B1" },
  { fr: "une prise de notes", def: "Fait de noter l'essentiel d'un cours.", ex: "Une bonne prise de notes aide à réviser.", level: "B2" },
  { fr: "un syllabus", def: "Programme détaillé d'un cours.", ex: "Le syllabus liste tous les chapitres.", level: "C1" },
  { fr: "une date de remise", def: "Jour où un travail doit être rendu.", ex: "La date de remise du devoir est lundi.", level: "B1" },

  // ── Évaluation & résultats ───────────────────────────────────────────
  { fr: "un examen", def: "Épreuve mesurant les connaissances.", ex: "L'examen final dure trois heures.", level: "A2" },
  { fr: "un examen final", def: "Épreuve de fin de session.", ex: "L'examen final compte pour la moitié de la note.", level: "B1" },
  { fr: "un examen de mi-session", def: "Épreuve au milieu de la session.", ex: "L'examen de mi-session est la semaine prochaine.", level: "B1" },
  { fr: "une note", def: "Résultat chiffré d'un travail.", ex: "Sa note a dépassé ses attentes.", level: "A2" },
  { fr: "un bulletin", def: "Document réunissant les notes d'un élève.", ex: "Le bulletin sort à la fin de l'étape.", level: "A2" },
  { fr: "une mention", def: "Distinction accompagnant une excellente note.", ex: "Elle a obtenu son diplôme avec mention.", level: "B2" },
  { fr: "la réussite", def: "Fait d'atteindre le résultat visé.", ex: "La réussite exige de la régularité.", level: "B1" },
  { fr: "un échec", def: "Fait de ne pas réussir.", ex: "Un échec peut se reprendre à l'été.", level: "B1" },
  { fr: "une reprise", def: "Nouvelle tentative après un échec.", ex: "La reprise de l'examen est autorisée une fois.", level: "B2" },
  { fr: "la note de passage", def: "Résultat minimal pour réussir.", ex: "La note de passage est de 60 %.", level: "B2" },
  { fr: "une évaluation", def: "Mesure du travail ou des connaissances.", ex: "L'évaluation se fait en continu.", level: "B1" },
  { fr: "un contrôle continu", def: "Notes réparties tout au long de la session.", ex: "Le contrôle continu réduit le stress final.", level: "B2" },
  { fr: "un barème", def: "Échelle servant à attribuer les notes.", ex: "Le barème est expliqué dans le plan de cours.", level: "B2" },
  { fr: "un corrigé", def: "Solution officielle d'un exercice.", ex: "Le corrigé est distribué après l'examen.", level: "B1" },
  { fr: "le plagiat", def: "Fait de copier le travail d'autrui.", ex: "Le plagiat entraîne un échec automatique.", level: "B2" },
  { fr: "une pondération", def: "Poids de chaque évaluation dans la note finale.", ex: "La pondération favorise l'examen final.", level: "C1" },
  { fr: "un relevé officiel", def: "Document scellé attestant les résultats.", ex: "L'employeur exige un relevé officiel.", level: "B2" },
  { fr: "une révision de note", def: "Demande de réexamen d'un résultat.", ex: "Il a déposé une demande de révision de note.", level: "B2" },
  { fr: "un rattrapage", def: "Cours pour combler un retard.", ex: "Le rattrapage a lieu le samedi.", level: "B2" },
  { fr: "une distinction", def: "Honneur accordé aux meilleurs résultats.", ex: "Elle a reçu une distinction pour son mémoire.", level: "B2" },

  // ── Financement des études ───────────────────────────────────────────
  { fr: "les droits de scolarité", def: "Somme payée pour étudier.", ex: "Les droits de scolarité augmentent chaque année.", level: "B2" },
  { fr: "une bourse", def: "Aide financière offerte à un étudiant.", ex: "Sa bourse couvre une partie du logement.", level: "B1" },
  { fr: "une bourse d'excellence", def: "Bourse récompensant de très bons résultats.", ex: "Il a décroché une bourse d'excellence.", level: "B2" },
  { fr: "un prêt étudiant", def: "Argent emprunté pour financer ses études.", ex: "Elle rembourse son prêt étudiant depuis un an.", level: "B2" },
  { fr: "l'aide financière aux études", def: "Programme public de prêts et bourses.", ex: "L'aide financière aux études soutient les moins fortunés.", level: "C1" },
  { fr: "un emploi étudiant", def: "Travail occupé pendant les études.", ex: "Son emploi étudiant paie ses livres.", level: "B1" },
  { fr: "les frais afférents", def: "Frais qui s'ajoutent aux droits de scolarité.", ex: "Les frais afférents financent les activités.", level: "C1" },
  { fr: "un régime enregistré d'épargne-études", def: "Compte pour épargner en vue des études d'un enfant.", ex: "Ils cotisent à un régime enregistré d'épargne-études.", level: "C1" },
  { fr: "une exonération", def: "Dispense de payer certains frais.", ex: "La bourse s'accompagne d'une exonération de frais.", level: "C1" },
  { fr: "un budget étudiant", def: "Plan des dépenses d'un étudiant.", ex: "Son budget étudiant est très serré.", level: "B1" },

  // ── Recherche, orientation & vie académique ──────────────────────────
  { fr: "la recherche", def: "Travail visant à produire de nouvelles connaissances.", ex: "La recherche universitaire attire des fonds.", level: "B2" },
  { fr: "un article scientifique", def: "Texte publié présentant des résultats de recherche.", ex: "Son article scientifique a été cité souvent.", level: "C1" },
  { fr: "une publication", def: "Texte rendu public dans une revue.", ex: "Sa première publication date de sa maîtrise.", level: "B2" },
  { fr: "un colloque", def: "Réunion de spécialistes sur un thème.", ex: "Le colloque réunit des chercheurs du monde entier.", level: "C1" },
  { fr: "un séminaire", def: "Cours en petit groupe axé sur la discussion.", ex: "Le séminaire porte sur la littérature moderne.", level: "B2" },
  { fr: "une bibliographie", def: "Liste des ouvrages utilisés.", ex: "N'oublie pas la bibliographie à la fin.", level: "B2" },
  { fr: "une citation", def: "Passage repris d'un autre texte.", ex: "Chaque citation doit être référencée.", level: "B1" },
  { fr: "une référence", def: "Indication de la source d'une information.", ex: "Ajoute la référence complète en note.", level: "B1" },
  { fr: "un résumé", def: "Version courte présentant l'essentiel.", ex: "Le résumé tient en dix lignes.", level: "A2" },
  { fr: "une hypothèse", def: "Idée à vérifier par la recherche.", ex: "Son hypothèse s'est confirmée.", level: "B2" },
  { fr: "une méthodologie", def: "Ensemble des méthodes d'une recherche.", ex: "La méthodologie décrit chaque étape.", level: "C1" },
  { fr: "une analyse", def: "Étude détaillée d'un sujet.", ex: "Son analyse des données est rigoureuse.", level: "B2" },
  { fr: "un exposé oral", def: "Présentation parlée d'un travail.", ex: "L'exposé oral compte pour la note.", level: "B1" },
  { fr: "un projet de fin d'études", def: "Travail majeur qui clôt un programme.", ex: "Son projet de fin d'études a été primé.", level: "B2" },
  { fr: "une soutenance", def: "Défense orale d'un mémoire ou d'une thèse.", ex: "Sa soutenance a duré deux heures.", level: "C1" },
  { fr: "un jury", def: "Groupe qui évalue un travail ou une soutenance.", ex: "Le jury a félicité la candidate.", level: "B2" },
  { fr: "un stage pratique", def: "Période de travail intégrée aux études.", ex: "Le stage pratique dure trois mois.", level: "B1" },
  { fr: "un programme d'échange", def: "Dispositif pour étudier à l'étranger.", ex: "Le programme d'échange l'a menée en France.", level: "B2" },
  { fr: "l'orientation", def: "Aide au choix d'un parcours d'études.", ex: "L'orientation se fait dès le secondaire.", level: "B2" },
  { fr: "un débouché", def: "Emploi auquel mène une formation.", ex: "Ce programme offre d'excellents débouchés.", level: "B2" },
  { fr: "la persévérance scolaire", def: "Fait de poursuivre ses études jusqu'au bout.", ex: "L'école valorise la persévérance scolaire.", level: "C1" },
  { fr: "le décrochage scolaire", def: "Abandon des études avant le diplôme.", ex: "Des programmes luttent contre le décrochage scolaire.", level: "C1" },
  { fr: "une aptitude", def: "Capacité naturelle à faire quelque chose.", ex: "Il a des aptitudes pour les langues.", level: "B2" },
  { fr: "une compétence transversale", def: "Aptitude utile dans plusieurs matières.", ex: "L'esprit critique est une compétence transversale.", level: "C1" },
  { fr: "un carnet de correspondance", def: "Cahier reliant l'école et les parents.", ex: "Le carnet de correspondance annonce la réunion de parents.", level: "B2" },

  // ── Matériel, classe & apprentissages de base ────────────────────────
  { fr: "un sac d'école", def: "Sac pour transporter le matériel scolaire.", ex: "Range tes livres dans ton sac d'école.", level: "A1" },
  { fr: "une trousse", def: "Étui pour les crayons et les stylos.", ex: "Sa trousse est pleine de stylos.", level: "A2" },
  { fr: "un manuel scolaire", def: "Livre servant de support à un cours.", ex: "Le manuel scolaire coûte quatre-vingts dollars.", level: "B1" },
  { fr: "un cahier", def: "Carnet pour écrire ses notes et exercices.", ex: "Elle a rempli deux cahiers cette session.", level: "A1" },
  { fr: "un tableau", def: "Surface sur laquelle le professeur écrit.", ex: "Le professeur écrit la date au tableau.", level: "A1" },
  { fr: "un pupitre", def: "Table individuelle de l'élève.", ex: "Chaque pupitre a un petit tiroir.", level: "B1" },
  { fr: "une matière", def: "Discipline enseignée à l'école.", ex: "Les mathématiques sont sa matière préférée.", level: "A2" },
  { fr: "une récréation", def: "Pause entre les cours à l'école.", ex: "Les enfants jouent dehors à la récréation.", level: "A2" },
  { fr: "la cour d'école", def: "Espace extérieur d'une école.", ex: "La cour d'école est surveillée à midi.", level: "A2" },
  { fr: "une sortie éducative", def: "Excursion organisée par l'école.", ex: "La sortie éducative va au musée des sciences.", level: "B1" },
  { fr: "une étape", def: "Période de l'année scolaire (usage québécois).", ex: "La première étape se termine en novembre.", level: "B2" },
  { fr: "une réunion de parents", def: "Rencontre entre enseignants et parents.", ex: "La réunion de parents a lieu ce soir.", level: "B1" },
  { fr: "un redoublement", def: "Fait de refaire une année scolaire.", ex: "Le redoublement est devenu rare.", level: "C1" },
  { fr: "une dictée", def: "Exercice où l'on écrit un texte lu à voix haute.", ex: "La dictée du vendredi corrige l'orthographe.", level: "B1" },
  { fr: "la lecture", def: "Activité qui consiste à lire.", ex: "La lecture est encouragée dès le primaire.", level: "A2" },
  { fr: "l'écriture", def: "Activité qui consiste à écrire.", ex: "L'écriture s'améliore avec la pratique.", level: "A2" },
  { fr: "le calcul", def: "Opérations effectuées sur les nombres.", ex: "Le calcul mental est utile au quotidien.", level: "A2" },
  { fr: "la grammaire", def: "Ensemble des règles d'une langue.", ex: "La grammaire française compte beaucoup d'exceptions.", level: "B1" },
  { fr: "l'orthographe", def: "Manière correcte d'écrire les mots.", ex: "Son orthographe s'est nettement améliorée.", level: "B1" },
  { fr: "le vocabulaire", def: "Ensemble des mots d'une langue.", ex: "Il enrichit son vocabulaire chaque jour.", level: "B1" },
  { fr: "la conjugaison", def: "Ensemble des formes que prend un verbe.", ex: "La conjugaison des verbes irréguliers est difficile.", level: "B1" },
  { fr: "un exercice", def: "Tâche courte pour s'entraîner.", ex: "Fais les exercices de la page trente.", level: "A2" },
  { fr: "une consigne", def: "Instruction à suivre pour un travail.", ex: "Lis bien la consigne avant de répondre.", level: "B1" },
  { fr: "une question à choix multiple", def: "Question offrant plusieurs réponses au choix.", ex: "L'examen comporte des questions à choix multiple.", level: "B2" },
  { fr: "une réponse", def: "Ce qu'on donne pour répondre à une question.", ex: "Sa réponse était juste du premier coup.", level: "A1" },
  { fr: "une erreur", def: "Réponse ou action fausse.", ex: "Il a corrigé son erreur au tableau.", level: "A2" },
  { fr: "une correction", def: "Fait de corriger un travail.", ex: "La correction est rendue la semaine suivante.", level: "B1" },
  { fr: "un examen blanc", def: "Examen d'entraînement dans les conditions réelles.", ex: "L'examen blanc l'a bien préparée.", level: "B2" },
  { fr: "une salle d'examen", def: "Pièce où se déroule un examen.", ex: "Le silence règne dans la salle d'examen.", level: "B1" },
  { fr: "la révision", def: "Fait de revoir la matière avant un examen.", ex: "La révision de dernière minute stresse tout le monde.", level: "B1" },
  { fr: "un groupe d'étude", def: "Petit groupe qui révise ensemble.", ex: "Son groupe d'étude se réunit à la bibliothèque.", level: "B1" },
  { fr: "la concentration", def: "Capacité à rester attentif.", ex: "La concentration baisse après une heure de cours.", level: "B1" },
  { fr: "la motivation", def: "Envie de fournir des efforts.", ex: "La motivation compte autant que le talent.", level: "B1" },
  { fr: "l'assiduité", def: "Fait d'être présent et régulier.", ex: "L'assiduité est notée dans certains cours.", level: "C1" },
  { fr: "une absence", def: "Fait de ne pas être présent.", ex: "Trop d'absences peuvent nuire à la réussite.", level: "B1" },
  { fr: "un retard", def: "Fait d'arriver après l'heure prévue.", ex: "Un retard répété est inscrit au dossier.", level: "A2" },
  { fr: "un congé pédagogique", def: "Journée sans cours pour les élèves (Québec).", ex: "Le congé pédagogique tombe un vendredi.", level: "B2" },
  { fr: "une année scolaire", def: "Période allant d'une rentrée à l'autre.", ex: "L'année scolaire se termine à la fin de juin.", level: "A2" },
  { fr: "le calendrier scolaire", def: "Répartition des jours de classe et de congé.", ex: "Le calendrier scolaire prévoit la semaine de relâche.", level: "B2" },
  { fr: "la semaine de relâche", def: "Semaine de congé au milieu de l'hiver (Québec).", ex: "La semaine de relâche a lieu début mars.", level: "B2" },
  { fr: "un diplôme reconnu", def: "Diplôme accepté par les employeurs ou l'État.", ex: "Cherche un diplôme reconnu au Canada.", level: "B2" },
  { fr: "une équivalence de scolarité", def: "Reconnaissance officielle d'un niveau d'études étranger.", ex: "Il a demandé une équivalence de scolarité.", level: "C1" },
  { fr: "l'apprentissage en ligne", def: "Formation suivie entièrement par Internet.", ex: "L'apprentissage en ligne s'est beaucoup répandu.", level: "B2" },
  { fr: "un travail de session", def: "Long travail à remettre à la fin d'une session.", ex: "Le travail de session vaut 40 % de la note.", level: "B2" },
  { fr: "une charge de cours", def: "Nombre de cours suivis dans une session.", ex: "Sa charge de cours est trop lourde ce trimestre.", level: "C1" },
];
