// Immigration — 200 entries. { fr, def, ex, level } — level is CEFR (A1 → C2).
// Category "Immigration" is stamped on in constants/vocabulary.js.
export const IMMIGRATION = [
  // ── Statuts & documents de base ──────────────────────────────────────
  { fr: "un visa", def: "Autorisation officielle d'entrer ou de séjourner dans un pays.", ex: "Elle a obtenu son visa d'étudiante pour le Canada.", level: "A1" },
  { fr: "un passeport", def: "Document de voyage délivré par un pays à ses citoyens.", ex: "Vérifie que ton passeport est encore valide six mois.", level: "A1" },
  { fr: "une frontière", def: "Limite qui sépare deux pays.", ex: "Ils ont franchi la frontière à Lacolle.", level: "A1" },
  { fr: "un formulaire", def: "Document à remplir avec ses renseignements.", ex: "Chaque formulaire doit être signé et daté.", level: "A2" },
  { fr: "une demande", def: "Démarche officielle pour obtenir un statut ou un service.", ex: "Sa demande de résidence a été acceptée.", level: "A2" },
  { fr: "un dossier", def: "Ensemble des documents réunis pour une démarche.", ex: "Son dossier d'immigration est enfin complet.", level: "A2" },
  { fr: "un permis de travail", def: "Document autorisant un étranger à occuper un emploi au Canada.", ex: "Elle a reçu son permis de travail ouvert en mars.", level: "A2" },
  { fr: "un permis d'études", def: "Document autorisant un étranger à étudier au Canada.", ex: "Le permis d'études couvre toute la durée du programme.", level: "A2" },
  { fr: "la résidence permanente", def: "Statut permettant de vivre et travailler au Canada sans limite de durée.", ex: "Ils ont déposé leur demande de résidence permanente.", level: "B1" },
  { fr: "la citoyenneté", def: "Statut juridique de membre à part entière d'un pays.", ex: "Après trois ans, il a demandé la citoyenneté canadienne.", level: "B1" },
  { fr: "un résident permanent", def: "Personne autorisée à s'établir durablement sans être citoyenne.", ex: "En tant que résident permanent, il peut travailler partout au pays.", level: "B1" },
  { fr: "une carte de résident permanent", def: "Carte prouvant le statut de résident permanent.", ex: "Sa carte de résident permanent expire l'an prochain.", level: "B1" },
  { fr: "un ressortissant étranger", def: "Personne qui n'est ni citoyenne ni résidente permanente du Canada.", ex: "Tout ressortissant étranger doit régulariser son statut.", level: "B2" },
  { fr: "un visa de visiteur", def: "Autorisation d'entrer au Canada pour un séjour temporaire.", ex: "Sa mère est venue avec un visa de visiteur.", level: "B1" },
  { fr: "une AVE", def: "Autorisation de voyage électronique exigée de certains voyageurs exemptés de visa.", ex: "Les Français ont besoin d'une AVE pour prendre l'avion vers le Canada.", level: "B2" },
  { fr: "le super visa", def: "Visa permettant aux parents et grands-parents de longs séjours répétés.", ex: "Grâce au super visa, ses parents restent deux ans à la fois.", level: "B2" },
  { fr: "un titre de voyage", def: "Document tenant lieu de passeport pour certaines personnes.", ex: "Le réfugié a reçu un titre de voyage canadien.", level: "B2" },
  { fr: "un statut temporaire", def: "Autorisation de séjour limitée dans le temps.", ex: "Son statut temporaire prend fin en décembre.", level: "B2" },
  { fr: "un séjour", def: "Fait de rester quelque temps dans un lieu.", ex: "Son séjour touristique ne dépasse pas six mois.", level: "A2" },
  { fr: "la double citoyenneté", def: "Fait d'être citoyen de deux pays à la fois.", ex: "Le Canada autorise la double citoyenneté.", level: "B2" },

  // ── Programmes & voies d'immigration ─────────────────────────────────
  { fr: "Entrée express", def: "Système fédéral de gestion des demandes de résidence pour travailleurs qualifiés.", ex: "Il a créé son profil dans Entrée express.", level: "B1" },
  { fr: "un profil", def: "Compte en ligne résumant le parcours d'un candidat à l'immigration.", ex: "Son profil Entrée express reste actif un an.", level: "A2" },
  { fr: "une invitation à présenter une demande", def: "Message invitant un candidat retenu à déposer son dossier complet.", ex: "Il a enfin reçu son invitation à présenter une demande.", level: "B2" },
  { fr: "un bassin de candidats", def: "Ensemble des profils en attente d'être sélectionnés.", ex: "Des milliers de profils attendent dans le bassin de candidats.", level: "B2" },
  { fr: "une ronde d'invitations", def: "Tirage périodique de candidats à qui l'on envoie une invitation.", ex: "La dernière ronde d'invitations a baissé le score exigé.", level: "B2" },
  { fr: "le Programme des travailleurs qualifiés", def: "Voie destinée aux immigrants choisis pour leur expérience et leurs compétences.", ex: "Elle est passée par le Programme des travailleurs qualifiés.", level: "B2" },
  { fr: "la catégorie de l'expérience canadienne", def: "Voie réservée à ceux qui ont déjà travaillé au Canada.", ex: "Son année de travail lui ouvre la catégorie de l'expérience canadienne.", level: "B2" },
  { fr: "le Programme des candidats des provinces", def: "Programme par lequel une province désigne des immigrants selon ses besoins.", ex: "Le Manitoba l'a retenu par le Programme des candidats des provinces.", level: "B2" },
  { fr: "une désignation provinciale", def: "Appui d'une province qui augmente fortement les chances de sélection.", ex: "Sa désignation provinciale lui a valu 600 points de plus.", level: "C1" },
  { fr: "le Programme de l'expérience québécoise", def: "Voie accélérée du Québec pour diplômés et travailleurs sur son territoire.", ex: "Le Programme de l'expérience québécoise vise les diplômés d'ici.", level: "C1" },
  { fr: "Arrima", def: "Portail du Québec où déposer une déclaration d'intérêt en immigration.", ex: "Elle a rempli sa déclaration d'intérêt dans Arrima.", level: "C1" },
  { fr: "un certificat de sélection du Québec", def: "Document par lequel le Québec approuve un candidat avant l'étape fédérale.", ex: "Sans certificat de sélection du Québec, la demande fédérale attend.", level: "C1" },
  { fr: "le parrainage", def: "Fait pour un proche établi au Canada de soutenir la venue d'un membre de sa famille.", ex: "Son mari a lancé une demande de parrainage.", level: "B1" },
  { fr: "le regroupement familial", def: "Ensemble des voies permettant de réunir une famille au Canada.", ex: "Le regroupement familial couvre le conjoint et les enfants.", level: "B2" },
  { fr: "un répondant", def: "Personne qui s'engage financièrement à parrainer un proche.", ex: "Le répondant doit prouver un revenu suffisant.", level: "B2" },
  { fr: "un engagement de parrainage", def: "Contrat par lequel le répondant assume les besoins du parrainé.", ex: "L'engagement de parrainage dure plusieurs années.", level: "C1" },
  { fr: "un travailleur étranger temporaire", def: "Personne venue occuper un emploi au Canada pour une durée limitée.", ex: "La ferme emploie des travailleurs étrangers temporaires l'été.", level: "B2" },
  { fr: "le Programme des aides familiaux", def: "Voie destinée aux personnes qui prennent soin d'enfants ou d'aînés à domicile.", ex: "Elle est arrivée par le Programme des aides familiaux.", level: "C1" },
  { fr: "un permis vacances-travail", def: "Permis permettant aux jeunes de voyager et de travailler au Canada.", ex: "Avec son permis vacances-travail, il a passé un an à Vancouver.", level: "B2" },
  { fr: "Expérience internationale Canada", def: "Programme de mobilité pour jeunes de pays partenaires.", ex: "Expérience internationale Canada l'a mené à Montréal.", level: "C1" },

  // ── Réfugiés & protection ────────────────────────────────────────────
  { fr: "un réfugié", def: "Personne protégée parce qu'elle fuit la persécution.", ex: "Le Canada accueille des réfugiés chaque année.", level: "B1" },
  { fr: "un demandeur d'asile", def: "Personne qui réclame une protection sans l'avoir encore obtenue.", ex: "Le demandeur d'asile attend l'audience de sa cause.", level: "B2" },
  { fr: "l'asile", def: "Protection accordée à une personne menacée dans son pays.", ex: "Il a demandé l'asile à son arrivée à l'aéroport.", level: "B2" },
  { fr: "la persécution", def: "Traitement injuste et cruel infligé pour des motifs comme la religion ou l'opinion.", ex: "Elle a fui la persécution politique.", level: "B2" },
  { fr: "une personne protégée", def: "Personne dont le besoin de protection a été reconnu.", ex: "Comme personne protégée, il peut demander la résidence.", level: "C1" },
  { fr: "le principe de non-refoulement", def: "Règle interdisant de renvoyer quelqu'un vers un pays où sa vie est menacée.", ex: "Le non-refoulement protège les réfugiés reconnus.", level: "C2" },
  { fr: "un parrainage privé de réfugiés", def: "Dispositif où des citoyens s'engagent à accueillir un réfugié.", ex: "Leur groupe a organisé un parrainage privé de réfugiés.", level: "C1" },
  { fr: "l'Entente sur les tiers pays sûrs", def: "Accord qui oblige à demander l'asile dans le premier pays sûr atteint.", ex: "L'Entente sur les tiers pays sûrs complique certaines demandes.", level: "C2" },
  { fr: "une audience", def: "Séance où l'on examine une demande devant un décideur.", ex: "Son audience devant la Commission a duré une heure.", level: "B2" },
  { fr: "la Commission de l'immigration et du statut de réfugié", def: "Tribunal indépendant qui tranche les cas d'immigration et d'asile.", ex: "La Commission de l'immigration et du statut de réfugié a rendu sa décision.", level: "C1" },

  // ── Critères, points & admissibilité ─────────────────────────────────
  { fr: "l'admissibilité", def: "Fait de remplir les conditions exigées pour un programme.", ex: "Vérifie ton admissibilité avant de payer les frais.", level: "B2" },
  { fr: "les critères de sélection", def: "Conditions servant à retenir ou écarter un candidat.", ex: "Les critères de sélection favorisent les jeunes diplômés.", level: "B2" },
  { fr: "un système de points", def: "Méthode qui note les candidats selon plusieurs facteurs.", ex: "Le système de points récompense l'expérience et les langues.", level: "B2" },
  { fr: "le Système de classement global", def: "Barème qui attribue un score aux candidats d'Entrée express.", ex: "Son score au Système de classement global a grimpé après le test.", level: "C1" },
  { fr: "un facteur", def: "Élément pris en compte dans l'évaluation d'une candidature.", ex: "L'âge est un facteur important dans le calcul.", level: "B1" },
  { fr: "la scolarité", def: "Niveau et durée des études suivies.", ex: "Sa scolarité universitaire lui donne plus de points.", level: "B1" },
  { fr: "l'expérience professionnelle", def: "Temps de travail accumulé dans un domaine.", ex: "Trois ans d'expérience professionnelle sont exigés.", level: "B1" },
  { fr: "la compétence linguistique", def: "Niveau de maîtrise d'une langue officielle.", ex: "Sa compétence linguistique en français pèse lourd au Québec.", level: "B2" },
  { fr: "la capacité d'adaptation", def: "Aptitude à s'intégrer rapidement à un nouveau milieu.", ex: "Un séjour antérieur montre une bonne capacité d'adaptation.", level: "C1" },
  { fr: "un seuil", def: "Valeur minimale à atteindre pour être retenu.", ex: "Le seuil de points varie d'une ronde à l'autre.", level: "B2" },
  { fr: "une offre d'emploi validée", def: "Proposition d'emploi confirmée par les autorités et ajoutant des points.", ex: "Une offre d'emploi validée a fait bondir son score.", level: "C1" },
  { fr: "une étude d'impact sur le marché du travail", def: "Analyse confirmant qu'aucun Canadien ne peut occuper le poste.", ex: "L'employeur a obtenu une étude d'impact sur le marché du travail favorable.", level: "C1" },
  { fr: "la preuve de fonds", def: "Justificatif montrant qu'on a assez d'argent pour s'établir.", ex: "La preuve de fonds exige un relevé bancaire récent.", level: "B2" },
  { fr: "l'autonomie financière", def: "Capacité à subvenir à ses besoins sans aide publique.", ex: "Le programme exige une autonomie financière suffisante.", level: "C1" },
  { fr: "une équivalence de diplôme", def: "Reconnaissance officielle d'un diplôme étranger.", ex: "Il a demandé une équivalence de diplôme avant de postuler.", level: "B2" },
  { fr: "une évaluation des diplômes d'études", def: "Rapport qui compare un diplôme étranger aux normes canadiennes.", ex: "L'évaluation des diplômes d'études a pris six semaines.", level: "C1" },
  { fr: "la reconnaissance des acquis", def: "Validation des compétences obtenues hors des filières officielles.", ex: "La reconnaissance des acquis a raccourci sa formation.", level: "C1" },
  { fr: "un ordre professionnel", def: "Organisme qui encadre l'exercice d'un métier réglementé.", ex: "Le médecin doit s'inscrire à l'ordre professionnel du Québec.", level: "B2" },
  { fr: "un permis d'exercice", def: "Autorisation d'exercer un métier réglementé.", ex: "Sans permis d'exercice, l'ingénieur ne peut pas signer de plans.", level: "C1" },
  { fr: "une profession réglementée", def: "Métier dont l'accès est contrôlé par un ordre ou une loi.", ex: "Le droit est une profession réglementée au Canada.", level: "B2" },

  // ── Tests de langue & évaluation ─────────────────────────────────────
  { fr: "un test de langue", def: "Examen mesurant le niveau de français ou d'anglais.", ex: "Le test de langue est valable deux ans.", level: "A2" },
  { fr: "le TCF Canada", def: "Test de connaissance du français reconnu pour l'immigration.", ex: "Elle a réservé son TCF Canada pour le mois prochain.", level: "B1" },
  { fr: "un niveau de compétence", def: "Palier officiel décrivant la maîtrise d'une langue.", ex: "Son niveau de compétence en écriture est très bon.", level: "B2" },
  { fr: "les Niveaux de compétence linguistique canadiens", def: "Échelle nationale mesurant la maîtrise du français ou de l'anglais.", ex: "Elle vise le niveau 7 des Niveaux de compétence linguistique canadiens.", level: "C1" },
  { fr: "un relevé de résultats", def: "Document officiel indiquant les notes obtenues à un test.", ex: "Joins ton relevé de résultats à la demande.", level: "B1" },
  { fr: "la validité", def: "Période pendant laquelle un document reste utilisable.", ex: "La validité du test expire au bout de deux ans.", level: "B2" },
  { fr: "la francisation", def: "Ensemble des cours et mesures pour apprendre le français.", ex: "Il suit des cours de francisation le soir.", level: "B2" },
  { fr: "un cours de langue pour immigrants", def: "Formation gratuite en français ou en anglais offerte aux nouveaux arrivants.", ex: "Le cours de langue pour immigrants l'aide à trouver un emploi.", level: "B2" },
  { fr: "bilingue", def: "Qui maîtrise deux langues.", ex: "Un profil bilingue est très recherché à Ottawa.", level: "A2" },
  { fr: "une langue officielle", def: "Langue reconnue par la loi pour l'administration.", ex: "Le français et l'anglais sont les langues officielles du Canada.", level: "B1" },

  // ── Démarches, frais & traitement ────────────────────────────────────
  { fr: "les frais de traitement", def: "Somme à payer pour l'examen d'une demande.", ex: "Les frais de traitement ne sont pas remboursables.", level: "B1" },
  { fr: "le droit de résidence permanente", def: "Frais exigés avant de recevoir le statut de résident permanent.", ex: "Il a acquitté le droit de résidence permanente en ligne.", level: "C1" },
  { fr: "un accusé de réception", def: "Confirmation officielle qu'une demande a bien été reçue.", ex: "L'accusé de réception est arrivé par courriel.", level: "B2" },
  { fr: "un numéro de dossier", def: "Identifiant unique attribué à une demande.", ex: "Cite ton numéro de dossier dans chaque message.", level: "A2" },
  { fr: "le délai de traitement", def: "Temps estimé pour qu'une demande soit étudiée.", ex: "Le délai de traitement dépasse parfois un an.", level: "B1" },
  { fr: "un traitement accéléré", def: "Examen plus rapide accordé à certaines demandes.", ex: "Les étudiants profitent parfois d'un traitement accéléré.", level: "C1" },
  { fr: "la biométrie", def: "Prise des empreintes et de la photo pour identifier une personne.", ex: "Il a donné sa biométrie dans un centre agréé.", level: "B2" },
  { fr: "un examen médical", def: "Contrôle de santé exigé pour certaines demandes.", ex: "L'examen médical se fait chez un médecin désigné.", level: "B1" },
  { fr: "un médecin désigné", def: "Médecin autorisé à réaliser l'examen médical d'immigration.", ex: "Prends rendez-vous avec un médecin désigné agréé.", level: "C1" },
  { fr: "un certificat de police", def: "Document attestant l'absence de casier judiciaire.", ex: "Chaque pays de résidence exige son certificat de police.", level: "B2" },
  { fr: "un casier judiciaire", def: "Relevé des condamnations pénales d'une personne.", ex: "Un casier judiciaire peut bloquer une demande.", level: "B2" },
  { fr: "une lettre d'invitation", def: "Lettre par laquelle un hôte invite officiellement un visiteur.", ex: "Son oncle a fourni une lettre d'invitation.", level: "B1" },
  { fr: "une lettre d'introduction", def: "Document remis à l'entrée du pays pour activer un permis.", ex: "Montre ta lettre d'introduction à l'agent frontalier.", level: "C1" },
  { fr: "une déclaration solennelle", def: "Affirmation écrite tenue pour vraie sous serment.", ex: "Il a signé une déclaration solennelle sur son état civil.", level: "C1" },
  { fr: "un mandataire", def: "Personne autorisée à agir au nom d'un demandeur.", ex: "Son avocat agit comme mandataire auprès du ministère.", level: "C1" },
  { fr: "un consultant en immigration", def: "Professionnel réglementé qui conseille et représente les demandeurs.", ex: "Elle a engagé un consultant en immigration agréé.", level: "B2" },
  { fr: "un avocat en immigration", def: "Juriste spécialisé dans le droit de l'immigration.", ex: "L'avocat en immigration a monté son appel.", level: "B2" },
  { fr: "une procuration", def: "Acte donnant à quelqu'un le pouvoir d'agir pour soi.", ex: "Il a signé une procuration à son frère resté au pays.", level: "C1" },
  { fr: "un renseignement", def: "Information demandée dans une démarche.", ex: "Tout renseignement faux entraîne un refus.", level: "A2" },
  { fr: "une pièce justificative", def: "Document servant à prouver ce qu'on déclare.", ex: "Joins chaque pièce justificative en format PDF.", level: "B2" },

  // ── Décisions, statuts problématiques & recours ──────────────────────
  { fr: "une approbation", def: "Décision favorable à une demande.", ex: "L'approbation est arrivée après huit mois.", level: "B1" },
  { fr: "un refus", def: "Décision de rejeter une demande.", ex: "Le refus indiquait un manque de preuves de fonds.", level: "B1" },
  { fr: "un motif de refus", def: "Raison invoquée pour rejeter une demande.", ex: "Le principal motif de refus était l'admissibilité.", level: "B2" },
  { fr: "une interdiction de territoire", def: "Décision qui empêche une personne d'entrer ou de rester au Canada.", ex: "Une fausse déclaration peut mener à une interdiction de territoire.", level: "C1" },
  { fr: "l'inadmissibilité", def: "Situation d'une personne à qui l'entrée ou le séjour est interdit.", ex: "L'inadmissibilité pour raisons médicales est rare.", level: "C1" },
  { fr: "une fausse déclaration", def: "Renseignement mensonger fourni aux autorités.", ex: "Une fausse déclaration entraîne un bannissement de cinq ans.", level: "C1" },
  { fr: "un appel", def: "Contestation d'une décision devant une instance supérieure.", ex: "Il a déposé un appel dans les trente jours.", level: "B2" },
  { fr: "une révision", def: "Réexamen d'une décision par une autre autorité.", ex: "Il a demandé une révision de son dossier.", level: "B2" },
  { fr: "un contrôle judiciaire", def: "Examen par un tribunal de la légalité d'une décision.", ex: "La Cour fédérale a accepté le contrôle judiciaire.", level: "C2" },
  { fr: "un sursis", def: "Suspension temporaire d'une mesure de renvoi.", ex: "Le juge a accordé un sursis à l'expulsion.", level: "C1" },
  { fr: "une mesure de renvoi", def: "Ordre officiel de quitter le Canada.", ex: "La mesure de renvoi a été suspendue en appel.", level: "C1" },
  { fr: "une expulsion", def: "Renvoi forcé d'une personne hors du pays.", ex: "L'expulsion a été reportée pour raisons humanitaires.", level: "B2" },
  { fr: "des motifs humanitaires", def: "Raisons de compassion justifiant une exception aux règles.", ex: "Sa demande repose sur des motifs humanitaires.", level: "C1" },
  { fr: "un rétablissement de statut", def: "Récupération d'un statut perdu, sous conditions et délais.", ex: "Il a demandé un rétablissement de statut dans les 90 jours.", level: "C1" },
  { fr: "la perte de statut", def: "Fin du droit de séjour, souvent faute de renouvellement.", ex: "Oublier la date d'expiration mène à la perte de statut.", level: "B2" },
  { fr: "un permis de séjour temporaire", def: "Autorisation exceptionnelle pour une personne autrement interdite de territoire.", ex: "Un permis de séjour temporaire lui a permis d'entrer.", level: "C1" },
  { fr: "sans papiers", def: "Se dit d'une personne qui vit dans un pays sans statut légal.", ex: "Régulariser les sans-papiers reste un débat de société.", level: "B2" },
  { fr: "la régularisation", def: "Fait d'obtenir un statut légal après une période sans papiers.", ex: "Un programme de régularisation a été annoncé.", level: "C1" },
  { fr: "une prolongation", def: "Fait d'allonger la durée d'un permis ou d'un statut.", ex: "Il a demandé une prolongation de son permis de travail.", level: "B1" },
  { fr: "un renouvellement", def: "Fait de remplacer un document arrivé à échéance.", ex: "Le renouvellement de la carte se fait tous les cinq ans.", level: "B1" },

  // ── Établissement & intégration ──────────────────────────────────────
  { fr: "s'établir", def: "S'installer durablement dans un lieu.", ex: "Ils rêvent de s'établir en Colombie-Britannique.", level: "B1" },
  { fr: "l'établissement", def: "Ensemble des premières démarches d'installation.", ex: "Un organisme l'accompagne dans son établissement.", level: "B2" },
  { fr: "l'intégration", def: "Processus par lequel un immigrant trouve sa place dans la société.", ex: "L'intégration passe par la langue et l'emploi.", level: "B2" },
  { fr: "un nouvel arrivant", def: "Personne récemment immigrée au pays.", ex: "La ville offre des ateliers pour nouveaux arrivants.", level: "A2" },
  { fr: "un organisme d'accueil", def: "Association qui aide gratuitement les immigrants à s'installer.", ex: "L'organisme d'accueil l'a aidé à ouvrir un compte.", level: "B2" },
  { fr: "un service d'établissement", def: "Aide financée par l'État pour l'installation des immigrants.", ex: "Les services d'établissement sont gratuits.", level: "B2" },
  { fr: "un agent d'intégration", def: "Personne qui guide un immigrant dans ses démarches.", ex: "Son agent d'intégration lui a trouvé une garderie.", level: "B2" },
  { fr: "le choc culturel", def: "Désarroi ressenti face à une culture très différente.", ex: "Le premier hiver a accentué son choc culturel.", level: "B2" },
  { fr: "la diversité", def: "Coexistence de personnes d'origines et de cultures variées.", ex: "La diversité est une richesse pour le pays.", level: "B1" },
  { fr: "le multiculturalisme", def: "Politique reconnaissant et valorisant la pluralité des cultures.", ex: "Le multiculturalisme est inscrit dans la loi canadienne.", level: "C1" },
  { fr: "une communauté", def: "Groupe de personnes partageant une origine ou des intérêts.", ex: "La communauté haïtienne de Montréal est très active.", level: "B1" },
  { fr: "un mentor", def: "Personne d'expérience qui guide un nouvel arrivant.", ex: "Son mentor l'a aidé à réseauter dans son domaine.", level: "B2" },
  { fr: "le réseautage", def: "Fait de tisser des contacts utiles, notamment professionnels.", ex: "Le réseautage lui a ouvert plusieurs portes.", level: "B2" },
  { fr: "un code d'établissement", def: "Numéro remis à l'arrivée pour accéder à certains services.", ex: "Note bien ton code d'établissement.", level: "C1" },
  { fr: "un numéro d'assurance sociale", def: "Identifiant nécessaire pour travailler et payer ses impôts.", ex: "Il a demandé son numéro d'assurance sociale dès son arrivée.", level: "B1" },
  { fr: "l'assurance maladie", def: "Couverture publique des soins de santé.", ex: "L'assurance maladie du Québec impose un délai de carence.", level: "B1" },
  { fr: "un délai de carence", def: "Période d'attente avant d'avoir droit à une prestation.", ex: "Souscris une assurance privée pendant le délai de carence.", level: "C1" },
  { fr: "une allocation", def: "Somme versée par l'État pour aider une catégorie de personnes.", ex: "L'allocation familiale soutient les nouveaux parents.", level: "B1" },
  { fr: "l'aide sociale", def: "Prestation de dernier recours pour les personnes sans revenu.", ex: "Recourir à l'aide sociale peut nuire à un parrainage.", level: "B2" },
  { fr: "le pays d'accueil", def: "Pays qui reçoit un immigrant.", ex: "Le Canada est devenu son pays d'accueil.", level: "B1" },

  // ── Acteurs, institutions & vocabulaire administratif ────────────────
  { fr: "IRCC", def: "Ministère fédéral chargé de l'immigration et de la citoyenneté.", ex: "IRCC met à jour les délais chaque semaine.", level: "B2" },
  { fr: "un agent d'immigration", def: "Fonctionnaire qui étudie les demandes et rend des décisions.", ex: "L'agent d'immigration a demandé des documents supplémentaires.", level: "B1" },
  { fr: "un agent des services frontaliers", def: "Fonctionnaire qui contrôle l'entrée au pays.", ex: "L'agent des services frontaliers a tamponné son passeport.", level: "B2" },
  { fr: "un point d'entrée", def: "Lieu officiel où l'on entre dans le pays.", ex: "Il a activé son permis au point d'entrée.", level: "B2" },
  { fr: "un poste frontalier", def: "Installation contrôlant le passage d'une frontière terrestre.", ex: "Le poste frontalier était bondé le dimanche soir.", level: "B2" },
  { fr: "une ambassade", def: "Représentation d'un pays dans la capitale d'un autre.", ex: "L'ambassade du Canada traite les visas de la région.", level: "B1" },
  { fr: "un consulat", def: "Bureau d'un pays à l'étranger offrant des services à ses citoyens.", ex: "Le consulat délivre les visas dans cette ville.", level: "B1" },
  { fr: "un centre de réception des demandes de visa", def: "Bureau privé qui recueille les dossiers pour le compte du gouvernement.", ex: "Dépose ta biométrie au centre de réception des demandes de visa.", level: "C1" },
  { fr: "une province", def: "Grande division administrative du Canada.", ex: "Chaque province choisit une partie de ses immigrants.", level: "A2" },
  { fr: "un territoire", def: "Division administrative du Nord canadien.", ex: "Le Yukon est un territoire, pas une province.", level: "B1" },
  { fr: "la compétence partagée", def: "Domaine où le fédéral et les provinces légifèrent ensemble.", ex: "L'immigration est une compétence partagée.", level: "C2" },
  { fr: "un accord", def: "Entente officielle entre deux gouvernements.", ex: "Un accord confie au Québec la sélection de ses immigrants.", level: "B2" },
  { fr: "un quota", def: "Nombre maximal de demandes acceptées sur une période.", ex: "Le quota de parrainages de parents se remplit vite.", level: "B2" },
  { fr: "les seuils d'immigration", def: "Nombre de nouveaux résidents que le pays vise à admettre.", ex: "Le gouvernement a relevé les seuils d'immigration.", level: "C1" },
  { fr: "un plan des niveaux d'immigration", def: "Document fixant les cibles d'admission pour les années à venir.", ex: "Le plan des niveaux d'immigration prévoit un demi-million d'arrivées.", level: "C2" },
  { fr: "le rapport annuel", def: "Bilan publié chaque année sur l'immigration.", ex: "Le rapport annuel détaille les admissions par catégorie.", level: "B2" },
  { fr: "une politique d'immigration", def: "Ensemble des orientations d'un gouvernement en matière d'immigration.", ex: "La politique d'immigration privilégie les métiers en pénurie.", level: "B2" },
  { fr: "un métier en pénurie", def: "Profession où la main-d'œuvre manque.", ex: "Les infirmières figurent parmi les métiers en pénurie.", level: "B2" },
  { fr: "l'immigration économique", def: "Volet fondé sur les besoins du marché du travail.", ex: "L'immigration économique domine les admissions.", level: "C1" },
  { fr: "une cible", def: "Objectif chiffré fixé par les autorités.", ex: "La cible francophone hors Québec a été atteinte.", level: "B2" },

  // ── Citoyenneté & derniers termes ────────────────────────────────────
  { fr: "la naturalisation", def: "Fait de devenir citoyen d'un pays d'adoption.", ex: "Sa naturalisation a été célébrée en famille.", level: "C1" },
  { fr: "un examen de citoyenneté", def: "Test sur l'histoire, la géographie et les institutions du pays.", ex: "Il révise pour son examen de citoyenneté.", level: "B2" },
  { fr: "un serment de citoyenneté", def: "Engagement solennel prononcé pour devenir citoyen.", ex: "Elle a prononcé le serment de citoyenneté avec émotion.", level: "C1" },
  { fr: "une cérémonie de citoyenneté", def: "Événement officiel où l'on remet la citoyenneté.", ex: "La cérémonie de citoyenneté s'est tenue à l'hôtel de ville.", level: "B2" },
  { fr: "un certificat de citoyenneté", def: "Document prouvant qu'on est citoyen canadien.", ex: "Son certificat de citoyenneté a remplacé la carte de résident.", level: "B2" },
  { fr: "la présence effective", def: "Nombre de jours réellement passés au pays, exigé pour la citoyenneté.", ex: "Il faut 1095 jours de présence effective sur cinq ans.", level: "C1" },
  { fr: "une obligation de résidence", def: "Nombre minimal de jours à passer au Canada pour garder son statut.", ex: "L'obligation de résidence est de deux ans sur cinq.", level: "C1" },
  { fr: "un engagement", def: "Promesse formelle de respecter certaines conditions.", ex: "Il a pris l'engagement de vivre au Québec.", level: "B2" },
  { fr: "l'apatridie", def: "Situation d'une personne qu'aucun pays ne reconnaît comme citoyenne.", ex: "L'apatridie complique la moindre démarche.", level: "C2" },
  { fr: "un droit acquis", def: "Avantage conservé malgré un changement de règle.", ex: "Les anciens demandeurs gardent un droit acquis.", level: "C1" },
  { fr: "une exemption", def: "Dispense d'une obligation normalement exigée.", ex: "Les enfants bénéficient d'une exemption de frais.", level: "B2" },
  { fr: "une déclaration d'intérêt", def: "Première étape signalant qu'on souhaite immigrer.", ex: "Sa déclaration d'intérêt a été retenue en trois semaines.", level: "C1" },
  { fr: "un parrainé", def: "Personne dont la venue est soutenue par un proche.", ex: "Le parrainé doit vivre avec son répondant.", level: "B2" },
  { fr: "un conjoint de fait", def: "Partenaire avec qui l'on vit sans être marié.", ex: "Son conjoint de fait figure sur la même demande.", level: "B2" },
  { fr: "une personne à charge", def: "Membre de la famille financièrement dépendant du demandeur.", ex: "Ses deux enfants sont des personnes à charge.", level: "B2" },
  { fr: "un membre de la famille", def: "Proche pouvant être inclus dans une demande.", ex: "Chaque membre de la famille doit passer l'examen médical.", level: "A2" },
  { fr: "un tuteur légal", def: "Adulte légalement responsable d'un mineur au Canada.", ex: "L'élève étranger doit désigner un tuteur légal.", level: "B2" },
  { fr: "un mineur non accompagné", def: "Enfant qui immigre sans ses parents.", ex: "Un mineur non accompagné reçoit un suivi particulier.", level: "C1" },
  { fr: "un point de contact", def: "Personne ou bureau à qui s'adresser pour un dossier.", ex: "Le centre d'appels reste ton point de contact.", level: "B2" },
  { fr: "un suivi de dossier", def: "Consultation de l'état d'avancement d'une demande.", ex: "Le suivi de dossier se fait dans le compte en ligne.", level: "B1" },

  // ── Documents, portail & compléments ─────────────────────────────────
  { fr: "un traducteur agréé", def: "Professionnel autorisé à traduire des documents officiels.", ex: "Un traducteur agréé a traduit son diplôme.", level: "B2" },
  { fr: "une traduction certifiée", def: "Traduction officielle acceptée par les autorités.", ex: "Joins une traduction certifiée de l'acte de naissance.", level: "C1" },
  { fr: "un pays d'origine", def: "Pays d'où vient un immigrant.", ex: "Son pays d'origine exige un visa de sortie.", level: "A2" },
  { fr: "un motif de voyage", def: "Raison invoquée pour entrer dans un pays.", ex: "Précise ton motif de voyage à l'agent.", level: "B2" },
  { fr: "une prolongation de séjour", def: "Allongement d'un séjour autorisé.", ex: "Il a obtenu une prolongation de séjour de six mois.", level: "B2" },
  { fr: "un visa fermé", def: "Permis de travail lié à un seul employeur.", ex: "Son visa fermé la retient chez cet employeur.", level: "C1" },
  { fr: "un permis de travail ouvert", def: "Permis autorisant à travailler pour tout employeur.", ex: "Le permis de travail ouvert offre plus de liberté.", level: "B2" },
  { fr: "la mobilité internationale", def: "Programmes facilitant la venue de travailleurs sans étude du marché.", ex: "La mobilité internationale accélère certaines embauches.", level: "C1" },
  { fr: "un visa étudiant", def: "Autorisation d'étudier dans un pays étranger.", ex: "Son visa étudiant couvre deux ans.", level: "B1" },
  { fr: "une lettre d'acceptation", def: "Lettre d'un établissement confirmant l'admission d'un étudiant étranger.", ex: "La lettre d'acceptation est requise pour le permis d'études.", level: "B2" },
  { fr: "un établissement désigné", def: "École reconnue pour accueillir des étudiants étrangers.", ex: "Seuls les établissements désignés donnent droit au permis.", level: "C1" },
  { fr: "un permis de travail postdiplôme", def: "Permis accordé aux diplômés pour travailler après leurs études.", ex: "Le permis de travail postdiplôme dure jusqu'à trois ans.", level: "C1" },
  { fr: "une demande en ligne", def: "Démarche effectuée par Internet.", ex: "La demande en ligne est traitée plus vite.", level: "B1" },
  { fr: "un portail", def: "Site officiel où gérer sa demande.", ex: "Téléverse tes documents sur le portail.", level: "B2" },
  { fr: "téléverser", def: "Envoyer un fichier vers un site (usage canadien).", ex: "Téléverse ton passeport en format PDF.", level: "B2" },
  { fr: "un document numérisé", def: "Copie électronique d'un document papier.", ex: "Chaque document numérisé doit être lisible.", level: "B2" },
  { fr: "un délai de conservation", def: "Durée pendant laquelle un document reste valable.", ex: "Respecte le délai de conservation des preuves.", level: "C1" },
  { fr: "une entrevue de sélection", def: "Rencontre servant à évaluer un candidat à l'immigration.", ex: "Son entrevue de sélection a eu lieu à l'ambassade.", level: "C1" },
  { fr: "un agent des visas", def: "Fonctionnaire qui décide de l'octroi d'un visa.", ex: "L'agent des visas a demandé plus de preuves.", level: "B2" },
  { fr: "un permis de résidence temporaire", def: "Document autorisant un séjour limité pour un motif précis.", ex: "Le permis de résidence temporaire couvre la durée du contrat.", level: "C1" },
];
