// Travail — 200 entries. { fr, def, ex, level } — level is CEFR (A1 → C2).
export const TRAVAIL = [
  // ── Recherche d'emploi ───────────────────────────────────────────────
  { fr: "un emploi", def: "Travail rémunéré occupé par une personne.", ex: "Il a trouvé un emploi dès son deuxième mois.", level: "A1" },
  { fr: "un travail", def: "Activité par laquelle on gagne sa vie.", ex: "Elle cherche un travail dans la restauration.", level: "A1" },
  { fr: "postuler", def: "Présenter sa candidature à un emploi.", ex: "J'ai postulé à trois offres cette semaine.", level: "A2" },
  { fr: "une candidature", def: "Démarche par laquelle on se propose pour un poste.", ex: "Sa candidature a retenu l'attention du recruteur.", level: "B1" },
  { fr: "un curriculum vitæ", def: "Document résumant le parcours et les compétences d'une personne.", ex: "Adapte ton curriculum vitæ à chaque offre.", level: "A2" },
  { fr: "un CV", def: "Abréviation courante de curriculum vitæ.", ex: "Envoie ton CV en format PDF.", level: "A1" },
  { fr: "une lettre de présentation", def: "Lettre qui accompagne le CV et défend une candidature (usage canadien).", ex: "Sa lettre de présentation était bien ciblée.", level: "B1" },
  { fr: "une offre d'emploi", def: "Annonce d'un poste à pourvoir.", ex: "L'offre d'emploi demande deux ans d'expérience.", level: "A2" },
  { fr: "une entrevue d'embauche", def: "Rencontre avec un employeur pour évaluer une candidature (québécisme).", ex: "Son entrevue d'embauche s'est très bien passée.", level: "B1" },
  { fr: "un recruteur", def: "Personne chargée de trouver et sélectionner des employés.", ex: "Le recruteur m'a rappelé le lendemain.", level: "B1" },
  { fr: "une agence de placement", def: "Entreprise qui met en relation candidats et employeurs.", ex: "Une agence de placement lui a décroché un contrat.", level: "B2" },
  { fr: "un chasseur de têtes", def: "Recruteur qui cible des profils rares ou de haut niveau.", ex: "Un chasseur de têtes l'a approchée sur les réseaux.", level: "C1" },
  { fr: "une candidature spontanée", def: "Envoi d'un CV sans qu'un poste soit annoncé.", ex: "Sa candidature spontanée a été retenue.", level: "B2" },
  { fr: "un référence", def: "Personne qui peut témoigner du sérieux d'un candidat.", ex: "Il a donné son ancien patron comme référence.", level: "B1" },
  { fr: "une embauche", def: "Fait de recruter quelqu'un.", ex: "L'embauche a été confirmée par courriel.", level: "B1" },
  { fr: "un employeur", def: "Personne ou entreprise qui engage des salariés.", ex: "Son employeur offre du télétravail.", level: "A2" },
  { fr: "un employé", def: "Personne qui travaille pour un employeur.", ex: "L'entreprise compte cinquante employés.", level: "A1" },
  { fr: "un poste", def: "Emploi précis occupé dans une organisation.", ex: "Elle vise un poste de gestionnaire.", level: "A2" },
  { fr: "un domaine", def: "Secteur d'activité ou champ de compétence.", ex: "Il travaille dans le domaine de la santé.", level: "A2" },
  { fr: "une profession", def: "Métier exercé habituellement.", ex: "Sa profession est comptable.", level: "A2" },
  { fr: "un métier", def: "Activité professionnelle exigeant un savoir-faire.", ex: "L'électricité est un métier en demande.", level: "A2" },
  { fr: "une compétence", def: "Savoir-faire utile dans le travail.", ex: "La gestion du stress est une compétence recherchée.", level: "B1" },
  { fr: "une qualification", def: "Formation ou aptitude reconnue pour un poste.", ex: "Ses qualifications dépassent les exigences.", level: "B2" },
  { fr: "l'expérience", def: "Ensemble des connaissances tirées de la pratique.", ex: "Son expérience à l'étranger est un atout.", level: "A2" },
  { fr: "un atout", def: "Avantage qui distingue un candidat.", ex: "Le bilinguisme est un atout majeur ici.", level: "B1" },

  // ── Contrat, salaire & horaires ──────────────────────────────────────
  { fr: "un contrat de travail", def: "Accord fixant les conditions d'un emploi.", ex: "Lis bien ton contrat de travail avant de signer.", level: "B1" },
  { fr: "un contrat à durée indéterminée", def: "Emploi sans date de fin prévue.", ex: "Il a décroché un contrat à durée indéterminée.", level: "B2" },
  { fr: "un contrat à durée déterminée", def: "Emploi limité à une période précise.", ex: "Son contrat à durée déterminée se termine en juin.", level: "B2" },
  { fr: "un salaire", def: "Argent versé régulièrement en échange du travail.", ex: "Son salaire est déposé toutes les deux semaines.", level: "A2" },
  { fr: "un taux horaire", def: "Somme payée pour chaque heure travaillée.", ex: "Le taux horaire dépasse le salaire minimum.", level: "B1" },
  { fr: "le salaire minimum", def: "Rémunération la plus basse permise par la loi.", ex: "Le salaire minimum a augmenté au 1er mai.", level: "B1" },
  { fr: "la rémunération", def: "Ensemble de ce qu'on reçoit pour son travail.", ex: "La rémunération inclut des primes annuelles.", level: "B2" },
  { fr: "un bulletin de paie", def: "Document détaillant le salaire et les retenues.", ex: "Vérifie les déductions sur ton bulletin de paie.", level: "B2" },
  { fr: "une retenue", def: "Somme prélevée sur le salaire brut.", ex: "Les retenues d'impôt réduisent le net.", level: "B2" },
  { fr: "le salaire net", def: "Montant réellement touché après les retenues.", ex: "Son salaire net a baissé après la hausse d'impôt.", level: "B1" },
  { fr: "le salaire brut", def: "Salaire avant toute retenue.", ex: "Le salaire brut annoncé paraît élevé.", level: "B1" },
  { fr: "un horaire", def: "Répartition des heures de travail.", ex: "Son horaire change chaque semaine.", level: "A2" },
  { fr: "le temps plein", def: "Emploi occupant toutes les heures normales.", ex: "Elle est passée au temps plein après six mois.", level: "A2" },
  { fr: "le temps partiel", def: "Emploi occupant moins d'heures que la normale.", ex: "Il étudie et travaille à temps partiel.", level: "A2" },
  { fr: "un quart de travail", def: "Période de travail dans un horaire à rotation (usage canadien).", ex: "Son quart de travail commence à 15 h.", level: "B1" },
  { fr: "le quart de nuit", def: "Période de travail effectuée la nuit.", ex: "Le quart de nuit est mieux payé.", level: "B1" },
  { fr: "des heures supplémentaires", def: "Heures travaillées au-delà de l'horaire normal.", ex: "Les heures supplémentaires sont payées à taux et demi.", level: "B1" },
  { fr: "un pourboire", def: "Somme laissée à un employé pour son service.", ex: "Au restaurant, le pourboire complète le salaire.", level: "A2" },
  { fr: "une prime", def: "Somme versée en plus du salaire habituel.", ex: "Il a reçu une prime de rendement.", level: "B1" },
  { fr: "une augmentation", def: "Hausse du salaire.", ex: "Elle a demandé une augmentation à son évaluation.", level: "B1" },
  { fr: "la période d'essai", def: "Temps initial durant lequel l'employeur évalue un nouvel employé.", ex: "La période d'essai dure trois mois.", level: "B1" },
  { fr: "la période de probation", def: "Autre nom de la période d'essai (usage canadien).", ex: "Il a été confirmé après sa période de probation.", level: "B2" },
  { fr: "le lieu de travail", def: "Endroit où l'on exerce son emploi.", ex: "Son lieu de travail est au centre-ville.", level: "A2" },
  { fr: "le télétravail", def: "Travail effectué à distance, souvent de la maison.", ex: "Le télétravail est offert deux jours par semaine.", level: "B1" },

  // ── Avantages, congés & protections ──────────────────────────────────
  { fr: "les avantages sociaux", def: "Bénéfices offerts en plus du salaire.", ex: "Les avantages sociaux comprennent une assurance dentaire.", level: "B2" },
  { fr: "une assurance collective", def: "Couverture d'assurance offerte à un groupe d'employés.", ex: "L'assurance collective rembourse les médicaments.", level: "B2" },
  { fr: "un régime de retraite", def: "Dispositif d'épargne pour la fin de carrière.", ex: "L'employeur cotise au régime de retraite.", level: "B2" },
  { fr: "un congé", def: "Autorisation de s'absenter du travail.", ex: "Il a pris un congé pour déménager.", level: "A2" },
  { fr: "des vacances", def: "Période de repos payée hors du travail.", ex: "Elle a deux semaines de vacances par an.", level: "A1" },
  { fr: "un jour férié", def: "Journée chômée et souvent payée.", ex: "La fête du Travail est un jour férié.", level: "A2" },
  { fr: "un congé de maladie", def: "Absence autorisée pour raison de santé.", ex: "Il a pris un congé de maladie de trois jours.", level: "B1" },
  { fr: "un congé parental", def: "Absence prolongée à la naissance ou l'adoption d'un enfant.", ex: "Son congé parental dure un an.", level: "B2" },
  { fr: "un congé de maternité", def: "Congé accordé à la mère autour de l'accouchement.", ex: "Elle part en congé de maternité en septembre.", level: "B1" },
  { fr: "un congé sans solde", def: "Absence autorisée mais non payée.", ex: "Il a demandé un congé sans solde pour voyager.", level: "B2" },
  { fr: "un syndicat", def: "Association qui défend les droits des travailleurs.", ex: "Le syndicat négocie les hausses de salaire.", level: "B1" },
  { fr: "une convention collective", def: "Accord fixant les conditions de travail d'un groupe.", ex: "La convention collective encadre les horaires.", level: "B2" },
  { fr: "une grève", def: "Arrêt collectif du travail pour faire pression.", ex: "Les employés ont voté la grève.", level: "B1" },
  { fr: "un piquet de grève", def: "Rassemblement de grévistes à l'entrée du lieu de travail.", ex: "Un piquet de grève bloquait l'usine.", level: "C1" },
  { fr: "une cotisation", def: "Somme versée à un syndicat ou un régime.", ex: "La cotisation syndicale est retenue sur la paie.", level: "B2" },
  { fr: "la santé et la sécurité au travail", def: "Ensemble des règles protégeant les travailleurs.", ex: "La formation en santé et sécurité au travail est obligatoire.", level: "B2" },
  { fr: "un accident du travail", def: "Blessure survenue pendant l'emploi.", ex: "Il a déclaré son accident du travail le jour même.", level: "B2" },
  { fr: "une indemnité", def: "Somme versée pour compenser un préjudice ou une perte.", ex: "Elle touche une indemnité pendant sa convalescence.", level: "B2" },
  { fr: "le harcèlement au travail", def: "Comportements répétés qui portent atteinte à un employé.", ex: "L'entreprise a une politique contre le harcèlement au travail.", level: "B2" },
  { fr: "l'équité salariale", def: "Principe d'un salaire égal pour un travail de valeur égale.", ex: "L'équité salariale corrige les écarts entre les sexes.", level: "C1" },
  { fr: "les normes du travail", def: "Règles minimales encadrant les conditions d'emploi.", ex: "Les normes du travail fixent la durée des pauses.", level: "B2" },
  { fr: "un délai de préavis", def: "Temps à respecter avant de quitter ou de congédier.", ex: "Le délai de préavis est de deux semaines.", level: "B2" },
  { fr: "une pause", def: "Court arrêt pendant le travail.", ex: "La pause du midi dure une heure.", level: "A1" },
  { fr: "une garderie subventionnée", def: "Service de garde d'enfants aidé par l'État.", ex: "Une garderie subventionnée facilite le retour au travail.", level: "B2" },
  { fr: "la conciliation travail-famille", def: "Équilibre entre les obligations professionnelles et familiales.", ex: "L'horaire flexible favorise la conciliation travail-famille.", level: "C1" },

  // ── Carrière & évolution ─────────────────────────────────────────────
  { fr: "une carrière", def: "Ensemble du parcours professionnel d'une personne.", ex: "Elle a bâti sa carrière dans l'enseignement.", level: "B1" },
  { fr: "une promotion", def: "Passage à un poste plus élevé.", ex: "Sa promotion s'accompagne d'un meilleur salaire.", level: "B1" },
  { fr: "une mutation", def: "Changement de poste ou de lieu au sein d'une organisation.", ex: "Sa mutation l'a menée à Calgary.", level: "B2" },
  { fr: "une formation", def: "Apprentissage destiné à acquérir des compétences.", ex: "L'entreprise finance une formation en gestion.", level: "A2" },
  { fr: "le perfectionnement", def: "Amélioration continue de ses compétences.", ex: "Il suit des cours de perfectionnement le soir.", level: "B2" },
  { fr: "une évaluation de rendement", def: "Bilan périodique du travail d'un employé.", ex: "Son évaluation de rendement a été excellente.", level: "B2" },
  { fr: "le rendement", def: "Résultat obtenu par rapport aux efforts fournis.", ex: "Son rendement dépasse les objectifs.", level: "B2" },
  { fr: "un objectif", def: "But à atteindre dans un délai donné.", ex: "L'équipe a dépassé son objectif du trimestre.", level: "A2" },
  { fr: "un mandat", def: "Tâche ou mission confiée à quelqu'un.", ex: "On lui a confié le mandat de réorganiser le service.", level: "B2" },
  { fr: "une responsabilité", def: "Tâche ou obligation dont on doit répondre.", ex: "Ses responsabilités ont augmenté avec le poste.", level: "B1" },
  { fr: "une démission", def: "Fait de quitter volontairement son emploi.", ex: "Il a remis sa démission après cinq ans.", level: "B2" },
  { fr: "un licenciement", def: "Renvoi d'un employé par l'employeur.", ex: "Le licenciement a été jugé injustifié.", level: "B2" },
  { fr: "un congédiement", def: "Renvoi d'un employé (usage canadien).", ex: "Son congédiement a surpris toute l'équipe.", level: "B2" },
  { fr: "une mise à pied", def: "Suspension temporaire d'un emploi, souvent faute de travail.", ex: "L'usine a annoncé des mises à pied pour l'hiver.", level: "B2" },
  { fr: "le chômage", def: "Situation d'une personne sans emploi qui en cherche un.", ex: "Le taux de chômage a baissé ce trimestre.", level: "B1" },
  { fr: "l'assurance-emploi", def: "Prestation versée aux travailleurs ayant perdu leur emploi.", ex: "Il touche l'assurance-emploi depuis un mois.", level: "B2" },
  { fr: "une prestation", def: "Somme versée par un régime public.", ex: "La prestation dépend des heures accumulées.", level: "B2" },
  { fr: "un cessation d'emploi", def: "Fin officielle d'un contrat de travail.", ex: "Le relevé de cessation d'emploi est requis pour l'assurance.", level: "C1" },
  { fr: "un relevé d'emploi", def: "Document indiquant les heures et le motif de départ.", ex: "L'employeur transmet le relevé d'emploi à Service Canada.", level: "B2" },
  { fr: "la réorientation professionnelle", def: "Changement de domaine de travail.", ex: "Sa réorientation professionnelle l'a menée vers le numérique.", level: "C1" },
  { fr: "un stage", def: "Période de formation pratique en entreprise.", ex: "Son stage de fin d'études dure quatre mois.", level: "B1" },
  { fr: "un apprentissage", def: "Formation d'un métier alliant travail et cours.", ex: "L'apprentissage de plombier dure quatre ans.", level: "B2" },
  { fr: "un compagnon", def: "Ouvrier qualifié qui a terminé son apprentissage.", ex: "Il est devenu compagnon électricien.", level: "C1" },
  { fr: "un certificat de qualification", def: "Attestation officielle qu'on maîtrise un métier.", ex: "Le certificat de qualification est exigé sur les chantiers.", level: "C1" },
  { fr: "l'ancienneté", def: "Durée passée dans un emploi ou une entreprise.", ex: "Son ancienneté lui donne priorité pour les vacances.", level: "B2" },

  // ── Vie de bureau & collègues ────────────────────────────────────────
  { fr: "un collègue", def: "Personne avec qui l'on travaille.", ex: "Ses collègues l'ont bien accueillie.", level: "A2" },
  { fr: "un patron", def: "Personne qui dirige et emploie.", ex: "Son patron est très accessible.", level: "A2" },
  { fr: "un gestionnaire", def: "Personne qui dirige une équipe ou un service.", ex: "Le gestionnaire organise les horaires.", level: "B1" },
  { fr: "un superviseur", def: "Personne qui encadre le travail d'autres employés.", ex: "Adresse ta demande à ton superviseur.", level: "B1" },
  { fr: "un directeur", def: "Personne à la tête d'une organisation ou d'un service.", ex: "Le directeur a présenté les résultats annuels.", level: "A2" },
  { fr: "une équipe", def: "Groupe de personnes travaillant ensemble.", ex: "L'équipe se réunit chaque lundi.", level: "A2" },
  { fr: "une réunion", def: "Rencontre de travail pour discuter ou décider.", ex: "La réunion a été reportée à mardi.", level: "A2" },
  { fr: "un ordre du jour", def: "Liste des points à traiter en réunion.", ex: "L'ordre du jour comptait cinq sujets.", level: "B2" },
  { fr: "un compte rendu", def: "Résumé écrit de ce qui s'est dit en réunion.", ex: "Elle rédige le compte rendu après chaque rencontre.", level: "B2" },
  { fr: "un courriel", def: "Message électronique, e-mail (usage canadien).", ex: "Envoyez votre CV par courriel.", level: "A2" },
  { fr: "une échéance", def: "Date limite pour terminer un travail.", ex: "L'échéance du projet est vendredi.", level: "B1" },
  { fr: "un délai", def: "Temps accordé pour accomplir une tâche.", ex: "Le délai est trop court pour tout finir.", level: "A2" },
  { fr: "une tâche", def: "Travail précis à accomplir.", ex: "Il a terminé toutes ses tâches avant midi.", level: "A2" },
  { fr: "un projet", def: "Ensemble d'actions menées vers un but.", ex: "Le projet mobilise trois services.", level: "A2" },
  { fr: "un livrable", def: "Résultat concret attendu d'un projet.", ex: "Le premier livrable est dû vendredi.", level: "B2" },
  { fr: "la productivité", def: "Quantité de travail produite dans un temps donné.", ex: "Le télétravail a amélioré sa productivité.", level: "B2" },
  { fr: "la charge de travail", def: "Quantité de tâches à accomplir.", ex: "Sa charge de travail a doublé cet automne.", level: "B2" },
  { fr: "une réunion d'équipe", def: "Rencontre régulière des membres d'une équipe.", ex: "La réunion d'équipe fait le point sur les priorités.", level: "B1" },
  { fr: "un suivi", def: "Action de vérifier l'avancement d'un dossier.", ex: "Je te fais un suivi demain matin.", level: "B1" },
  { fr: "une rétroaction", def: "Retour donné à quelqu'un sur son travail (usage canadien).", ex: "Sa rétroaction était constructive.", level: "B2" },
  { fr: "un organigramme", def: "Schéma montrant la structure d'une organisation.", ex: "L'organigramme précise qui relève de qui.", level: "B2" },
  { fr: "un poste vacant", def: "Emploi disponible à combler.", ex: "Deux postes vacants ont été affichés.", level: "B2" },
  { fr: "une affectation", def: "Attribution d'une tâche ou d'un lieu à un employé.", ex: "Sa nouvelle affectation est au service client.", level: "B2" },
  { fr: "la disponibilité", def: "Moments où l'on peut travailler.", ex: "Indique tes disponibilités pour la fin de semaine.", level: "B1" },
  { fr: "un remplacement", def: "Fait d'occuper temporairement le poste d'un autre.", ex: "Elle fait un remplacement pendant un congé.", level: "B1" },

  // ── Travail autonome & entreprise ────────────────────────────────────
  { fr: "un travailleur autonome", def: "Personne qui travaille pour son propre compte.", ex: "Comme travailleur autonome, il gère ses factures.", level: "B2" },
  { fr: "la pige", def: "Travail effectué à son compte pour divers clients.", ex: "Elle vit de la pige en traduction.", level: "C1" },
  { fr: "un pigiste", def: "Personne qui travaille à la pige.", ex: "Le journal engage plusieurs pigistes.", level: "C1" },
  { fr: "un contrat de service", def: "Entente pour fournir un travail précis à un client.", ex: "Il a signé un contrat de service de six mois.", level: "B2" },
  { fr: "une entreprise", def: "Organisation qui produit des biens ou des services.", ex: "L'entreprise embauche dans tout le pays.", level: "A2" },
  { fr: "une PME", def: "Petite ou moyenne entreprise.", ex: "Les PME créent la plupart des emplois.", level: "B2" },
  { fr: "une facture", def: "Document réclamant le paiement d'un travail.", ex: "Il envoie sa facture à la fin de chaque mandat.", level: "B1" },
  { fr: "un client", def: "Personne ou entreprise qui achète un service.", ex: "Son plus gros client est une municipalité.", level: "A2" },
  { fr: "un fournisseur", def: "Entreprise qui vend des biens à une autre.", ex: "Le fournisseur a livré en retard.", level: "B1" },
  { fr: "la comptabilité", def: "Gestion des recettes et des dépenses.", ex: "Il confie sa comptabilité à un professionnel.", level: "B2" },
  { fr: "un chiffre d'affaires", def: "Total des ventes sur une période.", ex: "Son chiffre d'affaires a doublé en deux ans.", level: "B2" },
  { fr: "un bénéfice", def: "Gain qui reste après les dépenses.", ex: "L'entreprise réinvestit ses bénéfices.", level: "B2" },
  { fr: "une dépense", def: "Argent utilisé pour payer quelque chose.", ex: "Il déduit ses dépenses professionnelles.", level: "B1" },
  { fr: "un investissement", def: "Argent placé pour obtenir un gain futur.", ex: "L'achat du matériel est un bon investissement.", level: "B2" },
  { fr: "l'incorporation", def: "Fait de constituer son activité en société.", ex: "L'incorporation lui offre des avantages fiscaux.", level: "C1" },
  { fr: "un permis d'exploitation", def: "Autorisation d'exercer une activité commerciale.", ex: "Le restaurant a obtenu son permis d'exploitation.", level: "C1" },
  { fr: "une taxe de vente", def: "Impôt ajouté au prix d'un bien ou d'un service.", ex: "La taxe de vente s'ajoute à la facture.", level: "B2" },
  { fr: "un numéro d'entreprise", def: "Identifiant attribué à une entreprise par l'État.", ex: "Le numéro d'entreprise figure sur ses factures.", level: "B2" },
  { fr: "un démarrage d'entreprise", def: "Lancement d'une nouvelle activité.", ex: "Un programme soutient le démarrage d'entreprise des immigrants.", level: "C1" },
  { fr: "un plan d'affaires", def: "Document présentant un projet d'entreprise.", ex: "La banque exige un plan d'affaires solide.", level: "B2" },

  // ── Secteurs, marché & termes avancés ────────────────────────────────
  { fr: "le marché du travail", def: "Ensemble de l'offre et de la demande d'emplois.", ex: "Le marché du travail manque de main-d'œuvre.", level: "B2" },
  { fr: "la main-d'œuvre", def: "Ensemble des travailleurs disponibles.", ex: "La région cherche de la main-d'œuvre qualifiée.", level: "B2" },
  { fr: "une pénurie de main-d'œuvre", def: "Manque de travailleurs dans un secteur.", ex: "La pénurie de main-d'œuvre touche la construction.", level: "B2" },
  { fr: "un secteur", def: "Grande division de l'activité économique.", ex: "Le secteur des technologies recrute beaucoup.", level: "B1" },
  { fr: "une industrie", def: "Ensemble des entreprises d'un même domaine.", ex: "L'industrie forestière emploie toute la région.", level: "B1" },
  { fr: "la relève", def: "Prochaine génération de travailleurs d'un secteur.", ex: "L'entreprise forme sa relève.", level: "C1" },
  { fr: "le roulement de personnel", def: "Rythme auquel les employés partent et sont remplacés.", ex: "Un fort roulement de personnel coûte cher.", level: "C1" },
  { fr: "la fidélisation", def: "Efforts pour garder ses employés.", ex: "La fidélisation passe par de bons avantages.", level: "C1" },
  { fr: "un chercheur d'emploi", def: "Personne qui cherche activement du travail.", ex: "Le salon attire des milliers de chercheurs d'emploi.", level: "B1" },
  { fr: "un salon de l'emploi", def: "Événement réunissant employeurs et candidats.", ex: "Elle a rencontré trois recruteurs au salon de l'emploi.", level: "B2" },
  { fr: "un emploi précaire", def: "Travail instable, sans garantie de durée.", ex: "Les emplois précaires se multiplient.", level: "C1" },
  { fr: "la sous-traitance", def: "Confier une partie du travail à une autre entreprise.", ex: "La sous-traitance réduit ses coûts.", level: "C1" },
  { fr: "le travail saisonnier", def: "Emploi limité à une saison de l'année.", ex: "Le travail saisonnier reprend au printemps.", level: "B2" },
  { fr: "un emploi à distance", def: "Travail fait entièrement hors du bureau.", ex: "Cet emploi à distance permet de vivre en région.", level: "B1" },
  { fr: "la mobilité professionnelle", def: "Capacité à changer d'emploi, de poste ou de lieu.", ex: "Sa mobilité professionnelle facilite l'embauche.", level: "C1" },
  { fr: "le perfectionnement continu", def: "Mise à jour permanente de ses compétences.", ex: "Le perfectionnement continu est valorisé dans ce métier.", level: "C1" },
  { fr: "une compétence transférable", def: "Aptitude utile d'un emploi à l'autre.", ex: "La gestion de projet est une compétence transférable.", level: "C1" },
  { fr: "l'épuisement professionnel", def: "État d'épuisement causé par le stress au travail.", ex: "L'épuisement professionnel l'a forcée à s'arrêter.", level: "C1" },
  { fr: "un travailleur essentiel", def: "Personne dont le travail reste indispensable en tout temps.", ex: "Les travailleurs essentiels sont restés en poste.", level: "B2" },
  { fr: "la reconversion", def: "Passage à un nouveau métier après une formation.", ex: "Sa reconversion vers l'informatique a réussi.", level: "C1" },
  { fr: "une perspective d'emploi", def: "Possibilité future de trouver du travail.", ex: "Ce secteur offre de belles perspectives d'emploi.", level: "B2" },
  { fr: "un poste de direction", def: "Emploi de haut niveau avec pouvoir de décision.", ex: "Elle vise un poste de direction d'ici cinq ans.", level: "B2" },
  { fr: "la gestion", def: "Fait d'organiser et de diriger des ressources.", ex: "La gestion du personnel exige de la diplomatie.", level: "B1" },
  { fr: "le leadership", def: "Capacité à guider et motiver une équipe.", ex: "Son leadership a redressé le service.", level: "B2" },
  { fr: "une entrevue de départ", def: "Rencontre au moment de quitter un emploi.", ex: "L'entrevue de départ sert à comprendre son choix.", level: "C1" },

  // ── Recrutement, contrats & vie professionnelle (compléments) ────────
  { fr: "une convention de stage", def: "Entente encadrant un stage en entreprise.", ex: "La convention de stage est signée par l'école.", level: "B2" },
  { fr: "un préavis de départ", def: "Avis donné à l'employeur avant de quitter un emploi.", ex: "Il a donné un préavis de départ de deux semaines.", level: "B2" },
  { fr: "une lettre de démission", def: "Écrit annonçant qu'on quitte son poste.", ex: "Sa lettre de démission est courte et polie.", level: "B2" },
  { fr: "un certificat de travail", def: "Document attestant un emploi passé.", ex: "L'employeur remet un certificat de travail au départ.", level: "B2" },
  { fr: "une attestation d'emploi", def: "Document confirmant qu'on occupe un poste.", ex: "La banque exige une attestation d'emploi.", level: "B2" },
  { fr: "une description de poste", def: "Texte détaillant les tâches d'un emploi.", ex: "La description de poste mentionne des déplacements.", level: "B2" },
  { fr: "un profil de compétences", def: "Résumé des aptitudes d'un candidat.", ex: "Son profil de compétences correspond à l'offre.", level: "C1" },
  { fr: "une entrevue téléphonique", def: "Entretien d'embauche mené par téléphone.", ex: "L'entrevue téléphonique a duré vingt minutes.", level: "B1" },
  { fr: "une deuxième entrevue", def: "Nouvel entretien après une première sélection.", ex: "Elle est convoquée à une deuxième entrevue.", level: "B1" },
  { fr: "un test de sélection", def: "Épreuve servant à choisir un candidat.", ex: "Le test de sélection évalue la logique.", level: "B2" },
  { fr: "une offre d'embauche", def: "Proposition officielle d'emploi faite à un candidat.", ex: "Il a accepté l'offre d'embauche par écrit.", level: "B2" },
  { fr: "une négociation salariale", def: "Discussion pour fixer le salaire d'un poste.", ex: "La négociation salariale s'est bien passée.", level: "C1" },
  { fr: "un plan de carrière", def: "Projet d'évolution professionnelle.", ex: "Son plan de carrière vise la gestion.", level: "B2" },
  { fr: "une évaluation annuelle", def: "Bilan de rendement fait chaque année.", ex: "L'évaluation annuelle décide des augmentations.", level: "B2" },
  { fr: "un mentorat", def: "Accompagnement d'un employé par une personne d'expérience.", ex: "Le mentorat facilite l'intégration des recrues.", level: "C1" },
  { fr: "un parcours d'intégration", def: "Étapes d'accueil et de formation d'un nouvel employé.", ex: "Le parcours d'intégration inclut une formation.", level: "C1" },
  { fr: "une politique interne", def: "Règle propre à une entreprise.", ex: "La politique interne interdit le travail au noir.", level: "B2" },
  { fr: "le travail au noir", def: "Travail rémunéré mais non déclaré.", ex: "Le travail au noir prive de protections.", level: "C1" },
  { fr: "un horaire flexible", def: "Horaire que l'employé peut ajuster.", ex: "L'horaire flexible aide les parents.", level: "B2" },
  { fr: "un horaire rotatif", def: "Horaire qui change selon les quarts.", ex: "Son horaire rotatif complique sa vie sociale.", level: "C1" },
  { fr: "une semaine de travail", def: "Nombre d'heures travaillées par semaine.", ex: "La semaine de travail est de 37 heures et demie.", level: "B1" },
  { fr: "un jour de congé", def: "Journée sans travail.", ex: "Son jour de congé tombe le mercredi.", level: "A2" },
  { fr: "une banque de congés", def: "Réserve de journées de congé accumulées.", ex: "Il puise dans sa banque de congés.", level: "C1" },
  { fr: "un accommodement", def: "Ajustement offert à un employé pour ses besoins.", ex: "Un accommodement lui permet d'adapter son horaire.", level: "C1" },
  { fr: "un code de conduite", def: "Règles de comportement à respecter au travail.", ex: "Le code de conduite interdit le harcèlement.", level: "B2" },
  { fr: "un renvoi", def: "Fait pour un employé d'être mis à la porte.", ex: "Le renvoi peut être contesté.", level: "B2" },
  { fr: "une indemnité de départ", def: "Somme versée à la fin d'un emploi.", ex: "Son indemnité de départ équivaut à trois mois de salaire.", level: "C1" },
  { fr: "un recours", def: "Moyen légal de contester une décision.", ex: "Il a un recours contre son congédiement.", level: "B2" },
  { fr: "la santé mentale au travail", def: "Bien-être psychologique des employés.", ex: "L'entreprise investit dans la santé mentale au travail.", level: "C1" },
  { fr: "un poste à combler", def: "Emploi vacant à pourvoir.", ex: "Trois postes à combler ont été affichés.", level: "B2" },
  { fr: "la diversité en emploi", def: "Présence de profils variés au sein du personnel.", ex: "L'entreprise valorise la diversité en emploi.", level: "C1" },
];
