// Grammar lessons + exercises. Each topic has a short `lesson` (bullets) and a
// bank of exercises `qs` = { q, opts, a (index of correct opt), exp }. The quiz
// mode (see GrammarQuiz) draws from every topic's `qs` at once.
export const GRAMMAR_TOPICS = [
  {
    id: "articles",
    t: "Les articles",
    d: "Définis, indéfinis et partitifs : le, la, un, du, des…",
    lesson: [
      "Les articles définis (le, la, l', les) désignent une chose précise ou une généralité : « J'aime le café. »",
      "Les articles indéfinis (un, une, des) introduisent un élément non identifié : « Elle cherche un appartement. »",
      "Les partitifs (du, de la, de l') expriment une quantité indéterminée : « Il boit du thé. »",
      "Après une négation, un/une/du/des deviennent « de » : « Je n'ai pas de voiture. »",
    ],
    qs: [
      { q: "Je ne mange pas ___ viande.", opts: ["de la", "de", "la", "une"], a: 1, exp: "Après une négation, le partitif « de la » devient « de »." },
      { q: "Elle adore ___ hiver canadien.", opts: ["un", "l'", "du", "de"], a: 1, exp: "Devant une voyelle, l'article défini s'élide : « l'hiver »." },
      { q: "Nous achetons ___ pain à la boulangerie.", opts: ["du", "le", "un", "de"], a: 0, exp: "Une quantité indéterminée d'une matière → partitif « du »." },
      { q: "J'ai acheté ___ pommes au marché.", opts: ["les", "des", "de", "du"], a: 1, exp: "Une quantité indéterminée au pluriel → indéfini « des »." },
      { q: "Il n'y a plus ___ lait dans le frigo.", opts: ["du", "de", "le", "de la"], a: 1, exp: "Après une négation, « du » devient « de »." },
      { q: "Elle est ___ meilleure élève de la classe.", opts: ["la", "une", "de la", "l'"], a: 0, exp: "Un superlatif porte sur un nom précis → article défini « la »." },
      { q: "Je voudrais ___ eau, s'il vous plaît.", opts: ["de l'", "l'", "une", "du"], a: 0, exp: "Quantité indéterminée devant une voyelle → partitif « de l' »." },
      { q: "___ Canada est un grand pays.", opts: ["Le", "La", "Un", "L'"], a: 0, exp: "Nom de pays masculin → article défini « le »." },
      { q: "Il achète ___ fleurs pour sa mère.", opts: ["des", "les", "de", "du"], a: 0, exp: "Quantité indéterminée au pluriel → indéfini « des »." },
      { q: "Je n'ai pas ___ argent sur moi.", opts: ["de l'", "d'", "de", "du"], a: 1, exp: "Après une négation, « de » s'élide devant une voyelle → « d' »." },
      { q: "___ soleil brille fort aujourd'hui.", opts: ["Le", "Un", "Du", "De"], a: 0, exp: "Une chose unique → article défini « le »." },
      { q: "Elle joue ___ piano depuis dix ans.", opts: ["du", "le", "au", "de"], a: 0, exp: "« Jouer de » + instrument → « jouer du piano » (de + le)." },
      { q: "Nous mangeons ___ soupe ce soir.", opts: ["de la", "la", "une", "de"], a: 0, exp: "Quantité indéterminée d'une matière féminine → partitif « de la »." },
      { q: "As-tu ___ questions à poser ?", opts: ["des", "les", "de", "du"], a: 0, exp: "Pluriel indéterminé → indéfini « des »." },
      { q: "Le midi, il boit ___ eau seulement.", opts: ["de l'", "l'", "une", "du"], a: 0, exp: "Quantité indéterminée devant une voyelle → partitif « de l' »." },
      { q: "Je préfère ___ thé vert au thé noir.", opts: ["le", "du", "de", "un"], a: 0, exp: "Une préférence générale → article défini « le »." },
    ],
  },
  {
    id: "pronouns",
    t: "Les pronoms",
    d: "COD, COI, y, en et pronoms relatifs.",
    lesson: [
      "Les pronoms COD (le, la, les) remplacent un complément direct : « Ce film ? Je l'ai vu. »",
      "Les pronoms COI (lui, leur) remplacent « à + personne » : « Je lui téléphone. »",
      "« Y » remplace un lieu ou « à + chose » : « J'y pense. » « En » remplace « de + chose » : « J'en veux. »",
      "Qui, que, dont, où relient deux phrases : « La ville où j'habite. »",
    ],
    qs: [
      { q: "Tu as parlé à tes parents ? — Oui, je ___ ai parlé hier.", opts: ["les", "leur", "y", "en"], a: 1, exp: "« Parler à quelqu'un » → pronom COI « leur »." },
      { q: "C'est le dossier ___ j'ai besoin.", opts: ["que", "qui", "dont", "où"], a: 2, exp: "« Avoir besoin de » → pronom relatif « dont »." },
      { q: "Tu as vu Marie ? — Oui, je ___ ai vue ce matin.", opts: ["la", "lui", "l'", "le"], a: 2, exp: "COD féminin devant une voyelle → « l' » (« je l'ai vue »)." },
      { q: "Vous allez à Toronto ? — Oui, nous ___ allons demain.", opts: ["y", "en", "la", "lui"], a: 0, exp: "« Y » remplace un lieu (à Toronto)." },
      { q: "Il a besoin de sucre ? — Oui, il ___ a besoin.", opts: ["y", "en", "le", "lui"], a: 1, exp: "« En » remplace « de + chose » (de sucre)." },
      { q: "La maison ___ nous avons visitée est à vendre.", opts: ["qui", "que", "dont", "où"], a: 1, exp: "« Que » est complément d'objet direct de « visiter »." },
      { q: "Voici le professeur ___ enseigne le français.", opts: ["qui", "que", "dont", "où"], a: 0, exp: "« Qui » est sujet du verbe « enseigne »." },
      { q: "Tu donnes le livre à Paul ? — Oui, je ___ donne.", opts: ["le lui", "lui le", "la lui", "les lui"], a: 0, exp: "COD « le » + COI « lui » dans cet ordre → « le lui »." },
      { q: "Tu connais cette chanson ? — Oui, je ___ connais.", opts: ["la", "lui", "y", "en"], a: 0, exp: "COD féminin → « la »." },
      { q: "Elle pense à ses vacances ? — Oui, elle ___ pense.", opts: ["les", "y", "lui", "en"], a: 1, exp: "« Penser à + chose » → « y »." },
      { q: "Vous avez des enfants ? — Oui, nous ___ avons deux.", opts: ["les", "en", "y", "leur"], a: 1, exp: "« En » remplace « de + nom » avec une quantité : « nous en avons deux »." },
      { q: "Le sujet ___ tu parles est passionnant.", opts: ["que", "qui", "dont", "où"], a: 2, exp: "« Parler de » → pronom relatif « dont »." },
      { q: "Je téléphone à ma sœur ce soir. → Je ___ téléphone.", opts: ["la", "lui", "l'", "y"], a: 1, exp: "« Téléphoner à quelqu'un » → COI « lui »." },
      { q: "Tu as mangé tes légumes ? — Oui, je ___ ai tous mangés.", opts: ["les", "en", "y", "leur"], a: 0, exp: "COD défini pluriel → « les » (« je les ai mangés »)." },
      { q: "Nous habitons un quartier ___ tout est proche.", opts: ["que", "dont", "où", "qui"], a: 2, exp: "« Où » indique le lieu (dans lequel)." },
      { q: "Ces photos ___ sont sur la table sont à moi.", opts: ["qui", "que", "dont", "où"], a: 0, exp: "« Qui » est sujet du verbe « sont »." },
    ],
  },
  {
    id: "verbs",
    t: "Les verbes",
    d: "Groupes, auxiliaires et verbes pronominaux.",
    lesson: [
      "Le français compte trois groupes : -er (parler), -ir (finir) et les irréguliers (prendre, aller…).",
      "Aux temps composés, la plupart des verbes utilisent « avoir » ; les verbes de mouvement et pronominaux utilisent « être ».",
      "Avec « être », le participe s'accorde : « Elles sont arrivées. »",
      "Les verbes pronominaux se conjuguent avec un pronom réfléchi : « Je me lève à 7 h. »",
    ],
    qs: [
      { q: "Hier, elles ___ au parc La Fontaine.", opts: ["ont allé", "sont allées", "sont allés", "ont allées"], a: 1, exp: "« Aller » se conjugue avec « être » et s'accorde : « sont allées »." },
      { q: "Nous ___ fini nos devoirs.", opts: ["sommes", "avons", "ont", "avez"], a: 1, exp: "« Finir » se conjugue avec « avoir » : « nous avons fini »." },
      { q: "Le matin, je ___ à sept heures.", opts: ["me lève", "lève", "me lever", "m'ai levé"], a: 0, exp: "Verbe pronominal au présent : « je me lève »." },
      { q: "Ils ___ partis très tôt ce matin.", opts: ["ont", "sont", "avez", "est"], a: 1, exp: "« Partir » est un verbe de mouvement → auxiliaire « être »." },
      { q: "Elle s'est ___ les mains avant de manger.", opts: ["lavé", "lavée", "lavés", "lavées"], a: 0, exp: "Le COD (les mains) est placé après : le participe ne s'accorde pas → « lavé »." },
      { q: "Vous ___ le métro tous les jours ?", opts: ["prenez", "prennez", "prendez", "prend"], a: 0, exp: "« Prendre » : « vous prenez » (un seul n)." },
      { q: "Chaque hiver, il ___ beaucoup dans le Nord.", opts: ["neige", "neigent", "neiger", "neigera"], a: 0, exp: "Verbe impersonnel au présent : « il neige »." },
      { q: "Nous ___ arrivés à Montréal hier soir.", opts: ["avons", "sommes", "ont", "êtes"], a: 1, exp: "« Arriver » (mouvement) → « être » : « nous sommes arrivés »." },
      { q: "Vous ___ français très bien.", opts: ["parlez", "parler", "parlé", "parles"], a: 0, exp: "« Parler », 2e personne du pluriel → « vous parlez »." },
      { q: "Elles se sont ___ à la fête hier.", opts: ["amusé", "amusées", "amusés", "amusée"], a: 1, exp: "Pronominal, sujet féminin pluriel → accord : « amusées »." },
      { q: "J'___ mes clés ce matin.", opts: ["ai perdu", "suis perdu", "a perdu", "ai perdue"], a: 0, exp: "« Perdre » avec « avoir », COD placé après → pas d'accord : « j'ai perdu »." },
      { q: "Le week-end, nous ___ tard.", opts: ["nous levons", "levons", "nous lever", "se levons"], a: 0, exp: "Pronominal, 1re pers. du pluriel → « nous nous levons »." },
      { q: "Il ___ ses devoirs avant de sortir.", opts: ["a fait", "est fait", "a faites", "fait fait"], a: 0, exp: "« Faire » se conjugue avec « avoir » : « il a fait »." },
      { q: "Tu ___ déjà venu ici ?", opts: ["as", "es", "a", "est"], a: 1, exp: "« Venir » (mouvement) → « être » : « tu es venu »." },
      { q: "Les enfants ___ dans le jardin toute l'après-midi.", opts: ["ont joué", "sont joué", "ont joués", "sont joués"], a: 0, exp: "« Jouer » avec « avoir », sans accord → « ont joué »." },
      { q: "Elle ___ la porte doucement.", opts: ["a ouvert", "est ouverte", "a ouverte", "ouvri"], a: 0, exp: "« Ouvrir » avec « avoir », COD placé après → « a ouvert »." },
    ],
  },
  {
    id: "tenses",
    t: "Les temps",
    d: "Présent, passé composé, imparfait, futur, conditionnel, subjonctif.",
    lesson: [
      "Le passé composé raconte des actions ponctuelles et achevées ; l'imparfait décrit le contexte et les habitudes.",
      "« Quand je suis arrivé (action), il neigeait (décor). »",
      "Le futur simple exprime une prévision ; le conditionnel, une hypothèse ou une politesse.",
      "Le subjonctif suit les expressions de volonté, de doute ou d'émotion : « Il faut que tu viennes. »",
    ],
    qs: [
      { q: "Il faut que vous ___ votre passeport.", opts: ["apportez", "apporterez", "apportiez", "apporter"], a: 2, exp: "« Il faut que » exige le subjonctif : « apportiez »." },
      { q: "Avant, nous ___ chaque été au bord du lac.", opts: ["allions", "sommes allés", "irons", "irions"], a: 0, exp: "Une habitude dans le passé → imparfait : « allions »." },
      { q: "Quand je suis entré, elle ___ la télévision.", opts: ["regardait", "a regardé", "regarde", "regardera"], a: 0, exp: "Une action en cours dans le passé (décor) → imparfait : « regardait »." },
      { q: "Demain, je ___ mon examen de français.", opts: ["passe", "passais", "passerai", "passerais"], a: 2, exp: "Une action future → futur simple : « je passerai »." },
      { q: "Si j'avais le temps, je ___ plus souvent.", opts: ["voyagerai", "voyagerais", "voyage", "voyageais"], a: 1, exp: "« Si » + imparfait → conditionnel présent : « voyagerais »." },
      { q: "Hier, ils ___ un très bon film au cinéma.", opts: ["voyaient", "ont vu", "verront", "voient"], a: 1, exp: "Une action ponctuelle et achevée → passé composé : « ont vu »." },
      { q: "Je doute qu'il ___ raison.", opts: ["a", "ait", "aura", "avait"], a: 1, exp: "« Douter que » exprime le doute → subjonctif : « ait »." },
      { q: "Est-ce que tu ___ m'aider, s'il te plaît ?", opts: ["peux", "pourrais", "pouvais", "pourras"], a: 1, exp: "Une demande polie → conditionnel : « pourrais »." },
      { q: "L'année prochaine, nous ___ au Canada.", opts: ["déménagions", "déménageons", "déménagerons", "déménagerions"], a: 2, exp: "Un projet futur → futur simple : « déménagerons »." },
      { q: "Quand j'étais petit, j'___ souvent chez mes grands-parents.", opts: ["allais", "suis allé", "irai", "aille"], a: 0, exp: "Une habitude passée → imparfait : « allais »." },
      { q: "Elle veut que tu ___ à l'heure demain.", opts: ["es", "sois", "seras", "étais"], a: 1, exp: "« Vouloir que » → subjonctif : « sois »." },
      { q: "Hier soir, il ___ quand je suis rentré.", opts: ["pleuvait", "a plu", "pleuvra", "pleut"], a: 0, exp: "Une action en cours dans le passé (décor) → imparfait : « pleuvait »." },
      { q: "Nous ___ ce contrat la semaine dernière.", opts: ["signions", "avons signé", "signerons", "signerions"], a: 1, exp: "Une action ponctuelle et achevée → passé composé : « avons signé »." },
      { q: "Si tu étudiais plus, tu ___ de meilleures notes.", opts: ["auras", "aurais", "as", "avais"], a: 1, exp: "« Si » + imparfait → conditionnel : « aurais »." },
      { q: "Je suis content que vous ___ là.", opts: ["êtes", "soyez", "serez", "étiez"], a: 1, exp: "Une émotion (« content que ») → subjonctif : « soyez »." },
      { q: "Dès que le printemps ___, la neige fondra.", opts: ["arrive", "arrivera", "arriverait", "arrivait"], a: 1, exp: "« Dès que » avec une principale au futur → futur : « arrivera »." },
    ],
  },
  {
    id: "prepositions",
    t: "Les prépositions",
    d: "à, de, en, chez, pour, avec les lieux et les pays.",
    lesson: [
      "Villes : « à » (à Montréal). Pays féminins ou à voyelle : « en » (en France, en Ontario*). Pays masculins : « au » (au Canada). Pluriels : « aux » (aux États-Unis).",
      "*Les provinces suivent des usages particuliers : en Ontario, au Québec, en Alberta, au Manitoba.",
      "« Chez » s'emploie devant une personne ou un commerce : « chez le médecin ».",
    ],
    qs: [
      { q: "Elle habite ___ Québec depuis deux ans.", opts: ["en", "à", "au", "dans"], a: 2, exp: "Pour la province, on dit « au Québec » (mais « à Québec » pour la ville !)." },
      { q: "Ils déménagent ___ France cet été.", opts: ["au", "en", "à", "aux"], a: 1, exp: "Pays féminin → « en France »." },
      { q: "Nous allons ___ États-Unis en voiture.", opts: ["en", "au", "aux", "à"], a: 2, exp: "Pays au pluriel → « aux États-Unis »." },
      { q: "Mon frère vit ___ Toronto.", opts: ["au", "en", "à", "dans"], a: 2, exp: "Devant une ville → « à Toronto »." },
      { q: "Elle travaille ___ Canada depuis un an.", opts: ["en", "à", "au", "aux"], a: 2, exp: "Pays masculin → « au Canada »." },
      { q: "Je vais ___ le médecin cet après-midi.", opts: ["à", "chez", "au", "en"], a: 1, exp: "Devant une personne → « chez le médecin »." },
      { q: "Il étudie ___ Ontario.", opts: ["au", "en", "à", "dans"], a: 1, exp: "Cette province se dit « en Ontario »." },
      { q: "Le train part ___ Vancouver à midi.", opts: ["à", "de", "en", "du"], a: 1, exp: "Le point de départ → « de Vancouver »." },
      { q: "Nous partons ___ Japon cet automne.", opts: ["en", "au", "à", "aux"], a: 1, exp: "Pays masculin → « au Japon »." },
      { q: "Elle est née ___ Espagne.", opts: ["au", "en", "à", "aux"], a: 1, exp: "Pays féminin → « en Espagne »." },
      { q: "Ils habitent ___ Alberta depuis peu.", opts: ["au", "en", "à", "dans"], a: 1, exp: "Cette province se dit « en Alberta »." },
      { q: "Je vais ___ épicerie acheter du lait.", opts: ["de l'", "à l'", "du", "au"], a: 1, exp: "Aller vers un lieu féminin à voyelle → « à l'épicerie »." },
      { q: "Ce colis vient ___ Montréal.", opts: ["à", "de", "en", "du"], a: 1, exp: "La provenance d'une ville → « de Montréal »." },
      { q: "Elle voyage ___ Manitoba la semaine prochaine.", opts: ["en", "au", "à", "aux"], a: 1, exp: "Cette province se dit « au Manitoba »." },
      { q: "On se retrouve ___ mes parents pour Noël.", opts: ["à", "chez", "au", "dans"], a: 1, exp: "Devant des personnes → « chez mes parents »." },
      { q: "Le vol pour ___ Italie dure huit heures.", opts: ["l'", "au", "en", "à"], a: 0, exp: "« Pour » + pays garde l'article → « pour l'Italie »." },
    ],
  },
  {
    id: "conjunctions",
    t: "Les conjonctions",
    d: "Connecteurs logiques : cause, conséquence, opposition, but.",
    lesson: [
      "Cause : parce que, puisque, car. Conséquence : donc, alors, c'est pourquoi.",
      "Opposition : mais, pourtant, cependant, bien que (+ subjonctif).",
      "But : pour que, afin que (+ subjonctif) ; afin de, pour (+ infinitif, même sujet).",
      "Les connecteurs structurent l'argumentation, essentielle aux tâches 3 de l'écrit et de l'oral.",
    ],
    qs: [
      { q: "___ il fasse froid, ils sortent patiner.", opts: ["Parce qu'", "Bien qu'", "Donc", "Afin qu'"], a: 1, exp: "L'opposition avec subjonctif (« fasse ») appelle « bien que »." },
      { q: "Il n'est pas venu ___ il était malade.", opts: ["parce qu'", "bien qu'", "pour qu'", "afin qu'"], a: 0, exp: "On exprime la cause → « parce qu' »." },
      { q: "Elle révise beaucoup ___ réussir son examen.", opts: ["pour que", "parce que", "afin de", "bien que"], a: 2, exp: "But avec le même sujet → « afin de » + infinitif." },
      { q: "Il pleuvait, ___ nous sommes restés à la maison.", opts: ["car", "donc", "parce que", "bien que"], a: 1, exp: "On exprime la conséquence → « donc »." },
      { q: "Je t'explique la règle ___ tu comprennes.", opts: ["pour que", "parce que", "puisque", "car"], a: 0, exp: "But avec changement de sujet → « pour que » + subjonctif." },
      { q: "___ tu es déjà là, aide-moi à ranger.", opts: ["Puisque", "Bien que", "Afin que", "Pour que"], a: 0, exp: "Une cause connue et évidente → « puisque »." },
      { q: "Il fait très froid ; ___, le ciel est dégagé.", opts: ["donc", "cependant", "car", "afin que"], a: 1, exp: "On oppose deux idées → « cependant »." },
      { q: "Elle est fatiguée, ___ elle continue de travailler.", opts: ["mais", "donc", "car", "pour que"], a: 0, exp: "Opposition simple entre deux propositions → « mais »." },
      { q: "Elle a réussi ___ elle a beaucoup travaillé.", opts: ["parce qu'", "bien qu'", "afin qu'", "pour qu'"], a: 0, exp: "On exprime la cause → « parce qu' »." },
      { q: "Il fait des économies ___ acheter une maison.", opts: ["pour", "pour que", "parce que", "bien que"], a: 0, exp: "But avec le même sujet → « pour » + infinitif." },
      { q: "___ il soit tard, elle continue à lire.", opts: ["Bien qu'", "Parce qu'", "Puisqu'", "Donc"], a: 0, exp: "Opposition avec subjonctif (« soit ») → « bien qu' »." },
      { q: "Je prends mon parapluie, ___ il pleut.", opts: ["car", "donc", "bien que", "afin que"], a: 0, exp: "Cause placée après la proposition → « car »." },
      { q: "Il a raté son train ; ___ il est arrivé en retard.", opts: ["cependant", "c'est pourquoi", "bien que", "car"], a: 1, exp: "On exprime la conséquence → « c'est pourquoi »." },
      { q: "Nous t'écrivons ___ tu sois bien informé.", opts: ["afin que", "afin de", "parce que", "puisque"], a: 0, exp: "But avec des sujets différents → « afin que » + subjonctif." },
      { q: "Elle aime le froid, ___ moi je le déteste.", opts: ["donc", "pourtant", "car", "afin que"], a: 1, exp: "On oppose deux idées → « pourtant »." },
      { q: "___ tu as raison, je change d'avis.", opts: ["Puisque", "Bien que", "Pour que", "Afin que"], a: 0, exp: "Une cause reconnue → « puisque »." },
    ],
  },
  {
    id: "adverbs",
    t: "Les adverbes",
    d: "Formation en -ment, place et adverbes d'intensité.",
    lesson: [
      "La plupart se forment sur le féminin de l'adjectif + -ment : lente → lentement.",
      "Adjectifs en -ant/-ent → -amment/-emment : courant → couramment, prudent → prudemment.",
      "Certains adverbes sont irréguliers : bon → bien, mauvais → mal, meilleur → mieux.",
      "Aux temps composés, l'adverbe court se place entre l'auxiliaire et le participe : « J'ai bien compris. »",
    ],
    qs: [
      { q: "Elle parle ___ trois langues.", opts: ["courantement", "couramment", "courament", "courramment"], a: 1, exp: "« Courant » (en -ant) → « couramment »." },
      { q: "Il conduit très ___ sur la glace.", opts: ["prudent", "prudemment", "prudamment", "prudentment"], a: 1, exp: "« Prudent » (en -ent) → « prudemment »." },
      { q: "Elle a ___ répondu à toutes les questions.", opts: ["correctement", "correct", "correctment", "correctemant"], a: 0, exp: "« Correcte » + -ment → « correctement »." },
      { q: "Nous avons ___ terminé le projet.", opts: ["finalement", "finale", "finallement", "finalemant"], a: 0, exp: "« Finale » + -ment → « finalement »." },
      { q: "Ils marchent ___ dans la neige épaisse.", opts: ["lentment", "lentement", "lenttement", "lentemment"], a: 1, exp: "« Lente » + -ment → « lentement »." },
      { q: "J'ai ___ compris la leçon.", opts: ["bien", "bonnement", "biennement", "bienment"], a: 0, exp: "L'adverbe de « bon » est « bien » (forme irrégulière)." },
      { q: "Le train arrive ___ à l'heure en hiver.", opts: ["rarement", "rarment", "raremant", "rareement"], a: 0, exp: "« Rare » + -ment → « rarement »." },
      { q: "Elle chante vraiment ___.", opts: ["merveilleux", "merveilleusement", "merveilleusment", "merveillement"], a: 1, exp: "« Merveilleuse » + -ment → « merveilleusement »." },
      { q: "Elle a répondu ___ à la question.", opts: ["franchement", "franc", "franchemant", "franchment"], a: 0, exp: "« Franche » + -ment → « franchement »." },
      { q: "Ils sont ___ arrivés en retard.", opts: ["évidemment", "évidamment", "évidentment", "évidement"], a: 0, exp: "« Évident » (en -ent) → « évidemment »." },
      { q: "Le professeur explique ___.", opts: ["clairement", "clair", "clairment", "clairemant"], a: 0, exp: "« Claire » + -ment → « clairement »." },
      { q: "Elle range ses affaires ___.", opts: ["soigneux", "soigneusement", "soigneusment", "soignement"], a: 1, exp: "« Soigneuse » + -ment → « soigneusement »." },
      { q: "Il a ___ réagi à la nouvelle.", opts: ["mal", "mauvaisement", "malement", "mauvaisment"], a: 0, exp: "L'adverbe de « mauvais » est « mal » (forme irrégulière)." },
      { q: "Nous avons ___ apprécié le spectacle.", opts: ["vraiment", "vrai", "vraiement", "vraimant"], a: 0, exp: "« Vrai » + -ment → « vraiment » (sans e)." },
      { q: "Elle nage ___ que son frère.", opts: ["mieux", "plus bien", "meilleur", "bienne"], a: 0, exp: "Le comparatif de « bien » est « mieux » (irrégulier)." },
      { q: "Ce train roule ___ sur cette voie.", opts: ["rapide", "rapidement", "rapidment", "rapidemant"], a: 1, exp: "« Rapide » + -ment → « rapidement »." },
    ],
  },
];
