export const GRAMMAR_TOPICS = [
  { id: "articles", t: "Les articles", d: "Définis, indéfinis et partitifs : le, la, un, du, des…", lesson: ["Les articles définis (le, la, l', les) désignent une chose précise ou une généralité : « J'aime le café. »", "Les articles indéfinis (un, une, des) introduisent un élément non identifié : « Elle cherche un appartement. »", "Les partitifs (du, de la, de l') expriment une quantité indéterminée : « Il boit du thé. »", "Après une négation, un/une/du/des deviennent « de » : « Je n'ai pas de voiture. »"], qs: [{ q: "Je ne mange pas ___ viande.", opts: ["de la", "de", "la", "une"], a: 1, exp: "Après une négation, le partitif « de la » devient « de »." }, { q: "Elle adore ___ hiver canadien.", opts: ["un", "l'", "du", "de"], a: 1, exp: "Devant une voyelle, l'article défini s'élide : « l'hiver »." }] },
  { id: "pronouns", t: "Les pronoms", d: "COD, COI, y, en et pronoms relatifs.", lesson: ["Les pronoms COD (le, la, les) remplacent un complément direct : « Ce film ? Je l'ai vu. »", "Les pronoms COI (lui, leur) remplacent « à + personne » : « Je lui téléphone. »", "« Y » remplace un lieu ou « à + chose » : « J'y pense. » « En » remplace « de + chose » : « J'en veux. »", "Qui, que, dont, où relient deux phrases : « La ville où j'habite. »"], qs: [{ q: "Tu as parlé à tes parents ? — Oui, je ___ ai parlé hier.", opts: ["les", "leur", "y", "en"], a: 1, exp: "« Parler à quelqu'un » → pronom COI « leur »." }, { q: "C'est le dossier ___ j'ai besoin.", opts: ["que", "qui", "dont", "où"], a: 2, exp: "« Avoir besoin de » → pronom relatif « dont »." }] },
  { id: "verbs", t: "Les verbes", d: "Groupes, auxiliaires et verbes pronominaux.", lesson: ["Le français compte trois groupes : -er (parler), -ir (finir) et les irréguliers (prendre, aller…).", "Aux temps composés, la plupart des verbes utilisent « avoir » ; les verbes de mouvement et pronominaux utilisent « être ».", "Avec « être », le participe s'accorde : « Elles sont arrivées. »", "Les verbes pronominaux se conjuguent avec un pronom réfléchi : « Je me lève à 7 h. »"], qs: [{ q: "Hier, elles ___ au parc La Fontaine.", opts: ["ont allé", "sont allées", "sont allés", "ont allées"], a: 1, exp: "« Aller » se conjugue avec « être » et s'accorde : « sont allées »." }] },
  { id: "tenses", t: "Les temps", d: "Présent, passé composé, imparfait, futur, conditionnel, subjonctif.", lesson: ["Le passé composé raconte des actions ponctuelles et achevées ; l'imparfait décrit le contexte et les habitudes.", "« Quand je suis arrivé (action), il neigeait (décor). »", "Le futur simple exprime une prévision ; le conditionnel, une hypothèse ou une politesse.", "Le subjonctif suit les expressions de volonté, de doute ou d'émotion : « Il faut que tu viennes. »"], qs: [{ q: "Il faut que vous ___ votre passeport.", opts: ["apportez", "apporterez", "apportiez", "apporter"], a: 2, exp: "« Il faut que » exige le subjonctif : « apportiez »." }, { q: "Avant, nous ___ chaque été au bord du lac.", opts: ["allions", "sommes allés", "irons", "irions"], a: 0, exp: "Habitude dans le passé → imparfait : « allions »." }] },
  { id: "prepositions", t: "Les prépositions", d: "à, de, en, chez, pour, avec les lieux et les pays.", lesson: ["Villes : « à » (à Montréal). Pays féminins ou à voyelle : « en » (en France, en Ontario*). Pays masculins : « au » (au Canada). Pluriels : « aux » (aux États-Unis).", "*Les provinces suivent des usages particuliers : en Ontario, au Québec, en Alberta, au Manitoba.", "« Chez » s'emploie devant une personne ou un commerce : « chez le médecin »."], qs: [{ q: "Elle habite ___ Québec depuis deux ans.", opts: ["en", "à", "au", "dans"], a: 2, exp: "Pour la province, on dit « au Québec » (mais « à Québec » pour la ville !)." }] },
  { id: "conjunctions", t: "Les conjonctions", d: "Connecteurs logiques : cause, conséquence, opposition, but.", lesson: ["Cause : parce que, puisque, car. Conséquence : donc, alors, c'est pourquoi.", "Opposition : mais, pourtant, cependant, bien que (+ subjonctif).", "But : pour que, afin que (+ subjonctif).", "Les connecteurs structurent l'argumentation, essentielle aux tâches 3 de l'écrit et de l'oral."], qs: [{ q: "___ il fasse froid, ils sortent patiner.", opts: ["Parce qu'", "Bien qu'", "Donc", "Afin qu'"], a: 1, exp: "L'opposition avec subjonctif (« fasse ») appelle « bien que »." }] },
  { id: "adverbs", t: "Les adverbes", d: "Formation en -ment, place et adverbes d'intensité.", lesson: ["La plupart se forment sur le féminin de l'adjectif + -ment : lente → lentement.", "Adjectifs en -ant/-ent → -amment/-emment : courant → couramment.", "Aux temps composés, l'adverbe court se place entre l'auxiliaire et le participe : « J'ai bien compris. »"], qs: [{ q: "Elle parle ___ trois langues.", opts: ["courantement", "couramment", "courament", "courramment"], a: 1, exp: "« Courant » → « couramment » (règle des adjectifs en -ant)." }] },
];
